### ISSUE TITLE
nuget/v2/GetUpdates() web requests fail so the updates window doesn't work

### ISSUE THREAD

**Issue by ForrestTrepte** [GlitchEnzo/NuGetForUnity#101]
I'm seeing some errors in web request with GetUpdates(). This occurs when I attempt to install a package from a VSTS feed that has a dependency on another package. It seems to be preventing these dependencies from being automatically installed.

I'll need to do some further investigation to see if this is an incompatibility specific to the VSTS feed or something related to way NuGetForUnity if making its requests.

For now I'm just posting this error message so others are aware of it.

Here is an example of the sort of errors I'm receiving:
``Unable to retrieve package list from https://myteam.pkgs.visualstudio.com/_packaging/myteam/nuget/v2/GetUpdates()?packageIds='Performance'&versions='1.0.2835'&includePrerelease=false&includeAllVersions=false&targetFrameworks=''&versionConstraints=''
System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at NugetForUnity.NugetHelper.RequestUrl (System.String url, System.String password, System.Nullable`1[T] timeOut) [0x0007f] in D:\s\NuGetForUnity\Assets\NuGet\Editor\NugetHelper.cs:1144 
  at NugetForUnity.NugetPackageSource.GetPackagesFromUrl (System.String url, System.String password) [0x0005f] in D:\s\NuGetForUnity\Assets\NuGet\Editor\NugetPackageSource.cs:333 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetPackageSource:GetPackagesFromUrl(String, String) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetPackageSource.cs:345)
NugetForUnity.NugetPackageSource:GetUpdates(IEnumerable`1, Boolean, Boolean, String, String) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetPackageSource.cs:432)
NugetForUnity.NugetHelper:GetUpdates(List`1, Boolean, Boolean, String, String) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetHelper.cs:813)
NugetForUnity.NugetWindow:UpdateUpdatePackages() (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:338)
NugetForUnity.NugetWindow:DrawPackage(NugetPackage) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:820)
NugetForUnity.NugetWindow:DrawOnline() (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:513)
NugetForUnity.NugetWindow:OnGUI() (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:378)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)``

**Comment by jwittner** [comment]
Looking into this now.

**Comment by jwittner** [comment]
I can confirm that these queries succeed on Nuget.org.

**Comment by jwittner** [comment]
@mhutch Any idea why the VSTS GetUpdates() route via API 2 would always return 404? If not, do you know who might help me out on the VSTS Package Management team?

**Comment by jwittner** [comment]
Moved the dependencies issue to #107 as the GetUpdates() exception is caught and logged - it breaks the Updates pane in the window, but isn't what prevents dependencies from installing.

**Comment by mhutch** [comment]
@jwittner not sure but @rrelyea may know

**Comment by jwittner** [comment]
@mhutch Thanks for forwarding along!

**Comment by ForrestTrepte** [comment]
Looking at the metadata from nuget.org (https://www.nuget.org/api/v2/$metadata) reveals that nuget.org supports Packages, Search, FindPackagesById, and GetUpdates. Getting metadata from my VSTS feed only shows Packages, FindPackagesById, and Search. Similar to the issue that @jwittner  tracked down in #107, it looks like VSTS simply doesn't include the GetUpdates feature. I wonder if we can create a fallback to emulate it using the other functions such as Search or FindPackagesById.

**Comment by jwittner** [comment]
Looks like some version of FindPackagesById might be best as it finds the exact package Id. A version of `GetSpecificPackage` that returns the latest acceptable version might be a pretty straightforward solution.

**Comment by ForrestTrepte** [comment]
I was taking a look at this and mocked up a version that attempted to fallback to FindPackagesById. @jwittner, take a look at my [dev/getUpdatesFallback branch](https://github.com/ForrestTrepte/NuGetForUnity/tree/dev/getUpdatesFallback) to see if you like this approach. I'm going to be working on a different project for a little while so probably won't have time to look into this further.

**Comment by jwittner** [comment]
@ForrestTrepte I like a lot of what you have there - I was heading toward the same FindPackagesById method change. Given that VSTS supports everything that the Visual Studio and shell NuGet clients use I'm thinking we should move to a single implementation that's more along those lines instead of setting up the new implementation as a fallback. The fallback here is likely to be more stable for other servers too I think, since those tools are probably the most thoroughly tested against them.

**Comment by jwittner** [comment]
@ForrestTrepte - Any chance you want to take your branch all the way and get this issue resolved? For us VSTS users it makes the client seem error prone and I'm afraid will detract from the experience as we try to push this out more broadly to our teams.

**Comment by ForrestTrepte** [comment]
@jwittner Agreed. We should fix this. I can't get to it right away, but may be able to take a look later in the week.
