### ISSUE TITLE
Fix repositoryPath

### ISSUE THREAD

**Issue by jdnichollsc** [GlitchEnzo/NuGetForUnity#102]
Hi guys,
What do you think to fix the value of **repositoryPath** to `.\Assets\Packages`?

Regards, Nicholls

**Comment by Ziugy** [comment]
Ah yes, looks like the code loading the config file is expecting `./` and the path combine is not robust. This definitely should be made more flexible.

By default, `./Packages` gets appended to [Application.dataPath](https://docs.unity3d.com/ScriptReference/Application-dataPath.html) and thus what you're looking for. Try swapping back to `./Packages` and let me know if that works for you.

**Comment by ForrestTrepte** [comment]
@Ziugy, I believe this issue was fixed by #103. Please let us know if that's not the case.
