### ISSUE TITLE
Add official Mac support

### ISSUE THREAD

**Issue by GlitchEnzo** [GlitchEnzo/NuGetForUnity#105]
There appear to be some issues with using NuGetForUnity on a Mac.  The issues need to be tracked down and resolved.  It would be greatly beneficial if a Mac-using collaborator was to join, since I don't have a Mac myself.

Any volunteers out in the ether?

**Comment by GlitchEnzo** [comment]
It appears the current version of Ionic.Zip doesn't work on Mac.  Apparently the latest version of DotNetZip works, as stated here: https://github.com/GlitchEnzo/NuGetForUnity/issues/86#issuecomment-341414401

**Comment by rgarrett7** [comment]
I have a Mac and am getting the same error.  I am willing to help with debugging.

**Comment by dnlbschff** [comment]
I'm trying to get it to work on High Sierra as well. Happy to help with debugging!

**Comment by GlitchEnzo** [comment]
Thanks guys! And thanks for confirming that I need to update the zip library.

**Comment by jwittner** [comment]
Given reports of good use and no explicit action on this, I'm closing it.
