### ISSUE TITLE
Audio unzip issue: "Unspecified error during import of AudioClip"

### ISSUE THREAD

**Issue by Ziugy** [GlitchEnzo/NuGetForUnity#114]
I'm seeing an issue where all ogg files in my package aren't able to be loaded in Unity.

This seems to be an issue with the timestamp after unzipping: [https://forum.unity.com/threads/unspecified-error-during-import-of-audioclip-assets.312946/](https://forum.unity.com/threads/unspecified-error-during-import-of-audioclip-assets.312946/)

This can be worked-around with running touch or [COPY](http://answers.unity3d.com/questions/990669/unspecified-error-during-import-of-audioclip-asset.html) on the command line.

**Comment by GlitchEnzo** [comment]
Can you confirm that it's a timestamp issue?  

Do you know if the timestamps are correct _before_ being packaged up?  Meaning, do you think this is an issue with NuGetForUnity unzipping the package and messing with the timestamp, or did the file have an incorrect timestamp to begin with?

**Comment by Ziugy** [comment]
The issue looks to be coming from general unzipping of audio files, as the thread linked stated. It's unclear why the file's timestamp are set in the future. I have confirm that the time is in the future after pulling down the package and that running `touch` on the file reset the timestamp to the current time which fixed the load issue in Unity.

**Comment by jwittner** [comment]
Closing as this is very old and audio files have been imported successfully more recently.
