### ISSUE TITLE
Having problem in installing google cloud api libraries

### ISSUE THREAD

**Issue by naisu1412** [GlitchEnzo/NuGetForUnity#115]
I am trying to import the google speech cloud libraries using NuGetForUnity but the "lib" folder seems empty and not getting the dlls correctly? I tried other libraries and it seem to work fine. possible fix?

img: [https://imgur.com/a/Yd6bZ](url)

**Comment by Ziugy** [comment]
Looks like NuGet for Unity might need the [target frameworks](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks) expanded further.

Maybe create a PR with the expanded set?

**Comment by naisu1412** [comment]
Oh! Didn't noticed that, changing the framework to 4.6 solved the issue thanks :) .
