### ISSUE TITLE
Doesn't work on macOS 10.13

### ISSUE THREAD

**Issue by imyjimmy** [GlitchEnzo/NuGetForUnity#119]
When trying to install a NuGet package, Unity's console shows the following error:
 
`System.ArgumentException: Path is empty
  at System.IO.Directory.CreateDirectory (System.String path) [0x0001c] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:78 
  at Ionic.Zip.ZipEntry.InternalExtract (System.String baseDir, System.IO.Stream outstream, System.String password) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetHelper:Install(NugetPackage, Boolean)
NugetForUnity.NugetWindow:DrawPackage(NugetPackage)
NugetForUnity.NugetWindow:DrawOnline()
NugetForUnity.NugetWindow:OnGUI()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

The Path string comes up empty. I'm guessing NugetHelper.cs must not be getting the right path string, and is setting it to be nothing. Another concern I have is "/Users/builduser" is not an actual user on my computer. I'm new to .NET so I'm not sure if 1. its something that Mono did or 2. if statement 1. even makes sense.

**Comment by GlitchEnzo** [comment]
#105

**Comment by jwittner** [comment]
May be resolved by #368, but I don't have a Mac to test.

**Comment by jwittner** [comment]
Given the age of this issue, and successful use being reported on Mac by the community I'm closing this.
