### ISSUE TITLE
VSTS Authentication fails for .Net 3.5 Unity framework target

### ISSUE THREAD

**Issue by jwittner** [GlitchEnzo/NuGetForUnity#120]
The response indicates that the authentication header isn't written correctly to the request stream.

**Comment by ForrestTrepte** [comment]
I'm taking a look to see if this can be solved by using UnityWebRequest.

**Comment by ForrestTrepte** [comment]
I couldn't quite figure out how to make this work via UnityWebRequest. I was successful in loading package information from the VSTS feed using UnityWebRequest without the need for bypassing certificate validation. But unfortunately, when it came time to download the package itself, I had an InvalidAuthenticationInfo error and was unable to download the package even when using .NET 4.6. I'm giving up, at least for now.

**Comment by Ziugy** [comment]
Ran into this today as a silent error. We should at least notify the user that this failed.

**Comment by jwittner** [comment]
As .Net 3.5 is no longer the default I'm closing this as won't fix.
