### ISSUE TITLE
File not found exception 

### ISSUE THREAD

**Issue by rgarrett7** [GlitchEnzo/NuGetForUnity#124]
On Windows 10, Unity 2017.3.0f3: I get the following error.  I agree that this file path does not exist.  Perhaps I need to run as admin so that it can be created?

FileNotFoundException: Could not load file or assembly 'Accord, Version=3.0.2.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7' or one of its dependencies.
System.Reflection.MonoMethodInfo.GetMethodInfo (IntPtr handle) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:59)
System.Reflection.MonoMethodInfo.GetAttributes (IntPtr handle) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:75)
System.Reflection.MonoMethod.get_Attributes () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:245)
System.Reflection.MethodBase.get_IsSpecialName () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:184)
UnityEditor.Build.BuildPipelineInterfaces.InitializeBuildCallbacks (BuildCallbacks findFlags) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:191)

**Comment by GlitchEnzo** [comment]
It looks like something you installed is missing a dependency (Accord).  Could you provide more information about what package (including version) you were trying to install?

**Comment by jwittner** [comment]
No follow up on this, closing unless we can get more information.
