### ISSUE TITLE
Create PDF documenation

### ISSUE THREAD

**Issue by GlitchEnzo** [GlitchEnzo/NuGetForUnity#127]
NuGetForUnity was submitted to the Unity Asset Store, but it was rejected due to it not having any PDF documenation inside.  The markdown readme here on GitHub should be converted into a PDF and included in the created .unitypackage file.

**Comment by jwittner** [comment]
So excited to see this moving onto the store!

**Comment by GlitchEnzo** [comment]
The PDF was added and NuGet For Unity was re-submitted to the Unity Asset Store and accepted.
It is live here: https://assetstore.unity.com/packages/tools/utilities/nuget-for-unity-104640

**Comment by jwittner** [comment]
Way to go!!!!!!
