### ISSUE TITLE
Support native libraries

### ISSUE THREAD

**Issue by GlitchEnzo** [GlitchEnzo/NuGetForUnity#14]
Unity is terrible with it's handling of native DLLs, so this tool must provide some sort of additional support for them.

Unity requires native DLLs to be in the Assets/Plugins directory BUT Unity locks the files and there is no way to get it to release the lock without closing the Editor.  This creates complications such as saving any open scene, closing, copying/overwriting whatever DLLs need to be copied, re-opening Unity with whatever scene/project it had open, and continuing with the installation of the packages.

**Comment by GlitchEnzo** [comment]
Since it is the Unity Editor itself that locks the files, it's doubtful that there is any change that can be done to NuGetForUnity to resolve this.

**Comment by jwittner** [comment]
I don't believe the Unity plugin folder is a requirement anymore.
