### ISSUE TITLE
Online Tab Update Button Confusing

### ISSUE THREAD

**Issue by Ziugy** [GlitchEnzo/NuGetForUnity#141]
## Description
Update button in the online tap shows my current version. To the right of the package in the list item shows the latest version. Clicking this button is always confusing.

Here's a picture for reference:
<img width="353" alt="capture" src="https://user-images.githubusercontent.com/6968091/37357216-0a0620ec-26a5-11e8-9d79-196dd78b5d3a.PNG">

- **NuGet Package:** Personal package.
- **NuGetForUnity Version:** 0.0.14
- **Unity Version:** Unity 2017.3.1f1
- **Operating System:** Windows 10 | 16299

**Comment by ForrestTrepte** [comment]
I think the confusion is that the Update button seems like it should show what the action is going to do--the version it will update TO instead of the version it is updating FROM.

To be perfectly clear, perhaps we should show from and to on the button like this: `Update [1.0.4179] ->[1.0.4196]` but there probably isn't room on the button for that.

**Comment by ForrestTrepte** [comment]
Since there isn't room on the button, I propose that we simply have the button say "Update" and on the left hand side add additional text for "installed version [1.0.4179]".

**Comment by ForrestTrepte** [comment]
Tried it and it ends up looking messy/complicated to my eye. Particularly bad if you're showing all version and currently installed gets repeated on every line:
![update](https://user-images.githubusercontent.com/17389739/37376669-a94d2884-26e2-11e8-9d1d-d7571e0898d2.JPG)

Back to the drawing board. Maybe play with the button area e.g. Update to [1.0.4179] with text underneath the button saying current. This would be a little bit similar to the package manager in Visual Studio that shows Installed and Latest in the right-hand pane.

**Comment by ForrestTrepte** [comment]
Text underneath the button looks nicer:
![update2](https://user-images.githubusercontent.com/17389739/37437404-41db35f6-27aa-11e8-821a-6978a442f8f9.JPG)

**Comment by GlitchEnzo** [comment]
I think that's a good way to make the current UI clearer and less confusing.

In general I hope that we can redo the UI at some point to resemble NuGet in VS2017 more closely, with a second column containing the package information.

![image](https://user-images.githubusercontent.com/3473293/37464851-0593fa48-2830-11e8-9174-88c2f8cc8b6a.png)
