### ISSUE TITLE
How to use it in rider?

### ISSUE THREAD

**Issue by xahon** [GlitchEnzo/NuGetForUnity#150]
## Description
Hello. How do I use it? I installed this extension via unity asset manager then installed postsharp library. After that I have a directory `Packages` with `.nupkg`s. What's now? Rider doesn't recognize them automatically. Do I able to configure in on IDE's level to share this config with my teammates? I'm very new to c# so sorry if question looks dumb

- **NuGet Package:** PostSharp
- **NuGetForUnity Version:** 0.0.13
- **Unity Version:** 2018.1.0b13
- **Operating System:** Ubuntu 16.04.3

**Comment by jwittner** [comment]
NuGetForUnity installs packages into the Assets folder of Unity projects. Unity then compiles those assets like any other piece of content. Using the Rider IDE from JetBrains should effect the use of NuGetForUnity.
