### ISSUE TITLE
prevent users from editing package content files

### ISSUE THREAD

**Issue by ForrestTrepte** [GlitchEnzo/NuGetForUnity#151]
When the read-only option (see #137) is enabled, it would be helpful if we can prevent users in the Unity editor from modifying content inside packages. I'm not sure of exactly how this can be implemented. Perhaps a custom editor or part of the content serialization process can be used to prevent such edits.

Some history:
In #137, we added a read-only setting for installing packages. When this option is enabled, package files are read only. This prevents users from accidentally editing them--typically the contents of a package are in an ignore list so changes can't be checked in. This works for .cs source code files, for which editors typically warn the user or don't allow editing read-only files. However, Unity seems to be perfectly happy to edit content files such as Prefabs.

**Comment by ForrestTrepte** [comment]
[This thread](https://forum.unity.com/threads/why-does-unity-unlock-a-read-only-file.35462/) contains a code snippet using an AssetModificationProcessor to warn about modifying read-only files. We should try that and see if it works.

**Comment by jwittner** [comment]
Git hooks can be registered that can enforce consistency - I believe.

NuGet, as you suggested, seems a more logical place given it owns the packages whose consistency we want to manage. I like it again for being more consistent with the VS experience.

**Comment by ForrestTrepte** [comment]
Since the package files are ignored, how could Git hooks enforce consistency on these files?

I'm not sure there's a direct analogy with the VS experience because typically NuGet would be pulling in libraries that are externally referenced by a project. It seems like Unity content is uniquely likely to become interwoven in the editor leading to confusion where you inadvertently edit package files.

**Comment by jwittner** [comment]
I just meant that preventing modification via the editor is more in line with VS experience than attempting a solution at the source control level. You're right though about the hooks not being viable because the packages are ignored, I was hoping there was still a hook even for ignored files.

**Comment by jwittner** [comment]
Closing as we have the 'read only package files' option now though it comes with it's own problems.
