### ISSUE TITLE
Can't update a package, installer keeps installing oldest version

### ISSUE THREAD

**Issue by MostHated** [GlitchEnzo/NuGetForUnity#153]
## Description
[Describe the issue you have.]
Hello,
    I am trying to install a package but it just keeps installing the same original one and not the newer one. When I originally hit install it only showed the newest one, but installed the oldest, now it is showing update available, every time I hit it, it just reinstalls the same old one.
- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
RavenDB Client 4.0.3

- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
0.0.15
- **Unity Version:** [What version of Unity are you using?]
2018.1 0.f1
- **Operating System:** [What OS are you on?]
Windows 10 x64

https://i.imgur.com/JSVw0xL.png

**Comment by jwittner** [comment]
I am able to reproduce this in Unity 2017.4.2f2 as well. Even an initial install of RavenDB.Client results in Version 1.0.531 being installed. Must be an inconsistency in how we find packages for listing vs. installing.

**Comment by MostHated** [comment]
Yeah, I ended up having to just start a new VS project, downloading the NuGet normally and then put tossed the stuff in my project, lol.

**Comment by bleppie** [comment]
Same here.

## Description
Trying to install Serilog 2.8.0, NuGet installs 0.1.6. No error or warning messages.

Hitting the Update button does nothing. No error or warning messages.

Trying to install Serilog.File, which depends on Serilog 2.5.0 or greater I get this:
Could not find Serilog [2.5.0, ) or greater.
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetHelper:InstallIdentifier(NugetPackageIdentifier, Boolean)
NugetForUnity.NugetHelper:Install(NugetPackage, Boolean)
NugetForUnity.NugetHelper:InstallIdentifier(NugetPackageIdentifier, Boolean)
NugetForUnity.NugetWindow:DrawPackage(NugetPackage, GUIStyle, GUIStyle)
NugetForUnity.NugetWindow:DrawPackages(List`1)
NugetForUnity.NugetWindow:DrawOnline()
NugetForUnity.NugetWindow:OnGUI()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

- **NuGet Package:** Serilog 2.8.0
- **NuGetForUnity Version:** 1.0.3
- **Unity Version:** 2018.3.0f2
- **Operating System:** Mac OSX

**Comment by cooloon** [comment]
## Workaround of this issue
I found this happens when there are more than 100 versions in Version History.
The problem is, NuGet API returns at most 100 records in one time.
(You can check the count of elements in GetPackagesFromUrl() return value)

My possible workaround is, not ideal though, replacing
```
url = string.Format("{0}FindPackagesById()?$orderby=Version asc&id='{1}'", ExpandedPath, package.Id);
```
with
```
url = string.Format("{0}FindPackagesById()?$orderby=LastUpdated desc&id='{1}'", ExpandedPath, package.Id);
```
in NugetPackageSource.cs (line: 136)

**Comment by aknoerig** [comment]
Also see #209 -

Same here with NLog. NuGetForUnity shows the latest version correctly as 4.6.6, but when I click install, it ends up installing version 1.0.0.505.

* NuGet Package: NLog
* NuGetForUnity Version: 1.2.1
* Unity Version: 2019.2.0f1
* Operating System: MacOS 10.14.6
