### ISSUE TITLE
Empty lib folders

### ISSUE THREAD

**Issue by aalmada** [GlitchEnzo/NuGetForUnity#154]
## Description
First of all, thanks for developing this great tool!
I'm trying to add packages that don't have a net35 folder to a Unity project with player runtime set to .NET 4.6. Everything seems to work except the lib folders are all empty. I turned verbose on and no issue is reported.
I looked into your source and it seems this case should be handled. Am I doing something wrong?

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
Bonsai.Vision 2.3.0
- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
0.0.15
- **Unity Version:** [What version of Unity are you using?]
2017.4.1f1 Personal
- **Operating System:** [What OS are you on?]
Windows 10 Pro 1803

**Comment by jwittner** [comment]
Hmmm, I can't repro this with Unity Pro 2017.4.2f2, Windows 10, NuGetForUnity 0.0.15. It looks like I end up with all the appropriate folders as such: 

```
NuGetForUnity\Assets\Packages\Bonsai.Core.2.3.0\lib\net45\Bonsai.Core.dll                 
NuGetForUnity\Assets\Packages\Bonsai.Dsp.2.3.0\lib\net45\Bonsai.Dsp.dll                   
NuGetForUnity\Assets\Packages\Bonsai.System.2.3.0\lib\net45\Bonsai.System.dll             
NuGetForUnity\Assets\Packages\Bonsai.Vision.2.3.0\lib\net45\Bonsai.Vision.dll             
NuGetForUnity\Assets\Packages\Newtonsoft.Json.6.0.8\lib\net35\Newtonsoft.Json.dll         
NuGetForUnity\Assets\Packages\OpenCV.Net.3.3.1\lib\net40\OpenCV.Net.dll                   
NuGetForUnity\Assets\Packages\Rx-Core.2.2.5\lib\net45\System.Reactive.Core.dll            
NuGetForUnity\Assets\Packages\Rx-Interfaces.2.2.5\lib\net45\System.Reactive.Interfaces.dll
NuGetForUnity\Assets\Packages\Rx-Linq.2.2.5\lib\net45\System.Reactive.Linq.dll            
```
My Unity Configuration:
![image](https://user-images.githubusercontent.com/12958442/39546824-887dbffc-4e0a-11e8-8997-5cbb956009f1.png)

No compiler errors either! Maybe there's something about the personal edition?

**Comment by aalmada** [comment]
Thanks for checking. It's strange as I had the same settings.
I'm very sorry, but I installed 2018.1 so now I can't reproduce the issue.
Maybe close this issue and see what happens once NuGetForUnity works on 2018.1.
