### ISSUE TITLE
Can't install xBIM WindowsUI

### ISSUE THREAD

**Issue by sINFsehill** [GlitchEnzo/NuGetForUnity#157]
## Description
- **NuGet Package:** xBIM WindowsUI [4.0.11]
- **NuGetForUnity Version:** 0.0.15
- **Unity Version:** 2018.1.0f2
- **Operating System:** Windows 10

When I want to install xBIM WindowsUI it is unable to install xBIM Essentials and throws a NugetForUnity NullReference.
![xbim_nuget_error](https://user-images.githubusercontent.com/27274617/39630342-57bf0474-4faf-11e8-9fda-7308d6e25bc1.PNG)

**Comment by sINFsehill** [comment]
I found out that it only can't install SharpZipLib from the xBIM Essentials dependencies. Maybe there is the main problem?

**Comment by szyuGH** [comment]
Any solution for this yet?

**Comment by jwittner** [comment]
Could not reproduce with latest versions of XBim.WindowsUI and NuGetForUnity in Unity 2018.4.30f1.
