### ISSUE TITLE
Exact matching of ID on NugetPackageSource.GetSpecificPackage

### ISSUE THREAD

**Issue by SINePrime** [GlitchEnzo/NuGetForUnity#161]
## Description
Currently `GetSpecificPackage` uses the first result (`FirstOrDefault`) from `FindPackagesById`. If there are multiple matching Ids, this may return the wrong package. eg, searching for `dot.Common` and getting `dot.Common.Graphs`.

- **NuGet Package:** dot.Common
- **NuGetForUnity Version:** 0.0.15
- **Unity Version:** 2018
- **Operating System:** Windows

**Comment by jwittner** [comment]
This should be resolved now.
