### ISSUE TITLE
Idea: Integration with Unity Package Manager (UPM)

### ISSUE THREAD

**Issue by capyvara** [GlitchEnzo/NuGetForUnity#165]
## Description

On Unity 2017+ there's the UPM that already allows partial support for local client side controlled packages.

#### Some references:

[UPM: How to make a custom package](https://gist.github.com/LotteMakesStuff/6e02e0ea303030517a071a1c81eb016e)

[Local client side packages?](https://forum.unity.com/threads/local-client-side-packages.532521/)

### Idea outline
- Put the config files at `Packages/...` instead of `Assets/...`
- Install the packages directly into `Packages/...` instead of `Assets/Packages/...`
- Dynamically create a `Packages/Name/package.json` with the info from NuGet package

Or alternatively (not sure it this will work):
- Install the packages at unity shared cache folder (on mac for example is `~/Library/Unity/cache/packages/packages.unity.com/name@version/`) 
- Modify `Packages/manifest.json` dependencies and pray for Unity to find it

Or (not sure if will work too):
- Let NuGet install to the [default](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders) cache path 
- Point to it using the file: scheme inside the `manifest.json`

**Comment by jwittner** [comment]
This is not recommended by Unity here in the upgrade guide for the Package Manager drop: https://docs.unity3d.com/Manual/UpgradeGuide20181.html
