### ISSUE TITLE
Allow installation of older package versions

### ISSUE THREAD

**Issue by delphinius81** [GlitchEnzo/NuGetForUnity#167]
## Description
NuGet only retrieves the latest version of the selected nuget package. Sometimes you are working with other packages that are built against earlier versions. It would be nice to be able to select the older version from the package list.

- **NuGet Package:** All packages
- **NuGetForUnity Version:** 0.;0.15
- **Unity Version:** 2018.1
- **Operating System:** Win 10

**Comment by jwittner** [comment]
Unfortunately this appears to be a limitation of the nuget.org API. You can modify the packages.config to include whatever version you need. =)
