### ISSUE TITLE
It should use netstandard package for .net 4.x project for Unity 2018.

### ISSUE THREAD

**Issue by SetoKaiba** [GlitchEnzo/NuGetForUnity#168]
Because the .net 4.x project for 2018 is compatible with netstandard 2.0 profile.
It's a super for netstarndard 2.0 profile.
And also, if uses .net 4.5 package instead of netstandard one.
The new incremental compiler won't compile.

**Comment by jwittner** [comment]
I believe that if you select the .Net standard in Unity it should select that framework now when installing packages.
