### ISSUE TITLE
Duplicate dependencies causing compilation errors

### ISSUE THREAD

**Issue by SINePrime** [GlitchEnzo/NuGetForUnity#171]
## Description
When a package has a dependency on an assembly already present in Unity, compilation errors arise from duplicate assemblies.

Some such errors:
- Unity error CS1704
- The type "..." exists in both '...' and '...'

**NuGet Package:** QuickGraph.All
**NuGetForUnity Version:** 0.0.16
**Unity Version:** 2018.1.1f1
**Operating System:** Windows 10

**Comment by jwittner** [comment]
I believe this has been fixed by #303
