### ISSUE TITLE
Cannot add menu item warnings

### ISSUE THREAD

**Issue by Merglasch** [GlitchEnzo/NuGetForUnity#174]
## Description
NuGetForUnity seems to try and add all the menu items several times, throwing the following warning and several more like it on compilation:

Cannot add menu item 'Assets/NuGet/Open Nuspec Editor' for method 'NuspecEditor.DisplayNuspecEditor' because a menu item with the same name already exists.

- **NuGet Package:** none
- **NuGetForUnity Version:** 0.0.16
- **Unity Version:** 2017.4.2f2
- **Operating System:** Windows 10

**Comment by listvin** [comment]
Same here
Totally 14 for different items

    NuGet Package: none
    NuGetForUnity Version: 3.0.5
    Unity Version: 2021.3.8f1
    Operating System: Linux Mint 21

Amazing package by the way, thank you!

**Comment by JoC0de** [comment]
I never saw this kind of error. Is it a error that always happens when you restart Unity? Did you install NuGetForUnity using UPM?
