### ISSUE TITLE
Use of `#if UNITY_[*]` to change behavior across version numbers won't work in DLL

### ISSUE THREAD

**Issue by YossiMH** [GlitchEnzo/NuGetForUnity#175]
This is because the DLLs are being compiled outside of Unity, which means, as I understand it, that none of the `UNITY_[*]` version symbols are defined. I would expect the result of this to be that only the contents of the `#else` blocks actually make it into the DLL which is distributed in the project's releases. This could cause problems with using the DLL in newer versions of Unity if deprecated APIs are used within the `#else` blocks.

The only workaround that I can think of offhand is to provide different packages containing different DLLs to be used in different versions of Unity.

**Comment by jwittner** [comment]
I'm tempted to argue that we should move everything back to the latest supported version and drop all the #ifdef for the newer stuff. @GlitchEnzo  mentioned there is at least one big user of this library that is on 5.6. We've recently upgraded to minimum 5.3 to get the JsonUtility support.

Do you have a specific version of Unity in which the current DLLs are failing?

**Comment by JoC0de** [comment]
In the current version we don't have `#if UNITY_[*]` exactly for that reason. Every Unity version specific code is in if-statements. So there is no problem.
