### ISSUE TITLE
Dependencies not automatically installed

### ISSUE THREAD

**Issue by Chris3606** [GlitchEnzo/NuGetForUnity#176]
## Description
Not sure if this is a bug or missing feature, but dependencies of NuGet packages aren't being automatically resolved and downloaded with the package, like they typically are with NuGet in Visual Studio.  For instance, my own library GoRogue (a .NET Standard 2.0 library) depends on Troschuetz.Random and OptimizedPriorityQueue, but those dependencies are not automatically installed when I install GoRogue via NugetForUnity.  Instead Unity automatically unloads GoRogue after intstallation, as it considers it broken (missing dependencies).  If I install the dependencies via NuGetForUnity first, it works correctly.

- **NuGet Package:** GoRogue 1.5.0
- **NuGetForUnity Version:** 0.0.16
- **Unity Version:** 2018.2.2f1
- **Operating System:** Windows 10

**Comment by tomzorz** [comment]
"+1" to the SignalR issue, it's not downloading the references. (Although the main package did install "successfully" for me.)

**Comment by jwittner** [comment]
I believe this is resolved by #303
