### ISSUE TITLE
Installing custom NewGet Package

### ISSUE THREAD

**Issue by Storm-Develop** [GlitchEnzo/NuGetForUnity#177]
## Description
Authorization problem.  Can't install the custom package.

- **NuGet Package:** [Custom made in-house package]
- **NuGetForUnity Version:** [ver. 0.0.13]
- **Unity Version:** [Unity 2018.1.0f2]
- **Operating System:** [Windows 10]

So I noticed that you guys don't have the field for the username. So I added manually into Nuger.Config.
![image](https://user-images.githubusercontent.com/11896104/43974121-27ec2c94-9c9f-11e8-90fe-acfa2c611579.png)
Unfortunately, it's still doesn't work.
![image](https://user-images.githubusercontent.com/11896104/43974171-4ec9f2d8-9c9f-11e8-9d65-97362d7ffc8f.png)

My Nuget.Config file
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="http://www.nuget.org/api/v2/" />
    <add key="engineering" value="https://customurl/" />
  </packageSources>
  <disabledPackageSources />
  <packageSourceCredentials>
    <engineering>
	  <add key="Username" value="admin" />
      <add key="clearTextPassword" value="password" />
    </engineering>
  </packageSourceCredentials>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <config>
    <add key="repositoryPath" value="./Packages" />
    <add key="DefaultPushSource" value="http://www.nuget.org/api/v2/" />
  </config>
</configuration>

**Comment by jwittner** [comment]
User name is now available in the credentials. =)
