### ISSUE TITLE
Wrong path for cache folder on Mac 

### ISSUE THREAD

**Issue by vandelpal** [GlitchEnzo/NuGetForUnity#184]
On my mac cache folder in ~/.local/share\NuGet\\Cache, where «share\NuGet\Cache» is name folder!
Use Path.Combine in NugetHelper.cs instead of:

 public static readonly string PackOutputDirectory = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\NuGet\\Cache";

- **NuGetForUnity Version:** 0.0.16
- **Unity Version:** 5.5.3p4
- **Operating System:** MacOS

**Comment by JoC0de** [comment]
We now have `Path.Combine` so it should be fixed
