### ISSUE TITLE
Doesn't show package is installed, but shows "uninstall" on "online" tab

### ISSUE THREAD

**Issue by dylanh724** [GlitchEnzo/NuGetForUnity#192]
## Description
* In the online tab, it shows package is installed (JSON.NET, in this case)
* In the Installed tab, it doesn't show ANY packages installed - which makes no sense since I can uninstall JSON.NET in the 1st tab.

## Additional Notes
* Since it doesn't detect installed packages in the 'installed' tab, I have no idea if the updater is actually searching for updates for my package. It should probably list what packages it searched updates for?
* The NuGet ver, itself, should probably show somewhere within this tab - no need to make us dig for it.

![image](https://user-images.githubusercontent.com/8840024/46853744-8d0da080-ce31-11e8-976c-113ceadf6c08.png)

- **NuGet Package:** Json.NET [11.0.2]
- **NuGetForUnity Version:** Since the version isn't displayed anywhere, I have no idea. But _latest_, probably.
- **Unity Version:** 5.6.5p4
- **Operating System:** Win10

**Comment by JoC0de** [comment]
Very old issue + can't reproduce.
