### ISSUE TITLE
Allow changing the path for NuGet.config and packages.config in Settings screen.

### ISSUE THREAD

**Issue by XtroTheArctic** [GlitchEnzo/NuGetForUnity#195]
Please allow changing the path for NuGet.config and packages.config in Settings screen. Hard coded paths in Unity plugins are HORRIBLE! :(

I'll fork the repo and change the path manually for now. I hope you can add this feature so I don't have to update my fork for eternity.

**Comment by jwittner** [comment]
Can you lay out your use case for other config file locations? Not opposed to it, just want to understand it.

Any change you want to make a PR with this functionality?

**Comment by XtroTheArctic** [comment]
I (probably many other Unity developers too) don't like to keep individual files (especially the ones don't belong to me directly) in the Unity project root (Assets folder). When I import a 3rd party asset, I move its main folder to 3rdParty folder to keep the Unity root clean.

I did the same thing for NuGetForUnity's main folder. I moved it to 3rdParty folder. But the config files are created in the root automatically by NuGetForUnity dll. I'd like to be able to move them to another folder. Maybe not to 3rdParty folder because it's not a folder for storing config files but maybe I can move the config files to Assets/NuGet folder. To be able to do that, I would like to set the config path in NuGet settings in Unity's preferences window.

**Comment by wombatzus** [comment]
Another vote for making the path to the config files configurable and here is my reason: other tools don't like this location. For instance Rider doesn't discover the config files here under Assets but works fine if they are one level up, at the same level as the solution.

**Comment by BlurringShadow** [comment]
Is there any progress for this enhancement?

**Comment by jwittner** [comment]
Not that I've seen. We're open to any PRs though if you'd like to make the changes. =)

**Comment by JoC0de** [comment]
The main problem in making it configurable is: where to store the configuration with the information where to find the config file (its a 🐔 🥚  problem) 😄

**Comment by JoC0de** [comment]
Duplikate of #527
At least the packages.config file can now be moved #551

**Comment by mwgray** [comment]
[Odin Inspector](https://odininspector.com) gets around this problem by using the guids in meta files.  Basically they have a hard coded guid in their codebase to use as a marker to find a directory.  Source isn't available, but I believe they use [this class](https://odininspector.com/documentation/sirenix.odininspector.editor.sirenixpathlookupscriptableobject) to create a scriptable object `Odin Inspector/Assets/Editor/OdinPathLookup.asset`, which has a guid of `08379ccefc05200459f90a1c0711a340`.  

Then the path can be looked up by `AssetDatabase.GUIDToAssetPath("08379ccefc05200459f90a1c0711a340")`, which can then assume that that file is in the expected location, and thus find the root folder of the distribution, no matter where it's placed within the 'Assets' folder.

For this issue, `CreateDefaultFile` could also write a default `NuGet.config.meta` alongside the default `NuGet.config` file, with a hard coded guid.   Then `ConfigurationManager` could use the guid to find the file, which could then be moved anywhere within the project.

**Comment by igor84** [comment]
But we also have a Command Line Interface (CLI) version that needs to run outside of unity in automatic build systems and there is no cheap way to replicate GUIDToAssetPath there as far as I can see.

**Comment by mwgray** [comment]
Ah, if that's the case could the users that wish to move the config file simply pass in a CLI argument, ie `--config_path`, which defaults to the current behavior?

**Comment by JoC0de** [comment]
What we can do is provide two "hardcoded" locations where the `NuGet.config` file can be placed.
- `Assets/NuGet.config` (the currently used location)
- `ProjectSettings/Packages/com.github-glitchenzo.nugetforunity/NuGet.config` (new location would disable the auto-reload feature)

**Comment by JoC0de** [comment]
Implemented by #619
