### ISSUE TITLE
Mac Support - Installing Updates and Restoring Packages

### ISSUE THREAD

**Issue by awolowiecki720** [GlitchEnzo/NuGetForUnity#200]
## Description
Restoring packages on startup causes Unity to periodically crash. If packages do restore successfully, they do not show up under the 'Installed' list, which is an issue for updating or uninstalling those packages. 

- **NuGet Package:** Newtonsoft.Json, but this behavior occurs for other package restores from a private feed.
- **NuGetForUnity Version:** 0.0.18
- **Unity Version:** 2017.1.1f1
- **Operating System:** macOS High Sierra 10.13

**Comment by JoC0de** [comment]
Should be fixed in newer versions of NuGetForUnity
