### ISSUE TITLE
Packages that fail to install dependencies should fail to install

### ISSUE THREAD

**Issue by derekfreed** [GlitchEnzo/NuGetForUnity#207]
If I install a package with a dependency and the dependency fails to install, the package should not be put into my project. It should just get an error that it failed because it couldn't install dependencies.

**Comment by ForrestTrepte** [comment]
@derekfreed, it looks like this was fixed by #208? Can we close this issue?

**Comment by derekfreed** [comment]
Yup, meant to do that
