### ISSUE TITLE
Installs Wrong Package Versions

### ISSUE THREAD

**Issue by biscuitWizard** [GlitchEnzo/NuGetForUnity#212]
## Description
Trying to install any nuget package results in it pulling tens of nuget packages for netstandard1.0.

This is on a FRESH 2018.2.17f1 install and project. Just completely bombs and is unusable.

- **NuGet Package:** Newtonsoft.Json
- **NuGetForUnity Version:** 1.0
- **Unity Version:** 2018.2.17f1
- **Operating System:** Windows 10

**Comment by biscuitWizard** [comment]
Player Settings: Net 4.x install, IL2CPP, /w NetStandard2.0 target.

**Comment by biscuitWizard** [comment]
On further investigation it just seems to be pulling every core/system package possible.

**Comment by madawe** [comment]
I was having a problem with the NuGet Package AWSSDK.Core always installing the 3.0.0.0-preview no matter which version I selected. I worked around it by putting the nuget package in the cache folder but now it is doing the above. It's installing every core/system package. It's been going for 20 minutes now and has installed... a lot of packages. I am on version NuGetForUnity 1.0.1

**Comment by jwittner** [comment]
Should be resolved by #218
