### ISSUE TITLE
Can this work for the .Net Standard version of NewtonSoft Json?

### ISSUE THREAD

**Issue by Noemata** [GlitchEnzo/NuGetForUnity#217]
I tried bringing in a very recent version of NewtonSoft Json but ran into lib conflicts after it was loaded.  Can someone provide a sample or instructions that target a Unity UWP project that's configured to use .Net Standard.  If this sort of thing isn't possible, what are the limitations and are there any possible workarounds?

**Comment by jwittner** [comment]
I am currently adding fixes/support for target framework dependencies and am verifying functionality on .Net Standard. I expect that PR up this week. I suggest you try v0.0.17, but depending on the package you may still have problems.

**Comment by Noemata** [comment]
As one further note, when it did bring in the correct .Net Standard lib, the import was super quick.  In all other instances, the process was loading everything under the sun.

**Comment by Noemata** [comment]
Thank you for your suggestion, switching to v0.0.17 resolved the issue.  Looking forward to your update.  Very, very, very nice work!
