### ISSUE TITLE
Can't reference package source from C# scripts

### ISSUE THREAD

**Issue by larryPlayabl** [GlitchEnzo/NuGetForUnity#220]
## Description
After installing a package, I still can't reference it from a C# script. Trying to include a namespace from the package with a "using" directive fails to compile.

- **NuGet Package:** Json.net 12.0.1
- **NuGetForUnity Version:** 1.0.2
- **Unity Version:** 2018.3.0f2
- **Operating System:** osx 10.13.4

**Comment by dyllandry** [comment]
Same here, I honestly don't know how to include the script.

**Comment by dyllandry** [comment]
@larryPlayabl Yooo! I think I got it! Took a lot of Googling.

I heard from a little bird across the sea that you can rename a .nupkg file as a .zip and simply unzip it to retrieve the contents. In my case, I was downloading MailKit using NuGet for Unity.

I had a MailKit.2.1.3.nupkg file that NuGet for Unity downloaded. I renamed it from .nupkg to .zip, unzipped it, then found something I had seen mentioned earlier.

According to [Arshia001](https://stackoverflow.com/a/53458099/7933478),  netstandard20 dlls can be placed within Unity projects. In that unzipped MailKit NuGet package I found dir called `_rels/lib/netstandard2.0`. I copied the dll i found there into my Unity project, then Unity did some building mumbo-jumbo, and the using directive stopped erring!

I haven't *used* my NuGet package yet, so I don't know if it works, but at least it got rid of the using directive error.

**Comment by iAmNaz** [comment]
The packages when installed are empty and for some reason the .nupkg were not unzipped. I did it manually and replaced the empty package folder in the Packages folder. That made it work.
