### ISSUE TITLE
Add netstandard1.1 support for netframework target

### ISSUE THREAD

**Issue by anmelegov** [GlitchEnzo/NuGetForUnity#222]
As you know from doc https://docs.microsoft.com/en-us/dotnet/standard/net-standard netframework4.6 implements netstandard 1.3 so libraries targeted to netstandard 1.3 and below are compatible. That is the reason why I can see them from search API and can download the package. You shouldn't remove the library after unpacking because it's suitable

Unable to install library targeted to netstandard1.1 in unity project that is set to target net46

- **NuGet Package:** Polly
- **NuGetForUnity Version:** latest
- **Unity Version:** 2017.2
- **Operating System:** windows

**Comment by jwittner** [comment]
I believe this was resolved by #303
