### ISSUE TITLE
Getting "EndLayoutGroup: BeginLayoutGroup must be called first" when opening the Manage NuGet Packages window

### ISSUE THREAD

**Issue by rmiller-glreaitylabs** [GlitchEnzo/NuGetForUnity#243]
## Description

When the "Manage NuGet Packages" window is opened in a clean project, this exception gets thrown:
```
EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEditor.EditorGUILayout:EndVertical()
NugetForUnity.NugetWindow:DrawOnlineHeader()
NugetForUnity.NugetWindow:DrawOnline()
NugetForUnity.NugetWindow:OnGUI()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

This happens even when a new project is freshly created and nothing has been done except installing the unitypackage

- **NuGet Package:** none
- **NuGetForUnity Version:** 1.0.4
- **Unity Version:** 2018.3.4f
- **Operating System:** Ubuntu

**Comment by missechogao** [comment]
Did you solve the problem?I get the same issue

**Comment by JoC0de** [comment]
Fixed in newer version. Not sure when it is fixed but it is fixed 😄
