### ISSUE TITLE
Support Long Paths

### ISSUE THREAD

**Issue by andreiborodin** [GlitchEnzo/NuGetForUnity#246]
## Description
The NuGet install/uninstall process fails with NuGetForUnity when working with paths longer than 260 characters. This is due to Directory.Delete not being able to handle it. There are some possible ways of fixing this on Windows, one being calling DeleteFIleW API.

**Comment by andreiborodin** [comment]
This is also due to ZipEntry not being able to extract a NuGet package with long paths.

**Comment by JoC0de** [comment]
Not sure how we can fix this. It is a C# + Windows issue. I think in windows 11 it should be fixed but not sure.
