### ISSUE TITLE
Problem with DotNetty

### ISSUE THREAD

**Issue by SetoKaiba** [GlitchEnzo/NuGetForUnity#247]
## Description
1. There should be a option to treat api compatibility level .net 4.x as .net standard 2.0. Because the .net 4.x is modified by Unity. It can be compatible with .net standard assemblies.
2. The dependencies of DotNetty is not installed. When I choose the 5 packages in red rectangles. The dependencies below should be installed.

![image](https://user-images.githubusercontent.com/159540/56657566-f61c7d80-66ca-11e9-867f-b1c31c6f9fa2.png)

- **NuGet Package:** DotNetty
- **NuGetForUnity Version:** 1.0.4
- **Unity Version:** 2019.1.0f2
- **Operating System:** Windows

**Comment by SetoKaiba** [comment]
I just want to use the manager to simplify my manual installation nuget packages every time.

**Comment by jwittner** [comment]
I believe this was fixed by #303

**Comment by SetoKaiba** [comment]
I just tested that it's not working. Many dependencies is included. As the .net 4.x api compatibility level is compatible with .net standard as well. Many dependencies should not be included. Failed to install.

**Comment by jwittner** [comment]
Note: May be fixed by #357

**Comment by KonH** [comment]
Not sure about full repro steps (tried to install DotNetty.Buffers), but looks like it will be resolved by #357 (tested on Unity 2019.4.0f1, .NET Standard 2.0 subset, MacOS)

**Comment by SetoKaiba** [comment]
Thank you. Let me have a try.
