### ISSUE TITLE
Usability: Save button in preferences is easy to forget

### ISSUE THREAD

**Issue by ForrestTrepte** [GlitchEnzo/NuGetForUnity#256]
## Description

I often forget to hit the Save button when changing settings in the NuGetForUnity preferences pane. I have observed other users with this same problem. "Something keeps putting my settings back to their previous values! Oh, whoops, forgot to hit the Save button."

- **NuGetForUnity Version:** 1.1.0

## Proposal

Remove the Save button. Automatically apply all changes as they are made.

## Alternative Proposal

Prompt to save changes when the Preferences window is closed or when switching away from the tab.

**Comment by ForrestTrepte** [comment]
Thanks, @Efmi!

**Comment by Efmi** [comment]
Happy to help, @ForrestTrepte !
