### ISSUE TITLE
Namespace conflicts with Unity package manager package

### ISSUE THREAD

**Issue by ulyssesp** [GlitchEnzo/NuGetForUnity#259]
## Description
The Optional package conflicts with Unity's HDRP source. Unity's HDRP source uses Optional as an attribute, but because it's a global namespace after package installation the compiler complains. The quickest fix would be to allow renaming the namespace of a package, but I couldn't figure out how to do that.

- **NuGet Package:** Optional 4.0.0
- **NuGetForUnity Version:** latest (installed yesterday)
- **Unity Version:** 2019.1.0f2
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
This doesn't seem like an issue the N4U can fix.
