### ISSUE TITLE
'Show All Versions' Does Not Work In 'Online' Tab

### ISSUE THREAD

**Issue by tbg10101** [GlitchEnzo/NuGetForUnity#260]
## Description
In the 'Online' tab, the 'Show All Versions' checkbox does not appear to change anything. (the checkbox does work on the 'Updates' tab)

- **NuGet Package:** N/A
- **NuGetForUnity Version:** 1.2
- **Unity Version:** 2019.1.7f1
- **Operating System:** Mac OS 10.14.5

**Comment by jwittner** [comment]
This appears to be a limitation of the nuget.org API. It works as expected for other endpoints, and I've verified that finding packages via the nuget cli results in the same package set.
