### ISSUE TITLE
Sqlite Net with IL2CPP

### ISSUE THREAD

**Issue by bgulanowski** [GlitchEnzo/NuGetForUnity#262]
## Description

Perhaps this isn't strictly a problem with NuGetForUnity. But maybe there could be some documentation or information.

Sqlite.net doesn't seem to work the the IL2CPP backend. It works fine in the editor, but I get errors in the console in the built player:

```
The type initializer for 'SQLite.SQLiteConnection' threw an exception.
```
and
```
You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
```

I'm still trying to learn more information on the requirements for packages to be compatible with IL2CPP.

- **NuGet Package:** sqlite-net-pcl.1.4.118
- **NuGetForUnity Version:** 0.0.13
- **Unity Version:** 2018.4.3f1
- **Operating System:** macOS Mojave 10.14.5

**Comment by jwittner** [comment]
Perhaps this issue would be better placed here: https://github.com/praeclarum/sqlite-net

@praeclarum - any plans for Unity IL2CPP support?
