### ISSUE TITLE
Lower case NuGet packages in folder used as NuGet Source are ignored

### ISSUE THREAD

**Issue by andreiborodin** [GlitchEnzo/NuGetForUnity#265]
## Description
Use a folder as a NuGet source, and then rename any NuGet package to lower case to repro this. Renaming the file to just start with upper case fixes the issue.

- **NuGet Package:** microsoft.mixedreality.toolkit.foundation
- **NuGetForUnity Version:** 1.2.1
- **Unity Version:** 2018.3
- **Operating System:** Win 10 RS5

**Comment by Efmi** [comment]
I wasn't able to reproduce this with NuGetForUnity version 2.0.0. I tried with both Unity 2018.4 and 2019.2, so I guess that this has been fixed. Are you able to reproduce this with the newest version?

**Comment by andreiborodin** [comment]
I haven't tried with the latest, this may have been fixed. @jwittner, thoughts?

**Comment by JoC0de** [comment]
So if it is fixed I will close the issue.
Actually there could be an issues with wrong casing on case-sensitive file systems like linux.
