### ISSUE TITLE
Analyzers

### ISSUE THREAD

**Issue by dv-ak** [GlitchEnzo/NuGetForUnity#266]
## Description
Require the ability to have analyzers placed under 'References/Analyzers' in a project, rather than 'References'.
Refer to [this](https://forum.unity.com/threads/unity-strips-out-nuget-properties-on-csproj-files.473016/) forum for other developers solutions which may help in implementing.

- **NuGet Package:** package id="StyleCop.Analyzers" version="1.1.118"
- **NuGetForUnity Version:** 1.2.0
- **Unity Version:** 2019.1.7f1
- **Operating System:** Windows

**Comment by JoC0de** [comment]
fixed by #393
