### ISSUE TITLE
Installed nuget does not include dlls

### ISSUE THREAD

**Issue by mattbenic** [GlitchEnzo/NuGetForUnity#267]
## Description
When installing this package, no dlls are added to the project, just the folder structure and .nupkg

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
sharpadbclient (.Net client for adb, Android Debug Bridge) 2.2.29
- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
0.0.13
- **Unity Version:** [What version of Unity are you using?]
2018.4.1.1f1
- **Operating System:** [What OS are you on?]
Windows 10

**Comment by mads256c** [comment]
I have the same problem with the System.Threading.Tasks.Dataflow package. No actual dlls are downloaded into the packages folder. I have to manually download the package and copy the dlls for it to work

**Comment by jwittner** [comment]
I made an issue for what I think would be the shortest enhancement to fix this issue for your packages - #276.

**Comment by jwittner** [comment]
@mattbenic - I would expect your package to include it's libraries as long as you set Unity to target .NET 4.x, it does in my test with N4U 1.2.1. If you're targeting .NET standard then see #222.

**Comment by jwittner** [comment]
Closing as fixed for 4.x and duplicate for .Net Standard or Portable Class Libraries.

**Comment by mads256c** [comment]
@jwittner The packages also uses netstandard1.0, netstandard1.1 and netstandard2.0. Shouldn't these also get support?

**Comment by jwittner** [comment]
@mads256c - I think we'd fold the netstandard 1.x into #222 and you're right that we should create an issue for netstandard2.0. It's a little different because unity settings have to change to support that where as the older netstandards should work under the .Net 4.x support that Unity has.
