### ISSUE TITLE
/unityplugin folder hierarchy is lost; only files in root are copied

### ISSUE THREAD

**Issue by dfields-msft** [GlitchEnzo/NuGetForUnity#269]
## /unityplugin folder hierarchy is lost; only files in root are copied
Native plugins typically need to deliver different flavors for different architectures, which can't co-exist in the same folder since the files have the same names. Instead, they're typically placed in subfolders by architecture/platform, but the N4U handling of /unityplugin targets only copies files in the root folder, and discards subfolders. Instead, the whole unityplugin folder should be copied recursively to Assets/Plugins.

**Comment by dfields-msft** [comment]
@jwittner FYI

**Comment by jwittner** [comment]
Hey @dfields-msft, doing some research on the need for these folders. It looks like the plugins folder [is no longer necessary](https://docs.unity3d.com/Manual/UpgradeGuide5-Plugins.html) and hasn't been since Unity 5.x.

> "Plugins are no longer required to be placed in Assets\Plugins\<Platform\> folders"

Doing some tests using OpenCV I'm seeing this to be true in practice.
