### ISSUE TITLE
Local package source search doesn't find packages in subfolders

### ISSUE THREAD

**Issue by dfields-msft** [GlitchEnzo/NuGetForUnity#270]
## Local package source search doesn't find packages in subfolders
After setting up a local package source with `nuget.exe add MyPackage -source c:\localpackages` and adding `c:\localpackages` to `PackageSources` in my `nuget.config` file, NuGet for Unity was not able to find my package. After inspecting the source, this is because N4U only looks in the root of the specified folder, but `nuget.exe add` creates a folder hierarchy based on package names and versions.

- **NuGet Package:** N/A
- **NuGetForUnity Version:** 1.21
- **Unity Version:** 2018.4
- **Operating System:** Windows

**Comment by JoC0de** [comment]
fixed in #489
