### ISSUE TITLE
Using NuGet For Unity With CI

### ISSUE THREAD

**Issue by matthew17754** [GlitchEnzo/NuGetForUnity#274]
How would one go about configuring **Continuous Integration** (such as Unity Cloud Build or Travis) for a project that utilizes dependencies from NuGet for Unity? Is there a way to pass a `Restore Packages` command line argument of some sort for use when deploying over CI?

**Comment by jwittner** [comment]
Hey! While I don't believe there is an official N4U way to do this, I can speak to how our team leverages it in our CI. 

* We use [UnitySetup ](https://www.powershellgallery.com/packages/unitysetup/5.1.126)to automate Unity.
* We execute `Start-UnityEditor -Project <pathToProject> -LogFile <pathToRestoreLogFile> -AcceptAPIUpdate -BatchMode -Quit -Wait`
  * This simply boots Unity for the project, which causes assets to be built and N4U to restore packages, then exits Unity.
* We then execute `Start-UnityEditor -Project <pathToProject> -LogFile <pathToBuildLogFile> -AcceptAPIUpdate -BatchMode -Quit -Wait -ExecuteMethod <Class.MethodName> -BuildTarget <targetPlatform>`
  * This does the work of creating the build from within Unity using custom logic in `Class.MethodName`.

Hope that helps!

**Comment by GlitchEnzo** [comment]
There's the old batch file that I wrote for a similar purpose back in the day.  I'm not sure if it still works now:
[https://github.com/GlitchEnzo/NuGetForUnity/blob/master/RestoreNugetPackages.bat](https://github.com/GlitchEnzo/NuGetForUnity/blob/master/RestoreNugetPackages.bat)

**Comment by matthew17754** [comment]
Thanks for the helpful responses. 
@GlitchEnzo I can confirm that [RestoreNugetPackages.bat](https://github.com/GlitchEnzo/NuGetForUnity/blob/master/RestoreNugetPackages.bat) does in fact still work. Line 11 seems to solve my problem. I would definitely recommend adding something in the readme about that.
@jwittner What does `<pathToRestoreLogFile>` represent in this context?

Thanks again for the support.

**Comment by jwittner** [comment]
@matthew17754 - the path to the file you'd like Unity to log to. =)

**Comment by jwittner** [comment]
And a PR to the README for the restore function would be much appreciated @matthew17754. =)
