### ISSUE TITLE
Support for Portable Class Libraries

### ISSUE THREAD

**Issue by jwittner** [GlitchEnzo/NuGetForUnity#276]
## Description

Right now N4U doesn't include any of the [portable-* target frameworks](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks#portable-class-libraries), but it should support any that include the target frameworks that it already supports. This causes many compatible nuget packages to have their lib files stripped.

**Comment by JoC0de** [comment]
I didn't see any newer nuget packages using portable target frameworks. Even Microsoft recommends not to use them, so I don't see a reason to support it.
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/53140583/02d37e91-6798-40d7-8a8f-b8a722347c71)
