### ISSUE TITLE
Asset Store Version is very old now.

### ISSUE THREAD

**Issue by jwittner** [GlitchEnzo/NuGetForUnity#278]
## Description
The version of NuGetForUnity on the [Unity Asset Store](https://assetstore.unity.com/packages/tools/utilities/nuget-for-unity-104640) is woefully out of date, and doesn't support the auto update feature (key to an easy path to latest).

@glitchenzo - can we get the latest from our [releases page](https://github.com/GlitchEnzo/NuGetForUnity/releases) up on the Asset Store?

**Comment by jwittner** [comment]
@GlitchEnzo  - any chance you can respond soon to this?

**Comment by DanJBower** [comment]
I agree. I think this should be updated on the asset store as it is a great tool!

**Comment by jcs090218** [comment]
Wonder any progress on this? This package is no longer on Unity Assets store! :(

**Comment by GlitchEnzo** [comment]
Sorry, I haven't touched this project (or even Unity) for several years now.

There was some discussion to have Microsoft completely take ownership of this project and handle the shared package. @jwittner - perhaps now is a good time to think/talk about this again since the original package is now delisted.

**Comment by jwittner** [comment]
Definitely interested in picking that conversation back up. If you're ok discussing the path forward in the clear we can do that in #255. =)

**Comment by jwittner** [comment]
Long term I think we'd like to move distribution to the Unity Package Manager via a public scoped feed and bypass the Unity Asset Store. Curious @jcs090218 if that would be viable or satisfy the reasons you'd like to get this back on the Asset Store.

**Comment by jcs090218** [comment]
@jwittner I think is fine, I think it would be great to be on both yet is fine for me! :)

**Comment by JoC0de** [comment]
Now we are on openupm + support installation using Git or manually using .unitypackage but we no longer support installing using Asset Store, it is deprecated on the Asset Store
