### ISSUE TITLE
Can't get updtates for AWSSDK.Core

### ISSUE THREAD

**Issue by danilonobren** [GlitchEnzo/NuGetForUnity#286]
## Description
When trying to use NuGetForUnity to install the nuget package into my project, it installs the version 3.0.0.0-preview from 2016. When trying to update, console (verbose) shows that newest version wasn't founded, and then installs the old one.

- **NuGet Package:** AWSSDK.Core
- **NuGetForUnity Version:** 1.2.3
- **Unity Version:** 2019.1.0f2
- **Operating System:** Windows 10

![image](https://user-images.githubusercontent.com/14813304/65839691-1a1d6400-e2e6-11e9-91e1-b19acae1fa57.png)

**Comment by yuhe0925** [comment]
same here, only 3.0.0 preview can be installed and not able to update
