### ISSUE TITLE
Remove Unity logo from Asset Store images

### ISSUE THREAD

**Issue by GlitchEnzo** [GlitchEnzo/NuGetForUnity#288]
## Description
Unity has changed the rules for the Asset Store and they no longer allow the Unity logo to be used in images for the package. NuGet for Unity is now deprecated on the Asset Store until this is resolved.

> We do not allow the Unity logo in your package and key images. The Unity logo is only allowed on packages and key images created by Unity teams and submitted via the Unity Technologies publishing account. If you have been given an award badge from the Unity Awards, this badge is the only exception to this rule. Otherwise, please remove the Unity logo from your package and key images.

**Comment by JoC0de** [comment]
All screenshots have been updatet to not contain the Unity Logo eventually we can add NuGetForUnity to the Asset Store but I don't see the need.
