### ISSUE TITLE
Settings in Manage NuGet Packages are not persistent

### ISSUE THREAD

**Issue by thalbern** [GlitchEnzo/NuGetForUnity#292]
## Description
Ticking boxes like "Show all Versions" or "Show Prerelease" are not stored. Whenever the Manage NuGet Packages window gets closed and reopened the previous settings are cleared.

- **NuGet Package:** Mrtk v2.1.0
- **NuGetForUnity Version:** 1.2.4
- **Unity Version:** 2018.4.0f1
- **Operating System:** Windows 10

**Comment by JoC0de** [comment]
duplicate
