### ISSUE TITLE
No Contribute .md - missing instructions how to build and contribute

### ISSUE THREAD

**Issue by thalbern** [GlitchEnzo/NuGetForUnity#294]
## Description
This is a docs issue.
I was trying to fix one of the issues in this repo but couldn't figure out how to build the source code. Can you provide a Contribute.md that describes the steps how to contribute to this repo?

- **NuGet Package:** Mrtk v2.1.0
- **NuGetForUnity Version:** 1.2.4
- **Unity Version:** 2018.4.0f1
- **Operating System:** Windows 10

**Comment by thalbern** [comment]
I've now created an empty unity project and dragged the nuget for unity source folder into the assets - this seems to work but is probably not the right way to do it

**Comment by igor84** [comment]
I can tell you that under CreateDLL folder there is a sln and csproj files you can open in Visual Studio or other compatible software and build the new DLL from it. There is also a build.ps1 PowerShell script in the root of the project that will build the DLL and package it in a unitypackage file, but you need to install the modules that script depends on and appropriate Unity version for packaging.

**Comment by JoC0de** [comment]
I added https://github.com/GlitchEnzo/NuGetForUnity/blob/master/CONTRIBUTING.md that explains how to build / how to contribute. If theor. are open questions we are open to feedback.
