### ISSUE TITLE
Running package restore command doesn't work on Mac

### ISSUE THREAD

**Issue by dolanmiu** [GlitchEnzo/NuGetForUnity#300]
On the README, it says:

Mac: `$ /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -projectPath <yourProjectDirHere> -executeMethod NugetForUnity.NugetHelper.Restore`

So my command is:

```sh
/Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -projectPath /Users/dmiu/villager-game/game -executeMethod NugetForUnity.NugetHelper.Restore
```

But I get a:

```sh
-bash: /Applications/Unity/Unity.app/Contents/MacOS/Unity: No such file or directory
```

**Comment by jwittner** [comment]
`/Applications/Unity/Unity.app/Contents/MacOS/Unity` is the documentation's assumed install path for Unity. Your error seems to indicate that's not where you have your unity installed. Can you confirm where you have Unity installed on your Mac?

FYI, testing Mac can be difficult for us as we don't have ready access to one - any help improving the Mac support is much appreciated!

**Comment by JoC0de** [comment]
closing as no response + the issue is not related to NuGetForUnity
