### ISSUE TITLE
Can't push to Azure DevOps Artifacts

### ISSUE THREAD

**Issue by shaddadjr** [GlitchEnzo/NuGetForUnity#301]
## Description

I am attempting to push a self-made test nuget package to our DevOps Artifacts, but I get the following error:

Pushing XYZ_pkg 0.0.1 to 'https://xyz.pkgs.visualstudio.com/_packaging/XYZ_Nuget_Packages/nuget/v2/'...

Please provide credentials for: https://xyz.pkgs.visualstudio.com/_packaging/XYZ_Nuget_Packages/nuget/v2/

UserName: 
UnityEngine.Debug:Log(Object)
NugetForUnity.NugetHelper:RunNugetProcess(String, Boolean)
NugetForUnity.NugetHelper:Push(NuspecFile, String, String)
NugetForUnity.NuspecEditor:OnGUI()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I tried adding credentials to the config file (not sure if I did it right) but it didn't seem to make a difference. I am able to pull packages from my artifacts just fine.

- **NuGet Package:** Self-made test
- **NuGetForUnity Version:** 1.2.4
- **Unity Version:** 2019.1.0f2
- **Operating System:** Windows 10 - 1903

**Comment by zkkzkk32312** [comment]
Im having trouble pulling from Azure with credentials added in the config file. Has this issue been resolved for you?

**Comment by JoC0de** [comment]
Closing as it is really old issue. If someone has a similar issue pleas crate a new issue.
