### ISSUE TITLE
unity 2019.2.11 ,.net4.x，nuget package 'Orleans' is download but not  dll  ，windows,

### ISSUE THREAD

**Issue by 731315163** [GlitchEnzo/NuGetForUnity#310]
## Description
[Describe the issue you have.]

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
- **Unity Version:** [What version of Unity are you using?]
- **Operating System:** [What OS are you on?]

**Comment by jwittner** [comment]
Can you update with what version of N4U you were using? If it was a release, can you try again with the latest source? I believe that #303 may have fixed this already.

**Comment by 731315163** [comment]
nuget newtonsoft.json is ok. nugetforunity is 1.2.4. nuget package orleans cannot be used.

**Comment by jwittner** [comment]
Cool, I suspect this is fixed with latest source code. =)

**Comment by 731315163** [comment]
Yes, it is working.
