### ISSUE TITLE
please add the proxy config.

### ISSUE THREAD

**Issue by Zchary** [GlitchEnzo/NuGetForUnity#312]
## Description
> Unable to retrieve package list from http://www.nuget.org/api/
it's difficult to download packages from a specific website like NuGet without using proxy in some countries like China. Appreciate it.

- **NuGet Package:** websocketsharp
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2018.2.16

**Comment by Zchary** [comment]
Personal mistake, sorry if it bothers you.

**Comment by orangeagain** [comment]
我也有这个问题,  请问你是怎么解决的?
