### ISSUE TITLE
Packages never download in Unity 2017.4 (works fine in 2018.4).

### ISSUE THREAD

**Issue by jwittner** [GlitchEnzo/NuGetForUnity#315]
## Description
If I have 'Install from Cache' disabled packages timeout when downloading. This works find in Unity 2018.4, but fails in Unity 2017.4.

- **NuGet Package:** NewtonSoft.Json.6.0.8
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2017.4.34f1
- **Operating System:** Windows 10

**Comment by JoC0de** [comment]
We only support 2018.4+
