### ISSUE TITLE
Grcp.core runtimes are missing

### ISSUE THREAD

**Issue by zielezin** [GlitchEnzo/NuGetForUnity#318]
## Description

When installing Grpc.core 2.25.0 the main dll in lib\net45 folder is downloaded but an additional dll in runtimes/win/native/grpc_csharp_ext.x64.dll is not.

- **NuGet Package:** Grpc.Core 2.25.0
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2019.2.15f1
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
Right now the runtimes folder is explicitly deleted by N4U unfortunately. There has been other recent asks to support the architecture specific runtimes in the project, and we'd definitely be open to a solution. 

The key bit is that the runtime dlls will either need to have their platforms configured on install or the folder will need to be reshaped to take advantage of Unity's legacy Plugin folder naming scheme.

**Comment by zielezin** [comment]
Thank you for information.

I tried to manually copy the runtimes folder as is to packages but it still does not work.
I get Exception TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: grpc_csharp_ext

I need to manually change name from grpc_csharp_ext.x64.dll to grpc_csharp_ext.dll and only then it starts to work.

Is this caused by a problem you are describing?

**Comment by jwittner** [comment]
Unrelated to the missing support for runtimes, but an interesting issue for any implementation of that feature.

Interesting, from [all the docs](https://github.com/NuGet/docs.microsoft.com-nuget/issues/600) I've seen, putting the architecture into the dll name is not a standard convention - the folder hierarchy is normally used to indicate the target os-arch for the native dlls.

Looks like this project is relying on the targets files (\grpc.core.2.25.0.nupkg\build\net45\) to get MSBuild to properly include these runtime dependencies.

**Comment by bricelam** [comment]
[Microsoft.Extensions.DependencyModel](https://www.nuget.org/packages/Microsoft.Extensions.DependencyModel) can help with this.

```csharp
var targetPlatform = "win7-x86"; // Or win7-x64, osx.10.12-x64, ubuntu.16.04-x64, etc.

var rids = DependencyContext.Default.RuntimeGraph.FirstOrDefault(g => g.Runtime == targetPlatform)?.Fallbacks.ToList()
    ?? new List<string>();
rids.Insert(0, targetPlatform);

// Find the nearest match
foreach (var rid in rids)
{
    if (Directory.Exists("runtimes\" + rid + "\native"))
    {
        // TODO: Add these files as native Unity plugins for Windows x86

        break;
    }
}
```

**Comment by robin-moss** [comment]
even with support for runtime folders gRPC will not work (out of the box). The native importing code in gRPC has some handling for `Unity` which means that the native filenames it looks for do not match those in NuGet.

This is something that we are also looking into, but won't be part of the runtime folder support initially
