### ISSUE TITLE
nuget versions not match

### ISSUE THREAD

**Issue by 731315163** [GlitchEnzo/NuGetForUnity#322]
![2PW9WI4Z{5SRAGCI(B5@F0G](https://user-images.githubusercontent.com/15324820/71981475-738a1d00-325d-11ea-8bbb-04f03d945ec2.png)
unity debug console:
Assembly 'Assets/Packages/System.IO.Pipelines.4.6.0/lib/netstandard2.0/System.IO.Pipelines.dll' will not be loaded due to errors:
System.IO.Pipelines references strong named System.Buffers, versions has to match. Assembly references: 4.0.2.0 Found in project: 4.0.3.0.

Unity nuget version does not match, but nuget for unit downloaded. What should I do?

**Comment by 731315163** [comment]
I downloaded two nuget, which refer to different versions of system.buffers, causing problems. I can only get the source code to recompile the package, and let him use the same system.buffer nuget

**Comment by 731315163** [comment]
![BXWUN5`KN%{CH _W_}4JAZY](https://user-images.githubusercontent.com/15324820/72031190-97357d80-32c6-11ea-8ab8-d7586cd2d1b5.png)
Finally, the installation of orleans.client nuget failed

**Comment by 731315163** [comment]
Finally, the installation of orleans.client nuget failed
![BXWUN54JAZY](https://user-images.githubusercontent.com/15324820/72031412-4c683580-32c7-11ea-982a-bae13defb253.png)

**Comment by jwittner** [comment]
Note: This may be resolved by #357 .

**Comment by KonH** [comment]
Not sure about full repro steps (tried to install Microsoft.Orleans.Client), but looks like it will be resolved by #357 (tested on Unity 2019.4.0f1, .NET Standard 2.0 subset, MacOS)
