### ISSUE TITLE
NugetForUnity not finding the most recent package version

### ISSUE THREAD

**Issue by kaysabelle** [GlitchEnzo/NuGetForUnity#323]
I was trying to install the latest version (0.9.0-preview.1) of Microsoft.Azure.Management.MixedReality. I tried manually adding this to the packages.config so that NugetForUnity would pick it up the next time the project was opened.

However, NugetForUnity won't restore this package - I get the error `Could not find Microsoft.Azure.Management.MixedReality 0.9.0-preview.1 or greater.`

When I search for this package in the NugetForUnity Nuget package manager UI, I can see that the version picked up by NugetForUnity is 0.9.0-preview. However, looking at the package in nuget.org, I can confirm that the actual latest version is 0.9.0.preview-1.

Specifying package version as 0.9.0-preview results in that version of the package being restored as expected.

Is there a bug with how NugetForUnity is parsing package versions that is causing it to not pick up the latest version of this package (and possibly other packages with a similar versioning system)?

- **NuGet Package:** https://www.nuget.org/packages/Microsoft.Azure.Management.MixedReality, version 0.9.0-preview.1
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2019.2.14.f1
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
Ah, looks like you're hitting [the need for this](https://github.com/GlitchEnzo/NuGetForUnity/issues/273).
