### ISSUE TITLE
Space in folder name

### ISSUE THREAD

**Issue by peted70** [GlitchEnzo/NuGetForUnity#324]
## Description
A %20 in a local folder name causes NugetForUnity to fail to load packages correctly. There is a warning about being unable to locate folder "" but the end result is packages being copied into the Assets/Packages folder with all of the contained libraries for each platform.

- **NuGet Package: any package
- **NuGetForUnity Version: 2.0.0
- **Unity Version:** 2019.2.17f
- **Operating System: Windows 10

**Comment by JoC0de** [comment]
I am closing it as it should be fixed in current version. If someone else gets a similar issue pleas create a new issue.
