### ISSUE TITLE
NullReferenceException in NugetHelper.LoadNugetConfigFile ()

### ISSUE THREAD

**Issue by tobi1449** [GlitchEnzo/NuGetForUnity#326]
## Description

I'm getting this NullReferenceException whenever I try to do anything with NuGetForUnity

System.NullReferenceException: Object reference not set to an instance of an object
  at NugetForUnity.NugetHelper.LoadNugetConfigFile () [0x0011c] in <d5348c0adcb941678978d77f32d61a2a>:0 
  at NugetForUnity.NugetHelper..cctor () [0x001e6] in <d5348c0adcb941678978d77f32d61a2a>:0 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])

Looks like the error occurs when MSBuildForUnity has been installed previously, which adds its own Nuget.config file that just contains the nuget repository for MSBuildForWindows and nothing else.

- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2019.3.2f1
- **Operating System:** Win10

**Comment by FelixWeichselgartner** [comment]
For me its working with Unity Version 2019 but I have the same issue in Unity 2018 LTS

**Comment by sabeur-salah-elmastouri** [comment]
For me i downloaded the CS files and edit this lines on NugetHelper.cs: 

```
public static readonly string NugetConfigFilePath = Path.Combine(Application.dataPath, "./NuGet.config");
private static readonly string PackagesConfigFilePath = Path.Combine(Application.dataPath, "./packages.config");
```

They will be like this(just add the Nuget Folder tp the path):
```
public static readonly string NugetConfigFilePath = Path.Combine(Application.dataPath, "./NuGet/NuGet.config");
private static readonly string PackagesConfigFilePath = Path.Combine(Application.dataPath, "./NuGet/packages.config");
```

Hope it solve ur problem if it's still occurs.

**Comment by jasonhbartlett** [comment]
I think I was getting this error because I had an old Nuget.config file in my project (from previously using "MSBuild for Unity".  I needed to close Unity, delete that old Nuget.config file, and then reopen Unity.  Then the error went away.

**Comment by jwittner** [comment]
@tobi1449 - can you confirm if you were using MSBuildForUnity and that this might be the issue?

**Comment by tobi1449** [comment]
Yeah, that might have been the issue.

**Comment by RichLogan** [comment]
I merged my two Nuget configs manually and that seemed to work fine for both NuGet and MSBuild. Just added: 

```<add key="MSBuildForUnity" value="https://pkgs.dev.azure.com/UnityDeveloperTools/MSBuildForUnity/_packaging/UnityDeveloperTools/nuget/v3/index.json" />``` to the default NuGetForUnity config. I get some console errors for the repo, but it doesn't seem to negatively affect anything.
