### ISSUE TITLE
Unable to choose version from public Nuget

### ISSUE THREAD

**Issue by hoihoi8** [GlitchEnzo/NuGetForUnity#329]
## Description
Select "Show all versions"
## Results
Only the latest version of a package on the public Nuget is shown.
## Expected results
You should be able to choose older versions in the GUI
## Reasoning
There are many reasons why you would need to choose an older version of a library: You don't have access to the source code and it uses a legacy version; The environment you are using doesn't support the framework of the newest version; etc

- **CommandLineParser
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2019.3.2f1
- **Operating System:** OSX High Sierra

**Comment by jwittner** [comment]
Yeah, an unfortunate limitation of the NuGet API that's been raised before in #260, which we resolved "won't fix" with:

> This appears to be a limitation of the nuget.org API. It works as expected for other endpoints, and I've verified that finding packages via the nuget cli results in the same package set.

Would be keen to have a good solution for this problem in the code, but in the meantime I believe people have been modifying their packages.config by hand, then reloading Unity, to install older versions of packages.

Do let me know if you research anything further on the API front that might make this workable within NuGetForUnity! =)
