### ISSUE TITLE
Microsoft.Windows.MixedReality.DotNetWinRT package causes UnityException on Build

### ISSUE THREAD

**Issue by jasonhbartlett** [GlitchEnzo/NuGetForUnity#332]
- **NuGet Package:** Microsoft.Windows.MixedReality.DotNetWinRT ver:0.5.1049
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2018.4.20f1
- **Operating System:** Windows 10 Pro
- **Target:** UWP
- **Scripting Backend:** .NET
- **Platform:** HoloLens
- **Architecture** ARM

Steps to Reproduce:
1. Create a new Unity Project in 2018.4.
2. Import NuGet for Unity version 2.0.0
3. Use N4U to install the DotNetWinRT package (also installs System.Draw.Primitives)
4. Set project settings as specified above.
5. Add Sample Scene and Click Build

Build fails with the following UnityException:

`UnityException: Failed to run reference rewriter with command "--target=Temp\StagingArea\Unity.Analytics.DataPrivacy.dll" "--target=Temp\StagingArea\Unity.TextMeshPro.dll" "--target=Temp\StagingArea\Unity.XR.WindowsMR.dll" "--target=Temp\StagingArea\UnityEngine.Timeline.dll" "--target=Temp\StagingArea\UnityEngine.UI.dll" "--target=Temp\StagingArea\System.Drawing.Primitives.dll" "--target=Temp\StagingArea\UnityEngine.SpatialTracking.dll" "--target=Temp\StagingArea\Microsoft.Windows.MixedReality.DotNetWinRT.dll" "--target=Temp\StagingArea\UnityEngine.Networking.dll" "--additionalreferences=Temp\StagingArea,Temp\StagingArea\Plugins\X64,Temp\StagingArea\Plugins\ARM,Temp\StagingArea\Plugins\ARM64,Temp\StagingArea\Plugins\X86,C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.MachineLearningContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsPhoneContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsVoipContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.StartupTaskContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.DevicesLowLevelContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.PrintersContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardEmulatorContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.UniversalApiContract\8.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.XboxLive.StorageApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Graphics.Printing3D.Printing3DContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Sockets.ControlChannelTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.GuidanceContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.LocalSearchContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Store.StoreContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.TargetedContent.TargetedContentContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileSharedModeContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.SystemManagementContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Core.Direct.XamlDirectContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.SearchContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Input.GamingInputPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Preview.GamesEnumerationContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GameChatOverlayContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GamingUIProviderContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppBroadcasting.AppBroadcastingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppRecording.AppRecordingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppBroadcastContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureMetadataContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.GameBarContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Devices.CallControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.MediaControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Playlists.PlaylistsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.XboxLive.XboxLiveSecureSocketsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.EnterpriseData.EnterpriseDataContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Storage.Provider.CloudFilesContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Shell.SecurityAppManagerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Hosting.HostingContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.PhoneContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0" "--platform=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade\Windows.winmd" "--dbg=pdb" "--support=Temp\StagingArea\WinRTLegacy.dll" "--supportpartialns=Unity.Partial" "--system=System" "--lock=UWP\project.lock.json" "--alt=Microsoft.Win32.SafeHandles,System.IO.FileSystem;Microsoft.Win32.SafeHandles,System.Runtime.Handles;System,System.ComponentModel;System,System.Data.Common;System,System.Runtime;System,System.Runtime.Extensions;System,System.Runtime.InteropServices;System,System.Threading.Tasks;System.CodeDom.Compiler,System.Diagnostics.Tools;System.Collections,System.Collections;System.Collections,System.Collections.NonGeneric;System.Collections,System.Runtime;System.Collections.Generic,System.Collections;System.Collections.Generic,System.Runtime;System.Collections.ObjectModel,System.ObjectModel;System.Collections.ObjectModel,System.Runtime;System.Collections.Specialized,System.Collections.NonGeneric;System.Collections.Specialized,System.Collections.Specialized;System.Collections.Specialized,System.ObjectModel;System.ComponentModel,Microsoft.Win32.Primitives;System.ComponentModel,System.ComponentModel;System.ComponentModel,System.ComponentModel.EventBasedAsync;System.ComponentModel,System.ObjectModel;System.ComponentModel,System.Runtime;System.ComponentModel.DataAnnotations,System.ComponentModel.Annotations;System.Data,System.Data.Common;System.Data.Common,System.Data.Common;System.Diagnostics,System.Diagnostics.Debug;System.Diagnostics,System.Diagnostics.StackTrace;System.Diagnostics,System.Runtime;System.Diagnostics,System.Runtime.Extensions;System.Diagnostics.CodeAnalysis,System.Diagnostics.Tools;System.Globalization,System.Globalization;System.Globalization,System.Globalization.Calendars;System.Globalization,System.Globalization.Extensions;System.Globalization,System.Runtime;System.IO,System.IO;System.IO,System.IO.FileSystem;System.IO,System.IO.FileSystem.Primitives;System.IO,System.IO.UnmanagedMemoryStream;System.IO,System.Runtime;System.IO,System.Runtime.Extensions;System.IO,System.Runtime.Handles;System.IO.Compression,System.IO.Compression;System.IO.IsolatedStorage,System.IO.IsolatedStorage;System.Linq,System.Linq;System.Linq,System.Linq.Expressions;System.Linq,System.Linq.Queryable;System.Linq.Expressions,System.Linq.Expressions;System.Net,System.Net.Primitives;System.Net,System.Net.Requests;System.Net,System.Net.WebHeaderCollection;System.Net.NetworkInformation,System.Net.NetworkInformation;System.Net.NetworkInformation,System.Net.Primitives;System.Net.Security,System.Net.Primitives;System.Net.Sockets,System.Net.Primitives;System.Net.Sockets,System.Net.Sockets;System.Reflection,System.Reflection;System.Reflection,System.Reflection.Extensions;System.Reflection,System.Reflection.Primitives;System.Reflection,System.Reflection.TypeExtensions;System.Reflection,System.Runtime;System.Reflection,System.Runtime.InteropServices;System.Reflection.Emit,System.Reflection.Primitives;System.Resources,System.Resources.ResourceManager;System.Runtime,System.Runtime;System.Runtime.CompilerServices,System.Runtime;System.Runtime.InteropServices,System.Runtime;System.Runtime.InteropServices,System.Runtime.Handles;System.Runtime.InteropServices,System.Runtime.InteropServices;System.Runtime.InteropServices.ComTypes,System.Runtime.InteropServices;System.Runtime.Serialization,System.Runtime.Serialization.Primitives;System.Runtime.Serialization,System.Runtime.Serialization.Xml;System.Runtime.Serialization.Json,System.Runtime.Serialization.Json;System.Security,System.Runtime;System.Security.Authentication,System.Net.Primitives;System.Security.Principal,System.Security.Claims;System.Security.Principal,System.Security.Principal;System.ServiceModel,System.ServiceModel.Duplex;System.ServiceModel,System.ServiceModel.Http;System.ServiceModel,System.ServiceModel.NetTcp;System.ServiceModel,System.ServiceModel.Primitives;System.ServiceModel,System.ServiceModel.Security;System.ServiceModel.Channels,System.ServiceModel.Http;System.ServiceModel.Channels,System.ServiceModel.NetTcp;System.ServiceModel.Channels,System.ServiceModel.Primitives;System.ServiceModel.Channels,System.ServiceModel.Security;System.ServiceModel.Description,System.ServiceModel.Primitives;System.ServiceModel.Dispatcher,System.ServiceModel.Primitives;System.ServiceModel.Security,System.ServiceModel.Primitives;System.ServiceModel.Security,System.ServiceModel.Security;System.ServiceModel.Security.Tokens,System.ServiceModel.Security;System.Text,System.Globalization.Extensions;System.Text,System.Runtime;System.Text,System.Text.Encoding;System.Text,System.Text.Encoding.Extensions;System.Text.RegularExpressions,System.Text.RegularExpressions;System.Threading,System.Runtime;System.Threading,System.Threading;System.Threading,System.Threading.Overlapped;System.Threading,System.Threading.Timer;System.Xml,System.Runtime.Serialization.Xml;System.Xml,System.Xml.ReaderWriter;System.Xml,System.Xml.XmlDocument;System.Xml.Linq,System.Xml.XDocument;System.Xml.Schema,System.Xml.ReaderWriter;System.Xml.Serialization,System.Xml.ReaderWriter;System.Xml.Serialization,System.Xml.XmlSerializer;<winmd>,Windows.winmd;<winmd>,Windows.AI.MachineLearning.M<message truncated>`

**Comment by JoC0de** [comment]
At the time this issue was created this package wasn't actively maintained. So sorry for eventual trouble. Now there are some new active contributors. 

I tried to reproduce but everything works. If someone else has a similar issue we can try to solve it.
