### ISSUE TITLE
I have some question

### ISSUE THREAD

**Issue by zhoujiazhi222** [GlitchEnzo/NuGetForUnity#334]
1.Do I need to upload the directory Assets/Nuget to git repo If I using ci for build？ 
2.Can I switch the Assets/Nuget directory, for example, switch it to Assets/Tool/Nuget
3.I installed Nlog , but when want use NLog , Rider can not found Nlog
<img width="282" alt="Screen Shot 2020-06-27 at 6 31 41 PM" src="https://user-images.githubusercontent.com/20750357/85920222-91e3e380-b8a4-11ea-8a61-39ac293ddcbb.png">
<img width="323" alt="Screen Shot 2020-06-27 at 6 31 58 PM" src="https://user-images.githubusercontent.com/20750357/85920224-93ada700-b8a4-11ea-80ef-2441be72ada0.png">
<img width="786" alt="Screen Shot 2020-06-27 at 6 32 19 PM" src="https://user-images.githubusercontent.com/20750357/85920226-94ded400-b8a4-11ea-910c-bb0a1f2f6c48.png">

**Comment by zhoujiazhi222** [comment]
Who can help me

**Comment by jwittner** [comment]
Hey @zhoujiazhi222! Thanks for reaching out!

> 1.Do I need to upload the directory Assets/Nuget to git repo If I using ci for build？

You should add the Nuget project to your source repo as it won't be automatically installed. The Assets/Packages folder where NuGetForUnity installs packages should be excluded form git (including the Packages.meta file).

> 2.Can I switch the Assets/Nuget directory, for example, switch it to Assets/Tool/Nuget

I believe you can move NuGetForUnity wherever you'd like, but updating the package in the future will be more difficult if you don't keep the default.

> 3.I installed Nlog , but when want use NLog , Rider can not found Nlog

Can you give us details on the Unity Version, N4U version, Platform Target, and Scripting Backend?

**Comment by zhoujiazhi222** [comment]
Thank you ，I finally solved this problem，Because the capitalization is wrong，the correct one is **NLog** ， not **Nlog**
@jwittner
