### ISSUE TITLE
Multiple assemblies with equivalent identity have been imported

### ISSUE THREAD

**Issue by EricBatlle** [GlitchEnzo/NuGetForUnity#336]
## Description

When installing Stripe through NuGetForUnity it also installs a bunch of System.XXX in packages, which results in the following error: 

> Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> error CS1703: Multiple assemblies with equivalent identity have been imported

If I delete manually those directories, unity eventually re-download again those dll's :S

- **NuGet Package:** Stripe.net 37.20.0
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.3.13f1
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
Right now N4U doesn't do anything to ignore the System dependencies that Unity includes by default when targeting .Net Standard for the scripting runtime. If possible, the easiest work around at the moment is to target .Net 4.x. if a package you are using causes this to happen.

**Comment by YStrauch** [comment]
Could you provide information on how to change the target?

**Comment by jwittner** [comment]
[Here are the docs ](https://docs.unity3d.com/2019.3/Documentation/Manual/dotnetProfileSupport.html)for the changing the .NET API Compatibility Profile for Unity 2019.3 - the version referenced in this bug.

**Comment by jwittner** [comment]
Note: This may be resolved by #357 .

**Comment by KonH** [comment]
Looks like it will be resolved by #357 (tested on Unity 2019.4.0f1, .NET Standard 2.0 subset, MacOS)
