### ISSUE TITLE
No button for NuGet in Unity

### ISSUE THREAD

**Issue by ksyao2002** [GlitchEnzo/NuGetForUnity#338]
## Description
[Describe the issue you have.]

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
- **Unity Version:** [What version of Unity are you using?]
- **Operating System:** [What OS are you on?]

Downloaded package as stated in readme, imported package into unity. What's the next step? I still don't see the tab that says NuGet at the top:

![image](https://user-images.githubusercontent.com/53455408/89718700-86e1a000-d986-11ea-8d3a-5de7a23117e7.png)

**Comment by jwittner** [comment]
Hmmm, did you try reloading Unity after installing the package?

**Comment by ksyao2002** [comment]
Yes sorry, I just needed to close and reopen it.
