### ISSUE TITLE
Can't install Microsoft.Office.Interop.Excel

### ISSUE THREAD

**Issue by longtran2904** [GlitchEnzo/NuGetForUnity#340]
## Description
When I installed Microsoft.Office.Interop.Excel it did install successful (I saw it in the Installed tab) but I couldn't use it in visual studio. Visual Studio just keeps telling me that "the type of namespace didn't exist...". If I install it directly through visual studio NuGet then unity wouldn't recognize it. I've tried to install some other packages (through NuggetForUnity) and it all works ok. Am I missing something?

- **NuGet Package:** 5.4.0
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.4.8f1
- **Operating System:** [Windows 10]

**Comment by jwittner** [comment]
Thanks for posting the issue @longtran2904. When I try to install that package, I also see it in the Installed list, but I get several errors in the Unity error log about issues with references the DLL makes.

```
Assembly 'Assets/Packages/Microsoft.Office.Interop.Excel.15.0.4795.1000/lib/net20/Microsoft.Office.Interop.Excel.dll' will not be loaded due to errors:
Unable to resolve reference 'office'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Microsoft.Vbe.Interop'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```
Seems like the package is assuming you have some other packages installed? It doesn't have any dependencies though so mileage may vary acquiring 'office' and 'Microsoft.Vbe.Interop'.

Differences in testing environment:
* Unity 2019.4.3f1
* Package - microsoft.office.interop.excel.15.0.4795.1000
  * I couldn't find a version matching 5.4.0 as you stated. =(

**Comment by longtran2904** [comment]
@jwittner So what can I do now?

**Comment by jwittner** [comment]
@longtran2904 - I think you need to dig into what the real dependencies of this package are? If you're not in Unity (say, in a 'normal' VS project), how do the 'office' and 'Microsoft.Vbe.Interop' references get resolved?

**Comment by jwittner** [comment]
@longtran2904 - would love any notes on how you solved this if you did, for posterity. =)

**Comment by longtran2904** [comment]
Sorry, I just move on and don't need it anymore.
