### ISSUE TITLE
Unable to install NuGetForUnity 2.0.1 with Unity 2020.1

### ISSUE THREAD

**Issue by hummlj** [GlitchEnzo/NuGetForUnity#341]
## Problem:
After installing NuGetForUnity, any GUI click throws the following error in the Unity console:

System.TypeInitializationException: The type initializer for 'NugetForUnity.NugetHelper' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at NugetForUnity.NugetHelper.LoadNugetConfigFile () [0x0011c] in <d5348c0adcb941678978d77f32d61a2a>:0 
  at NugetForUnity.NugetHelper..cctor () [0x001e6] in <d5348c0adcb941678978d77f32d61a2a>:0 
   --- End of inner exception stack trace ---
  at NugetForUnity.NugetWindow.Refresh (System.Boolean forceFullRefresh) [0x00014] in <d5348c0adcb941678978d77f32d61a2a>:0 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetWindow:Refresh(Boolean)
NugetForUnity.NugetWindow:OnEnable()
UnityEditor.EditorWindow:GetWindow()
NugetForUnity.NugetWindow:DisplayNugetWindow()

and

NullReferenceException: Object reference not set to an instance of an object
NugetForUnity.NugetHelper.LoadNugetConfigFile () (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetHelper..cctor () (at <d5348c0adcb941678978d77f32d61a2a>:0)
Rethrow as TypeInitializationException: The type initializer for 'NugetForUnity.NugetHelper' threw an exception.
NugetForUnity.NugetWindow.DrawOnline () (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetWindow.OnGUI () (at <d5348c0adcb941678978d77f32d61a2a>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <701f6580abad44cfb237a543dcd0d94b>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <701f6580abad44cfb237a543dcd0d94b>:0)
UnityEditor.DockArea.OldOnGUI () (at <701f6580abad44cfb237a543dcd0d94b>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <9c9fa79efe9e479a8cbe7a6f99f673d3>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <2500dd078a544a69b6c923861af6cd15>:0)

How can I resolve this issue and start installing NuGets?
Thanks for your help!

- **NuGetForUnity Version:** 2.0.0 (also with 2.0.1)
- **Unity Version:** 2020.1.3f1
- **Operating System:** Windows10
- **other packages:** Mixed Reality Toolkit, MSBuild
<img width="772" alt="NuGetUnityError" src="https://user-images.githubusercontent.com/40237504/92101636-b34dd800-eddd-11ea-9dd2-a6100174fd5f.png">

**Comment by hummlj** [comment]
Hi,

I imported NuGet packages this way, but still feel the NuGetForUnity problem should be addressed...

https://github.com/microsoft/MSBuildForUnity/blob/master/Documentation/CoreScenarios.md

Best,
J

**Comment by jwittner** [comment]
@hummlj - thanks for following up that you got a work around. I couldn't reproduce any issues opening N4U windows by doing:

* Create a new project with Unity 2020.1.4f1
* Import N4U 2.0.1 from [UnityPackage](https://github.com/GlitchEnzo/NuGetForUnity/releases/tag/v2.0.1).
* Nuget->Manage Nuget Packages.
* Install Newtonsoft.Json 12.0.3
* Install Microsoft.MixedReality.Toolkit.Foundation 2.3.0
* Close/Reopen Unity.

I do get some errors about multiple assemblies with the same name from Microsoft.Mixedreality.Toolkit.Async.dll, but I think that's an MRTK issue.

Think you could elaborate on the process that's reproducing this issue?
