### ISSUE TITLE
Conflict with OdinInspector - folders present un "Assets/Packages" are automatically deleted

### ISSUE THREAD

**Issue by Mythique** [GlitchEnzo/NuGetForUnity#344]
## Description

When installing OdinInspector through Unity's PackageManager, it will create a folder at `Assets/Packages/com.package.odin`. Unfortunately this folder is automatically erased by NuGetForUnity when downloading a NuGet package.

- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.4.10f1
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
Oh no! This is the first conflict we've seen with something using the "Assets/Packages" folder. One option for a solution would be to create a ScriptableObject to drive exclusion of folders under Packages from being managed by NuGetForUnity.

**Comment by wightwhale** [comment]
This happened to me too with packages I already had in that folder. Not sure wiping that folder is the best idea.
