### ISSUE TITLE
CsvHelper.Excel lib folder is empty

### ISSUE THREAD

**Issue by Mythique** [GlitchEnzo/NuGetForUnity#345]
## Description

CsvHelper.Excel is not installed properly. The nupkg is properly downloaded but the lib folder is empty. No dependencies were downloaded.

- **NuGet Package:** CsvHelper.Excel 1.0.6
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.4.10f1
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
Interesting, are you targetting .NetStandard 2.0 or .Net 4.x out of curiosity?

**Comment by Mythique** [comment]
I was targeting .NetStandard 2.0. When targeting .Net 4.x the lib folder is not empty anymore but some dependencies seem incompatible with .Net 4.x unfortunately (but I guess this specific issue is related to the library and not NuGetForUnity).

**Comment by jwittner** [comment]
Note: This issue may be resolved by #357

**Comment by KonH** [comment]
Unfortunately, #357 do nothing about that issue, the directory still empty (tested on Unity 2019.4.0f1, .NET Standard 2.0 subset, MacOS)

**Comment by JoC0de** [comment]
CsvHelper.Excel just doesn't support .Net Standard 2.0 see:
https://nuget.info/packages/CsvHelper.Excel/1.0.6
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/53140583/4c727f59-55b2-47fb-a877-eadae6252368)
