### ISSUE TITLE
NullReferenceException on asset database refresh

### ISSUE THREAD

**Issue by biosmanager** [GlitchEnzo/NuGetForUnity#346]
## Description
`NullReferenceException` on asset database refresh. Every now and then when some assets are updated, a couple of these messages appear in the log:

```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.GameObjectInspector.ClearPreviewCache () (at <8004fcc221b54f98ba547350ea71d812>:0)
UnityEditor.GameObjectInspector.ReloadPreviewInstances () (at <8004fcc221b54f98ba547350ea71d812>:0)
UnityEditor.GameObjectInspector.OnForceReloadInspector () (at <8004fcc221b54f98ba547350ea71d812>:0)
UnityEditor.AssetDatabase:Refresh()
NugetForUnity.NugetHelper:Restore()
NugetForUnity.NugetHelper:.cctor()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
```

- **NuGet Package:** n/a
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.4.10f1
- **Operating System:** Windows 10 Version 2004 (64 bit)

**Comment by jwittner** [comment]
Interesting. Looks like a Unity bug from the callstack - curious if AssetDatabase.Refresh is no longer allowed/expected during InitializeOnLoad methods in 2019.4.

**Comment by jwittner** [comment]
Have you experienced any other problems besides the log that seem related @biosmanager ?

**Comment by biosmanager** [comment]
@jwittner 

No, not really. The error frequently occurs when I change some script or asset but after I entered Play mode it disappears.
IIRC this issue was also present on earlier Unity 2019.x versions.

This issue from another project could be related:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1713

**Comment by andreasanta** [comment]
Same issue with Unity 2019.4.8f1 - I cannot install any packages.

**Comment by WazWaz** [comment]
Still present in Unity 2020.1.2f1. Didn't prevent installs in 2020 or in 2019.4.9f1.

It seems to happen only (but not in all cases) when a Scene object is selected and AssetDatabase.Refresh() is called. Certainly a Unity bug, but a very annoying one.

**Comment by benoit-dubreuil** [comment]
I have the same problem and crashes my Odin Inspector.

**Comment by jwittner** [comment]
Since this appears to be a Unity issue, I'm closing this. If anyone finds/wants to contribute a work around in the N4U code, then I'd gladly accept one. =)
