### ISSUE TITLE
nuget.org "FindByPackageById" API fails but "Packages" API works

### ISSUE THREAD

**Issue by sipsorcery** [GlitchEnzo/NuGetForUnity#348]
## Description
I'm attempting to install the latest version of my own nuget package, `SIPSorcery v4.0.77-pre`. Using `nugetforunity` I am only able to install an earlier version `SIPSorcery v4.0.60-pre`.

In an attempt to workaround the problem I manually set the required versions in the `nugetforunity` `packages.config` file.

With the `<add key="verbose" value="true" />` I the relevant log messages in the Unity console are:

````
Getting packages from: http://www.nuget.org/api/v2/FindPackagesById()?id='SIPSorcery'&$orderby=Version asc&$filter=Version eq '4.0.77-pre'
HTTP GET http://www.nuget.org/api/v2/FindPackagesById()?id='SIPSorcery'&$orderby=Version asc&$filter=Version eq '4.0.77-pre'
Retreived 0 packages in 278 ms
Failed to find SIPSorcery 4.0.77-pre
````

It looks like the problem is with the nuget.org API and possibly related to #260.

Works: [http://www.nuget.org/api/v2/FindPackagesById()?id='SIPSorcery'&$orderby=Version asc&$filter=Version eq '4.0.60-pre'](https://www.nuget.org/api/v2/FindPackagesById()?id=%27SIPSorcery%27&$orderby=Version%20asc&$filter=Version%20eq%20%274.0.60-pre%27)

Fails: [http://www.nuget.org/api/v2/FindPackagesById()?id='SIPSorcery'&$orderby=Version asc&$filter=Version eq '4.0.61-pre'](https://www.nuget.org/api/v2/FindPackagesById()?id=%27SIPSorcery%27&$orderby=Version%20asc&$filter=Version%20eq%20%274.0.61-pre%27)

Fails: [http://www.nuget.org/api/v2/FindPackagesById()?id='SIPSorcery'&$orderby=Version asc&$filter=Version eq '4.0.77-pre'](https://www.nuget.org/api/v2/FindPackagesById()?id=%27SIPSorcery%27&$orderby=Version%20asc&$filter=Version%20eq%20%274.0.77-pre%27)

All the requested versions exist. I suspect the nuget.org API is hitting some limit due to the number of versions my package has.

The alternative `Packages` API method seems to work correctly.

Works: [https://www.nuget.org/api/v2/Packages(Id='SIPSorcery',Version='4.0.60-pre')](https://www.nuget.org/api/v2/Packages(Id='SIPSorcery',Version='4.0.60-pre'))
Works: [https://www.nuget.org/api/v2/Packages(Id='SIPSorcery',Version='4.0.61-pre')](https://www.nuget.org/api/v2/Packages(Id='SIPSorcery',Version='4.0.61-pre'))
Works: [https://www.nuget.org/api/v2/Packages(Id='SIPSorcery',Version='4.0.77-pre')](https://www.nuget.org/api/v2/Packages(Id='SIPSorcery',Version='4.0.77-pre'))

- **NuGet Package:** SIPSorcery v4.0.77-pre
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** Unity 2019.4.10f1 Personal
- **Operating System:** Windows 10 Pro 10.0.19041

**Comment by JoC0de** [comment]
Should be fixed by #549 if the problem still exists please leave a comment.
