### ISSUE TITLE
Nuget for Unity installs too many packages

### ISSUE THREAD

**Issue by NiklasElze** [GlitchEnzo/NuGetForUnity#354]
## Description
Nuget for Unity installs too many packages. Aside from the package I want to install, it also installs packages from the System namespace (like System.IO, System.Linq, System.Collections, etc.), which should not be installed, because obviously those DLLs are already present.

Because of the installation of those additional DLLs, Unity complains about "Multiple assemblies with equivalent identity".

The full content of the packages.config file after I installed only the one package mentioned below:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Castle.Core" version="4.4.0" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" />
  <package id="Microsoft.NETCore.Targets" version="1.1.0" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" />
  <package id="Moq" version="4.15.1" />
  <package id="NETStandard.Library" version="1.6.1" />
  <package id="runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.native.System" version="4.3.0" />
  <package id="runtime.native.System.IO.Compression" version="4.3.0" />
  <package id="runtime.native.System.Net.Http" version="4.3.0" />
  <package id="runtime.native.System.Security.Cryptography.Apple" version="4.3.0" />
  <package id="runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple" version="4.3.0" />
  <package id="runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="System.AppContext" version="4.3.0" />
  <package id="System.Buffers" version="4.3.0" />
  <package id="System.Collections" version="4.3.0" />
  <package id="System.Collections.Concurrent" version="4.3.0" />
  <package id="System.Collections.NonGeneric" version="4.3.0" />
  <package id="System.Collections.Specialized" version="4.3.0" />
  <package id="System.ComponentModel" version="4.3.0" />
  <package id="System.ComponentModel.Primitives" version="4.3.0" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" />
  <package id="System.Console" version="4.3.0" />
  <package id="System.Diagnostics.Debug" version="4.3.0" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" />
  <package id="System.Diagnostics.Tools" version="4.3.0" />
  <package id="System.Diagnostics.TraceSource" version="4.3.0" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" />
  <package id="System.Dynamic.Runtime" version="4.3.0" />
  <package id="System.Globalization" version="4.3.0" />
  <package id="System.Globalization.Calendars" version="4.3.0" />
  <package id="System.Globalization.Extensions" version="4.3.0" />
  <package id="System.IO" version="4.3.0" />
  <package id="System.IO.Compression" version="4.3.0" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" />
  <package id="System.IO.FileSystem" version="4.3.0" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" />
  <package id="System.Linq" version="4.3.0" />
  <package id="System.Linq.Expressions" version="4.3.0" />
  <package id="System.Net.Http" version="4.3.0" />
  <package id="System.Net.Primitives" version="4.3.0" />
  <package id="System.Net.Sockets" version="4.3.0" />
  <package id="System.ObjectModel" version="4.3.0" />
  <package id="System.Reflection" version="4.3.0" />
  <package id="System.Reflection.Emit" version="4.3.0" />
  <package id="System.Reflection.Emit.ILGeneration" version="4.3.0" />
  <package id="System.Reflection.Emit.Lightweight" version="4.3.0" />
  <package id="System.Reflection.Extensions" version="4.3.0" />
  <package id="System.Reflection.Primitives" version="4.3.0" />
  <package id="System.Reflection.TypeExtensions" version="4.3.0" />
  <package id="System.Resources.ResourceManager" version="4.3.0" />
  <package id="System.Runtime" version="4.3.0" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" />
  <package id="System.Runtime.Extensions" version="4.3.0" />
  <package id="System.Runtime.Handles" version="4.3.0" />
  <package id="System.Runtime.InteropServices" version="4.3.0" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" />
  <package id="System.Runtime.Numerics" version="4.3.0" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" />
  <package id="System.Security.Cryptography.Cng" version="4.3.0" />
  <package id="System.Security.Cryptography.Csp" version="4.3.0" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" />
  <package id="System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" />
  <package id="System.Text.Encoding" version="4.3.0" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" />
  <package id="System.Text.RegularExpressions" version="4.3.0" />
  <package id="System.Threading" version="4.3.0" />
  <package id="System.Threading.Tasks" version="4.3.0" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.1" />
  <package id="System.Threading.Timer" version="4.3.0" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" />
  <package id="System.Xml.XDocument" version="4.3.0" />
  <package id="System.Xml.XmlDocument" version="4.3.0" />
</packages>
```

- **NuGet Package:** Moq, 4.15.1
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2020.1.6f1
- **Operating System:** Win 10, 64 bit

**Comment by NiklasElze** [comment]
The issue still exists after updating Nuget for Unity to 2.0.1.

**Comment by jwittner** [comment]
@NiklasElze - thanks for making the issue. This has shown up quite a bit, e.g. #343 and I'd say it's our number one issue at the moment. Fastest way around it is to target .Net 4.6 instead of .Net Standard.

The cru of the problem is that Unity includes many of the dependencies by default that normally, i.e. in pure .Net programs, are included as NuGet packages. Long term hope is to scan the directory of the currently executing Unity editor and disable any assemblies that Unity is including.

**Comment by NiklasElze** [comment]
@jwittner Thanks for the reply. Switching to .NET 4.6 solved the issue.

**Comment by KonH** [comment]
@jwittner 
Have the same issue, I want to help to address it if you still need such help.

**Comment by cryptogrounds** [comment]
Currently having the same issue, Unity version 2020.1.16f1 .NET 4.x

**Comment by jwittner** [comment]
@KonH - thanks for reaching out re: helping to resolve this issue. There are a couple of options I think for solutions here, but I'm open to others, and I definitely have a preference.

## 1. Preferred - Detect and ignore assemblies in packages that Unity already provides.
I was hoping for a solution that could automatically upgrade with Unity, such as one that scanned the correct, i.e. the one corresponding to the current scripting settings, Unity install directory folders for dll files that Unity has already installed and delete any with matching names from lib folders when installing nuget packages.

Example folders:
* C:\Program Files\Unity\Hub\Editor\2019.4.15f1\Editor\Data\NetStandard\compat\2.0.0\shims\netstandard\
* C:\Program Files\Unity\Hub\Editor\2019.4.15f1\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\

## 2. Work Around - Add a configuration file that NugetForUnity to control disallowed dll paths.
NugetForUnity could load a configuration that dictates what libraries shouldn't be allowed to be installed via a nuget package. We'd want to have support for configuring different sets of files based on the scripting settings / unity version. And users would most likely need to manually configure these. Though I think we could provide a good template.

If we build the first system, we could later read from this configuration file to append to our list of automatically detected disallowed dlls.

Interested in yours and anyone elses thoughts on these solutions!

**Comment by KonH** [comment]
I think a first option is better and we can detect such paths based on 
[Process.GetCurrentProcess().MainModule.FileName](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processmodule.filename?view=net-5.0) to inspecting actual directory regardless of install location (editor can be installed manually or install location can be changed in Unity Hub UI). But multi-platform support here is important, way to detect base path may be different on each available editor platform. For example, on Mac OS:

- Executable path looks like '/Applications/Unity/Hub/Editor/2019.4.15f1/Unity.app/Contents/MacOS/Unity'
- Dependencies found here: '/Applications/Unity/Hub/Editor/2019.4.15f1/Unity.app/Contents/NetStandard/compat/2.0.0/shims/netstandard' and '/Applications/Unity/Hub/Editor/2019.4.15f1/Unity.app/Contents/MonoBleedingEdge/lib/mono/4.7.1-api'

Unfortunately, I don't sure about directory layout on Linux for now.

**Comment by jwittner** [comment]
I believe we can use [EditorApplication.applicationPath](https://docs.unity3d.com/ScriptReference/EditorApplication-applicationPath.html) to get the path to the currently running Unity executable.

**Comment by KonH** [comment]
Right, it looks better. How can I help for now?

**Comment by jwittner** [comment]
At [this line ](https://github.com/GlitchEnzo/NuGetForUnity/blob/e37c13edeede576493d92f9b204ddcb5a7b2e41d/Assets/NuGet/Editor/NugetHelper.cs#L402)you can see where we're deleting subfolders of the Nuget "lib" folder based on the "best" target framework for the given settings. Around this point in the code I think we should:

1. Use this same "best" target framework and the idea above to scour the Unity install directory for dlls that Unity already provides for that "best" target framework.
2. Look in the selected lib directories that we're keeping and delete any dlls that Unity is already providing.

Does that make sense?

**Comment by KonH** [comment]
Yeah, I will try to make PR for that in next few days.

**Comment by KonH** [comment]
@jwittner PR was made, please review.

Verbose log for sample installation of the already imported library looks like this:
```
Cleaning .../NuGetForUnity/Assets/Packages/System.Linq.Expressions.4.3.0
All existing path to dependency lookup are: /Applications/Unity/Hub/Editor/2019.4.0f1/Unity.app/Contents/NetStandard/compat/2.0.0/shims/netstandard, /Applications/Unity/Hub/Editor/2019.4.0f1/Unity.app/Contents/MonoBleedingEdge/lib/mono/4.7.1-api
Already imported libs: Microsoft.Win32.Primitives, System.AppContext, System.Collections.Concurrent...
Is package 'System.Linq.Expressions' already imported? True
```

I tried this change against `Moq` (my original issue was related to it) package and it works fine.

But I have some concerns about this solution:
- Packages still exist in packages.config file and inside Assets/Packages directory but without importable libraries (I think it's better to skip it earlier, but don't have enough time for now to find a better place for import check; I ready to move it when got a better understanding of core logic)
- Hard-coding of dependencies sources will lead to issues in future Editor updates, maybe it's better to lookup for more common directories? (`NetStandard/compat` and `MonoBleedingEdge/lib/mono` only, not sub-directories)
- I'm not sure about Windows compatibility (isn't tested), but it looks like the proposed solution should work with it (selecting Data inside root of `EditorApplication.applicationPath`)

**Comment by KonH** [comment]
My bad, I think I understand how to work properly with compat and mono directories based on the detected framework, will investigate details and provide an additional commit tomorrow.

**Comment by KonH** [comment]
No, I'm not sure about the correct approach for target framework usage. I tried to scan libraries from `NetStandard/compat` only for netstandard libs, but it is not valid: in that case, I got a "Multiple assemblies" error because `MonoBleedingEdge/lib/mono` still used.
Skip that concern for now, will look at the earlier skip as a next step.
Also, I commit common directories usage in that PR.

**Comment by KonH** [comment]
I've added import check on the [earlier install stage](https://github.com/GlitchEnzo/NuGetForUnity/pull/357/commits/7cfdae0ac6dba8f4a7c5f68da158fb637084fe21), now it works much faster and does not add unwanted dependencies in `Assets/Packages` and `packages.config`.
