### ISSUE TITLE
Can't find correct dependencies when installing NetMQ

### ISSUE THREAD

**Issue by LovelyCatHyt** [GlitchEnzo/NuGetForUnity#356]
## Description
In unity, after installing NetMQ, I only get errors with _"Is assembly missing or incompatible with the current platform?"_ on the pkg System.Private.ServiceModule
Before using NugetForUnity, I created another project in VS and install NetMQ in VS, export all dlls to directory `Assets/Plugins`, it doesn't work neither; but after manully updating System.Private.ServiceModule to the latest version (4.8.0), and export the dlls to `Assets/Plugins`, it works.
Then I deleted everything generated by VS above, return to NugetForUnity,install NetMQ,  and update System.Private.ServiceModule to 4.8.0 through NugetForUnity --doens't fix the problem.
- **NuGet Package:** NetMQ 4.0.1.6
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.4.3f1
- **Operating System:** Windows 10.0.18363
_Not native English speaker, please forgive my language errors..._

**Comment by JoC0de** [comment]
At the time this issue was created this package wasn't actively maintained. So sorry for eventual trouble. Now there are some new active contributors. 
I can't reproduce the error with the newest version of NuGetForUnity in Unity 2022.2.1f1 and everything works fine.
