### ISSUE TITLE
Nuget packages are not restored in automated build

### ISSUE THREAD

**Issue by rLaister** [GlitchEnzo/NuGetForUnity#358]
We have been using NuGetForUnity in our automated builds without any problems for a long time.
Now I have updated to Unity Version 2020.2.0f1 and none of the installed nuget packages is restored. There is no "Restoring Nuget Packages" Log in the build log file as it was before. It seems like it is just not called. Also no errors concerning nuget package installation.
NuGetForUnity Version is 2.0.1.

**Comment by MJantowski3DQR** [comment]
FYI: We have the same problem in our development process. I reported this behavior as a bug in the cloud building system of unity and the support team was able to reproduce my request. Currently the error has been forwarded to the internal cloud dev team.

**Comment by rLaister** [comment]
@MJantowski3DQR Thanks for the info!

**Comment by rLaister** [comment]
@MJantowski3DQR have there been any fixes for this issue? What is the state of the bug report?

**Comment by MJantowski3DQR** [comment]
@rLaister 

I have only received one last message so far on January 21:

> Thank you for sharing the project and giving a detailed explanation, it helped a lot! We successfully reproduced this issue and have sent it for resolution with our developers.
> Unfortunately, we cannot provide an Issue Tracker link, as issues related to Cloud Services are tracked internally.
> 
> We highly appreciate your contribution. If you have further questions, please feel free to contact us.

I asked multiple times for an update or an status, but i never get a response..

Sry ..

**Comment by rLaister** [comment]
@MJantowski3DQR

Thanks for your reply though!
