### ISSUE TITLE
NugetPakage installing but not working

### ISSUE THREAD

**Issue by A-MH** [GlitchEnzo/NuGetForUnity#359]
## Description
[Describe the issue you have.]
The package download successfuly but when I try "Using ZeroMQ" it doesn't recognise it

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?] ZeroMQ version 4.1.0.31
- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?] 2.0.1
- **Unity Version:** [What version of Unity are you using?] 2019.4.13.f1
- **Operating System:** [What OS are you on?] windows 10

**Comment by jwittner** [comment]
Can you give me more information on what "Using ZeroMQ" is? That's not an option in NugetForUnity that I know of. Also, what do you mean by "it not recognizing it". Can you paste any relevant logs?
