### ISSUE TITLE
Azure Artifacts Custom Package Error

### ISSUE THREAD

**Issue by zkkzkk32312** [GlitchEnzo/NuGetForUnity#362]
## Description

I am trying to add custom Azure Artifacts Nuget package without success.
I have edited/added the \<packageSources> and \<packageSourceCredentials> in the config file.
but I am getting "Unable to retrieve package list...." Error in the Unity console when I hit the refresh button.
Any suggestion would be appreciated. 

...
\<packageSources>
     ...
     \<add key="ABC" value="https://pkgs.dev.azure.com/....json" />
     ...
\</packageSources>
...
\<packageSourceCredentials>
	\<ABC>
		\<add key="Username" value="ABC@ABC.com" />
		\<add key="Password" value="1234567" />
	\</ABC>
\</packageSourceCredentials>
...

System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  at NugetForUnity.NugetHelper.RequestUrl (System.String url, System.String userName, System.String password, System.Nullable`1[T] timeOut) [0x000b9] in <b7bde984cef1447da61a3fd28d4789b0>:0 
  at NugetForUnity.NugetPackageSource.GetPackagesFromUrl (System.String url, System.String username, System.String password) [0x0006c] in <b7bde984cef1447da61a3fd28d4789b0>:0 
  at NugetForUnity.NugetPackageSource.Search (System.String searchTerm, System.Boolean includeAllVersions, System.Boolean includePrerelease, System.Int32 numberToGet, System.Int32 numberToSkip) [0x000ce] in <b7bde984cef1447da61a3fd28d4789b0>:0 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetPackageSource:Search(String, Boolean, Boolean, Int32, Int32)
NugetForUnity.NugetHelper:Search(String, Boolean, Boolean, Int32, Int32)
NugetForUnity.NugetWindow:UpdateOnlinePackages()

- **NuGet Package:** [Custom Azure Artifacts Nuget Package]
- **NuGetForUnity Version:** [2.0.1]
- **Unity Version:** [2019.4]
- **Operating System:** [Windows10]

**Comment by jwittner** [comment]
The "json" portion of your feed leads me to think you're using a NuGet V3 API, which isn't supported by NuGetForUnity (yet). ADO feeds do support the NuGet v2 API though, which is what we use to great success.

**Comment by zkkzkk32312** [comment]
yes its a v3 link, i will try if I can get v2 API working, thanks for the info

**Comment by zkkzkk32312** [comment]
Just tried using v2 API without success. but It does show a popup window asking for credentials. @jwittner  did you have your credentials in the .config file ?

**Comment by jwittner** [comment]
We use the pop-up credentials locally for development, but our build machines depend on credentials in the config for its consumption so I'm certain that both can be made to function. NugetForUnity can't handle passwords that aren't in plain text though - did you set your password by hand or through the Preferences window in Unity? That will configure the config with a plain text password (be sure not to commit that to source).

Highly recommend you remove the password from the config and let the credential provider (the window you saw pop up) do it's work. =)

```xml
<packageSources>
    <add key="ABC" value="..." />
  </packageSources>
  <disabledPackageSources />
  <packageSourceCredentials>
    <ABC>
      <add key="userName" value="ignored" />
      <add key="clearTextPassword" value="..." />
    </ABC>
  </packageSourceCredentials>
```

**Comment by zkkzkk32312** [comment]
@jwittner Gotcha, I was just thinking that since I saw the popup that probably means my config credential wasn't working properly anyways. The popup that showed up only asked for which Microsoft account I wish to use, and then it was able to find the saved password based on cached credentials on this machine. Thanks for the help.

**Comment by jwittner** [comment]
Cool, closing this, but please reopen if you experience more issues.

**Comment by kit-ar-uk** [comment]
@jwittner Please take a look at #422, tested and working with our org.
