### ISSUE TITLE
PDF Sharp 'FontFamily' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by cricketspike** [GlitchEnzo/NuGetForUnity#366]
## Description
I'm getting an error CS0012: The type 'FontFamily' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

I can make this go away in visual studio with the "add reference" action but this only solves the issue in visual studio, it still shows up in Unity's console
![image](https://user-images.githubusercontent.com/3460556/105089284-c3dfb180-5a51-11eb-8bda-98ba6c4757cb.png)

before:
![image](https://user-images.githubusercontent.com/3460556/105088485-cdb4e500-5a50-11eb-8fb1-daa61635fad2.png)

after:
![image](https://user-images.githubusercontent.com/3460556/105088611-f937cf80-5a50-11eb-833d-80e91f2cd88d.png)

- **NuGet Package:** PdfSharp Version 1.50.5147
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2020.2.1
- **Operating System:** Windows 10

**Comment by nextechar-hardik** [comment]
I am facing same... with no solution , Do you have any solution ?

**Comment by nextechar-hardik** [comment]
This issue is not related to this package... its facing in PDFsharp dll directly as well..

**Comment by JoC0de** [comment]
@nextechar-hardik do you target .net framework or .net standard?
If you use .net framework you need a csc.rsp file see https://docs.unity3d.com/2019.2/Documentation/Manual/dotnetProfileAssemblies.html

**Comment by DennisFleming** [comment]
in the search solution explorer right click on References->Add Reference->Assemblies then select System.Design then Ok.

**Comment by JoC0de** [comment]
@DennisFleming all changes done in the visual studio solution are overwritten by unity on project sync.
