### ISSUE TITLE
Could not download nuget package.

### ISSUE THREAD

**Issue by ghost** [GlitchEnzo/NuGetForUnity#372]
## Description
Could not download nuget package.

I can't download the nuget package for Azure Kinect Body tracking.
When downloading, the following error message is displayed.

`
InvalidDataException: End of Central Directory record could not be found.
System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () (at <893b20abc59547dc8b2fd41a7233777e>:0)
System.IO.Compression.ZipArchive.Init (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen) (at <893b20abc59547dc8b2fd41a7233777e>:0)
System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen, System.Text.Encoding entryNameEncoding) (at <893b20abc59547dc8b2fd41a7233777e>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode, System.Text.Encoding entryNameEncoding) (at <21010871e8cb4079b5e9593dc3e69066>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode) (at <21010871e8cb4079b5e9593dc3e69066>:0)
System.IO.Compression.ZipFile.OpenRead (System.String archiveFileName) (at <21010871e8cb4079b5e9593dc3e69066>:0)
NugetForUnity.NuspecFile.FromNupkgFile (System.String nupkgFilepath) (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetPackage.FromNupkgFile (System.String nupkgFilepath) (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetHelper.GetCachedPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetHelper.GetSpecificPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetHelper.InstallIdentifier (NugetForUnity.NugetPackageIdentifier package, System.Boolean refreshAssets) (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetWindow.DrawPackage (NugetForUnity.NugetPackage package, UnityEngine.GUIStyle packageStyle, UnityEngine.GUIStyle contrastStyle) (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetWindow.DrawPackages (System.Collections.Generic.List 1[T] packages) (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetWindow.DrawOnline () (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
NugetForUnity.NugetWindow.OnGUI () (at <ebb7710be32040ba9a0cb144ce2a8967>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEditor.DockArea.OldOnGUI () (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <06214b245dbb4d10a9cefd10639bb04e>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <fe7ee1881b524b0d9443f74417fb598b>:0)
`

I don't know how to download it.
How do I install the package?

- **NuGet Package:             : Microsoft.Azure.Kinect.BodyTracking 
- **NuGetForUnity Version  : NugetForUnity.3.0.1
- **Unity Version                  : 2019.4.19f1
- **Operating System          : window10 Pro

**Comment by NareshBisht** [comment]
Same here did you found any solution?

**Comment by frenchtouchXR** [comment]
Idem here any solution so far ?

**Comment by frenchtouchXR** [comment]
`InvalidDataException: End of Central Directory record could not be found.
System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () (at <68a672ced0944a04ba38d459de774c77>:0)
System.IO.Compression.ZipArchive.Init (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen) (at <68a672ced0944a04ba38d459de774c77>:0)
System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen, System.Text.Encoding entryNameEncoding) (at <68a672ced0944a04ba38d459de774c77>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode, System.Text.Encoding entryNameEncoding) (at <089834992cd54a2e88ee55b6c467810c>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode) (at <089834992cd54a2e88ee55b6c467810c>:0)
System.IO.Compression.ZipFile.OpenRead (System.String archiveFileName) (at <089834992cd54a2e88ee55b6c467810c>:0)
NugetForUnity.NuspecFile.FromNupkgFile (System.String nupkgFilepath) (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetPackage.FromNupkgFile (System.String nupkgFilepath) (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetHelper.GetCachedPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetHelper.GetSpecificPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetHelper.InstallIdentifier (NugetForUnity.NugetPackageIdentifier package, System.Boolean refreshAssets) (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetWindow.DrawPackage (NugetForUnity.NugetPackage package, UnityEngine.GUIStyle packageStyle, UnityEngine.GUIStyle contrastStyle) (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetWindow.DrawPackages (System.Collections.Generic.List`1[T] packages) (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetWindow.DrawOnline () (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
NugetForUnity.NugetWindow.OnGUI () (at <6a48cd2923ae4ff490cdbdab680b2a59>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <f1711974e43141fb9eefce8d2ce06263>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at <f1711974e43141fb9eefce8d2ce06263>:0)
UnityEditor.DockArea.OldOnGUI () (at <f1711974e43141fb9eefce8d2ce06263>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.IMGUIContainer.ExecuteDefaultActionAtTarget (UnityEngine.UIElements.EventBase evt) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase evt) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <509f2019000744ac9b699b9a91cb11c5>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <e2c04b95794746bc99028bf1000be260>:0)
`

**Comment by lvZic** [comment]
any solution?

**Comment by JoC0de** [comment]
At the time this issue was created this package wasn't actively maintained. So sorry for eventual trouble. Now there are some new active contributors. 

I testet to install Microsoft.Azure.Kinect.BodyTracking it works fine.
The most probably think that could have happen ist that the cached .nupkg file got corrupted. Cache is locate at LocalApplicationData see https://github.com/GlitchEnzo/NuGetForUnity/blob/4493f3a180124f7597a4aee74523d3852b54a11b/src/NuGetForUnity/Editor/NugetHelper.cs#L49-L51
