### ISSUE TITLE
I need the mirror of Nuget but I finded only v3. This plugin is not supporting Nuget v3?

### ISSUE THREAD

**Issue by TheSmileCat** [GlitchEnzo/NuGetForUnity#377]
## Description
Excuse me? 
In a Unity Program, I need a Nuget Plugin (e.g. Newtonsoft.Json). It need a long long time, because I living in China and the international network bandwidth very little (only littler than 15 kb/s). So I need a mirror of Nuget. But I only finded the V3 Mirror.I thinked ... this plugin maybe not supporting Nuget v3 API？
I want to ask that this plugin (NugetForUnity) can be update to Nuget v3?
Thanks! 
![image](https://user-images.githubusercontent.com/53056806/110193538-6a034180-7e6f-11eb-86c0-706fc6537fd2.png)
![image](https://user-images.githubusercontent.com/53056806/110193171-59ea6280-7e6d-11eb-945e-f3b2bb28bd2a.png)

- **NuGet Package:** [Newtonsoft.Json(12.0.3) and more Plugins]
- **NuGetForUnity Version:** [3.0.1]
- **Unity Version:** [2020.1.0f1c1 Personal]
- **Operating System:** [Windows 10 家庭中文版(Chinese language of Home Version) 20H2 19042.804]

**Comment by jwittner** [comment]
This plugin currently only supports the V2 API, the feature request for V3 is #229.
