### ISSUE TITLE
Nuget.org V2 Endpoint Deprecated

### ISSUE THREAD

**Issue by projectcscientist** [GlitchEnzo/NuGetForUnity#378]
## Description
As of 3/9/2021, Nuget.org has deprecated the api/v2 endpoint, resulting in the following error message:

    <m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
    <m:code>NuGet.V2.Deprecated</m:code>
    <m:message xml:lang="en-US">The combination of parameters provided to this OData endpoint is no longer supported. Please refer to the following URL for more information about this deprecation: https://aka.ms/nuget/odata-deprecation</m:message>
    </m:error>

It appears that any FindPackagesById query results in a bad request. Example:
https://www.nuget.org/api/v2/FindPackagesById()?id='System.IdentityModel.Tokens.Jwt'&$orderby=Version asc&$filter=Version eq '6.8.0'

- **NuGet Package:** [Any]
- **NuGetForUnity Version:** [3.0.0]
- **Unity Version:** [2020.1.11f1]
- **Operating System:** [Windows 10]

**Comment by rojah** [comment]
I'm having the same problem, a clean checkout, will result in bad request

**Comment by JimWest** [comment]
Not fixed for me, using v.3.0.1 with Unity 2020.3.2f LTS and got the same issue:

`Unable to retrieve package list from http://www.nuget.org/api/v2/FindPackagesById()?id='System.Numerics.Vectors'&$orderby=Version asc
System.Net.WebException: The remote server returned an error: (400) Bad Request.
  at System.Net.HttpWebRequest+<GetResponseFromData>d__240.MoveNext () [0x00152] in <aa976c2104104b7ca9e1785715722c9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.GetResponse () [0x00013] in <aa976c2104104b7ca9e1785715722c9d>:0 
  at NugetForUnity.NugetHelper.RequestUrl (System.String url, System.String userName, System.String password, System.Nullable`1[T] timeOut) [0x000b9] in <ebb7710be32040ba9a0cb144ce2a8967>:0 
  at NugetForUnity.NugetPackageSource.GetPackagesFromUrl (System.String url, System.String username, System.String password) [0x0006c] in <ebb7710be32040ba9a0cb144ce2a8967>:0 
  at NugetForUnity.NugetPackageSource.FindPackagesById (NugetForUnity.NugetPackageIdentifier package) [0x000ee] in <ebb7710be32040ba9a0cb144ce2a8967>:0 
UnityEngine.Debug:LogErrorFormat (string,object[])
NugetForUnity.NugetPackageSource:FindPackagesById (NugetForUnity.NugetPackageIdentifier)
NugetForUnity.NugetPackageSource:GetSpecificPackage (NugetForUnity.NugetPackageIdentifier)
NugetForUnity.NugetHelper:GetOnlinePackage (NugetForUnity.NugetPackageIdentifier)
NugetForUnity.NugetHelper:GetSpecificPackage (NugetForUnity.NugetPackageIdentifier)
NugetForUnity.NugetHelper:InstallIdentifier (NugetForUnity.NugetPackageIdentifier,bool)
NugetForUnity.NugetHelper:Install (NugetForUnity.NugetPackage,bool)
NugetForUnity.NugetHelper:InstallIdentifier (NugetForUnity.NugetPackageIdentifier,bool)
NugetForUnity.NugetHelper:Install (NugetForUnity.NugetPackage,bool)
NugetForUnity.NugetHelper:InstallIdentifier (NugetForUnity.NugetPackageIdentifier,bool)
NugetForUnity.NugetHelper:Install (NugetForUnity.NugetPackage,bool)
NugetForUnity.NugetHelper:InstallIdentifier (NugetForUnity.NugetPackageIdentifier,bool)
NugetForUnity.NugetHelper:Install (NugetForUnity.NugetPackage,bool)
NugetForUnity.NugetHelper:InstallIdentifier (NugetForUnity.NugetPackageIdentifier,bool)
NugetForUnity.NugetWindow:DrawPackage (NugetForUnity.NugetPackage,UnityEngine.GUIStyle,UnityEngine.GUIStyle)
NugetForUnity.NugetWindow:DrawPackages (System.Collections.Generic.List`1<NugetForUnity.NugetPackage>)
NugetForUnity.NugetWindow:DrawOnline ()
NugetForUnity.NugetWindow:OnGUI ()
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

**Comment by jwittner** [comment]
@JimWest - the fix is into the source code, but there's no release yet. Were you testing the release or with the source? Waiting on some more testing/reviews of #385, planning for a release on Monday.
