### ISSUE TITLE
Can't install System.ServiceModel.Http

### ISSUE THREAD

**Issue by Oneiros90** [GlitchEnzo/NuGetForUnity#381]
Nuget find the package, but when clicking install, nothing happens

- **NuGet Package:** [System.ServiceModel.Http](https://www.nuget.org/packages/System.ServiceModel.Http)
- **NuGetForUnity Version:** 3.0.1
- **Unity Version:** Unity 2020.2.4f1
- **Operating System:** Windows 10

**Comment by mikejurka** [comment]
Seeing the same issue for `System.Numerics.Vectors` v4.5.0
Unity 2020.1.17f1

**Comment by jwittner** [comment]
This package is not installed because Unity already include the assembly. If you have any problems accessing the API in Unity code please let me know the Player Configuration settings that are resulting in this.
