### ISSUE TITLE
Unclear outcome for Unity's embedded packages.

### ISSUE THREAD

**Issue by jwittner** [GlitchEnzo/NuGetForUnity#388]
## Description
It's very unclear without verbose logging enabled that packages which are already included with Unity are ignored by NugetForUnity. 

Recommendations:

* Log that they were passed even without verbose enabled
* Update the UI to detect these packages and replace the 'Install' button with 'Embedded' or something similar.

**Comment by JoC0de** [comment]
fixed by #539
