### ISSUE TITLE
Version conflicts

### ISSUE THREAD

**Issue by benoitdion** [GlitchEnzo/NuGetForUnity#391]
What is the recommended way to deal with conflicts with transitive version requirements? With a regular dot net project, you'd use assembly binding resolution but with Unity and Nuget for Unity I haven't been able to find a satisfactory answer.

**Comment by benaadams** [comment]
Untick the "Assembly Version Validation" in Project Settings -> Player? 😅

![image](https://user-images.githubusercontent.com/1142958/121667813-92b85a00-caa2-11eb-805a-a2b1ef2fe7e5.png)
