### ISSUE TITLE
Conflict with existing folders under Assets/Packages

### ISSUE THREAD

**Issue by nobnak** [GlitchEnzo/NuGetForUnity#392]
## Description
Similar issue to #344. If my project already has my own packages under Assets/Packages folder or packages installed by UPM (which also uses Packages folder), NugetForUnity tries to read .nupkg files from them.

Package could not be read: xxxx\Assets\Packages\xxxx\xxxx.nupkg
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NuspecFile:FromNupkgFile(String)
NugetForUnity.NugetPackage:FromNupkgFile(String)
NugetForUnity.NugetHelper:CheckForUnnecessaryPackages()
NugetForUnity.NugetHelper:Restore()
NugetForUnity.NugetHelper:.cctor()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])

- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2019.4
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
Just to clarify - UPM uses a Packages folder that lives next to Assets, not within it. N4U is currently assuming it owns the contents of the Assets/Packages folder, is it possible for you to move your non N4U content under a different folder?

Open to a PR that makes the default install folder configurable within the preferences. =)

**Comment by jwittner** [comment]
Ah, I see from the other bug that some packages are installing things in this folder. If UPM is actually depending on this folder we should probably move to something else. At the very least we should make it configurable.
