### ISSUE TITLE
Package installs correctly but cannot be found when compiling.

### ISSUE THREAD

**Issue by NullandKale** [GlitchEnzo/NuGetForUnity#398]
## Description
I am attempting to test out this [library](https://github.com/m4rs-mt/ILGPU/) and the packages install correctly but ILGPU does not work. I tested a few other nuget packages and they install correctly. I am pretty familiar with ILGPU and am kinda surprised it doesnt work, I don't believe it does anything special.

[It probably wont help but the project is hosted here](https://github.com/NullandKale/ILGPUUnityTest)

![image](https://user-images.githubusercontent.com/13143533/119439997-55994d00-bcd8-11eb-810c-cb215fb19f4d.png)

- **NuGet Package:** ILGPU and ILGPU.Algorithms 
- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2021.1.7f1
- **Operating System:** Windows 10

**Comment by JoC0de** [comment]
At the time this issue was created this package wasn't actively maintained. So sorry for eventual trouble. Now there are some new active contributors. 
I testet installing and using ILGPU using the newest version of NuGetForUnity and I everything works fine.
