### ISSUE TITLE
Unloading Broken Assembly error + Timing Out

### ISSUE THREAD

**Issue by MaxwellDexter** [GlitchEnzo/NuGetForUnity#400]
## Description
I have a few AWS-related packages installed (among others) and unity throws these errors every time on project startup.
```
Unloading broken assembly Assets/Packages/AWSSDK.SecurityToken.3.7.1.5/analyzers/dotnet/cs/AWSSDK.SecurityToken.CodeAnalysis.dll, this assembly can cause crashes in the runtime
Unloading broken assembly Assets/Packages/AWSSDK.CognitoIdentity.3.7.0.2/analyzers/dotnet/cs/AWSSDK.CognitoIdentity.CodeAnalysis.dll, this assembly can cause crashes in the runtime
Unloading broken assembly Assets/Packages/AWSSDK.CognitoIdentity.3.7.0.2/analyzers/dotnet/cs/AWSSDK.CognitoIdentity.CodeAnalysis.dll, this assembly can cause crashes in the runtime
```
Which doesn't really affect much, but when setting up Unity Play Mode tests, I get this error thrown:
```
ArgumentException: The Assembly Microsoft.CodeAnalysis is referenced by AWSSDK.CognitoIdentityProvider.CodeAnalysis ('Assets/Packages/AWSSDK.CognitoIdentityProvider.3.7.0.2/analyzers/dotnet/cs/AWSSDK.CognitoIdentityProvider.CodeAnalysis.dll'). But the dll is not allowed to be included or could not be found.
```
Which is perhaps why it's breaking, but trying to install Microsoft.CodeAnalysis or it's sub-packages yields: 
```
Unable to retrieve package list from http://www.nuget.org/api/v2/GetUpdates()?packageIds='AWSSDK.CognitoIdentity|AWSSDK.CognitoIdentityProvider|AWSSDK.Core|AWSSDK.SecurityToken|Amazon.Extensions.CognitoAuthentication|Csv|CsvHelper|Google.Apis|Google.Apis.Auth|Google.Apis.Core'&versions='3.7.0.2|3.7.0.2|3.7.0.17|3.7.1.5|2.2.1|2.0.62|19.0.0|1.49.0|1.49.0|1.49.0'&includePrerelease=false&includeAllVersions=false&targetFrameworks=''&versionConstraints=''
System.Net.WebException: The request timed out
```
What should I do in this situation? I'm not certain that these are breaking my play mode tests but I'd prefer to rule out stuff if I can.
Thanks very much :)

- **NuGet Package:** AWSSDK.CognitoIdentityProvider
- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2019.3.14f1

**Comment by MaxwellDexter** [comment]
bump, anybody know?

**Comment by jwittner** [comment]
Thanks for the bump. To be honest I'm not quite clear on how unity decides if an assembly is broken / going to crash the runtime. Though I've seen it reported here and there. Any information on that would be much appreciated.

I'll try to make a run at installing these and seeing what I get asap.

**Comment by MaxwellDexter** [comment]
awesome thanks so much!

**Comment by JoC0de** [comment]
analyzers support is added in 3.1.0 so this can't happen any more.
