### ISSUE TITLE
[Feature] Give user better feedback when user try to install a library already installed in the engine

### ISSUE THREAD

**Issue by Enough7** [GlitchEnzo/NuGetForUnity#403]
## Description
Try download `System.Security.Cryptography.Pkcs`. This library is already installed in the engine, but the button shows still install, when it should show something like "already installed, can't uninstall because it is installed in the engine".

- **NuGet Package:** `System.Security.Cryptography.Pkcs`
- **NuGetForUnity Version:** Latest
- **Unity Version:** 2019.4.2f1
- **Operating System:** Win 10 (pro)

**Comment by JoC0de** [comment]
fixed by #539
