### ISSUE TITLE
Google Api Package can't find NewtonSoft.Json installed via UPM

### ISSUE THREAD

**Issue by MaxwellDexter** [GlitchEnzo/NuGetForUnity#408]
## Description
I'm trying to run tests on a local docker instance (linux) using [Game-CI](https://github.com/game-ci/unity-test-runner), but I'm running into errors with some packages installed through NuGetForUnity. When running unity via the command line (docker) it spits this out:
```
Begin MonoManager ReloadAssembly
Error: Could not load signature of Google.Apis.Auth.SignedTokenVerification:GetCertificatesAsync due to: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:(null) signature:<none>
(Filename: ./Runtime/Mono/MonoAttributeHelpers.cpp Line: 385)

Unloading broken assembly Assets/Packages/AWSSDK.CognitoIdentity.3.7.0.2/analyzers/dotnet/cs/AWSSDK.CognitoIdentity.CodeAnalysis.dll, this assembly can cause crashes in the runtime
(Filename: ./Runtime/Mono/MonoManager.cpp Line: 1182)

Unloading broken assembly Assets/Packages/AWSSDK.SecurityToken.3.7.1.5/analyzers/dotnet/cs/AWSSDK.SecurityToken.CodeAnalysis.dll, this assembly can cause crashes in the runtime
(Filename: ./Runtime/Mono/MonoManager.cpp Line: 1182)

Unloading broken assembly Assets/Packages/Google.Apis.Core.1.49.0/lib/net45/Google.Apis.Core.dll, this assembly can cause crashes in the runtime
(Filename: ./Runtime/Mono/MonoManager.cpp Line: 1182)

Unloading broken assembly Assets/Packages/AWSSDK.CognitoIdentityProvider.3.7.0.2/analyzers/dotnet/cs/AWSSDK.CognitoIdentityProvider.CodeAnalysis.dll, this assembly can cause crashes in the runtime
(Filename: ./Runtime/Mono/MonoManager.cpp Line: 1182)

Unloading broken assembly Assets/Packages/Google.Apis.Auth.1.49.0/lib/net45/Google.Apis.Auth.dll, this assembly can cause crashes in the runtime
(Filename: ./Runtime/Mono/MonoManager.cpp Line: 1182)

Native extension for LinuxStandalone target not found
Refreshing native plugins compatible for Editor in 3.33 ms, found 1 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
DisplayProgressbar: Restoring NuGet Packages
Refresh completed in 0.000003 seconds.
Mono: successfully reloaded assembly
- Completed reload, in  1.481 seconds
Platform modules already initialized, skipping
[ScriptCompilation] Recompiling all scripts because: Reload of assemblies failed, assemblies are invalid or forced recompiled
- Starting script compilation
```

And there's a lot to digest here but I'm just starting with the first thing. This `Google.Apis.Auth` package can't find the NewtonSoft Json package. 
We have the [JsonForUnity](https://github.com/jilleJr/Newtonsoft.Json-for-Unity) package installed via UPM so would I need to link it somehow? Is this a red herring and should be fine? Is that causing the subsequent `Unloading broken assembly` errors?

- **NuGet Package:** Google.Apis.Auth
- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2019.3.14f1
- **Operating System:** Linux VM

### some more context

- The error with `Google.Apis.Auth` doesn't show up as an error in the console log in Unity (mac/windows), but the `Unloading broken assembly` errors do.
- I have an issue open about the `Unloading broken assembly` errors here: https://github.com/GlitchEnzo/NuGetForUnity/issues/400
- After the code snippet above it then tries to import every assembly but they all have super broken references, like they can't even find UnityEngine.UI. Which you don't usually have to include as a dependency so I think something is breaking it.

**Comment by JoC0de** [comment]
At the time this issue was created this package wasn't actively maintained. So sorry for eventual trouble. What has changed. Need to close this issue as it old and everything that could have been problematic is changed in newer versions of NuGetForUnity. We even have a command line tool to install NuGet packages in a CI/CD environment to prevent issues like this.
