### ISSUE TITLE
package version selection

### ISSUE THREAD

**Issue by giorgi-abashidze** [GlitchEnzo/NuGetForUnity#409]
please add package version selection when installing package

**Comment by JoC0de** [comment]
With #549 we can now add support for this. As API v3 has support for this.

**Comment by kekchpek** [comment]
Do I understand correctly, that there is no way to get 3.1.4-alpha version to start using this feature?

**Comment by JoC0de** [comment]
You can install it either as a git dependency https://docs.unity3d.com/Manual/upm-git.html#revision
Or download the .unitypackae https://github.com/GlitchEnzo/NuGetForUnity/suites/15660198815/artifacts/893906981
