### ISSUE TITLE
Microsoft.CodeAnalysis.Analyzers.3.3.2  Error!

### ISSUE THREAD

**Issue by yimengfan** [GlitchEnzo/NuGetForUnity#410]
## Description
[Describe the issue you have.]

- **NuGet Package:Microsoft.CodeAnalysis.Analyzers.3.3.2** 
- **NuGetForUnity Version:3.0.2**
- **Unity Version:2019.4.25** 
- **Operating System: Win10** 

install.ps1 not work! And  some unuse dll imported in unity3d will error!

**Comment by RichLogan** [comment]
I think I might be facing this too. I'm using the AWS SDK which depends on `Microsoft.CodeAnalysis` but I get `FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

If I try and install the dependency directly it conflicts with an existing one. Any ideas?

**Comment by nRamstedt** [comment]
> I think I might be facing this too. I'm using the AWS SDK which depends on `Microsoft.CodeAnalysis` but I get `FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`
> 
> If I try and install the dependency directly it conflicts with an existing one. Any ideas?

I'm having same issue, solved by copy-pasting required code analyzer dll's from [Unity-Roslyn](https://github.com/mwahnish/Unity-Roslyn) (which i found [from unity docs](https://docs.unity3d.com/2020.3/Documentation/Manual/roslyn-analyzers.html?_gl=1*17ho3xs*_ga*NDA2Njg5MTA4LjE2MTAxMTI4NjI.*_ga_1S78EFL1W5*MTYyOTM2NjI1OC45My4wLjE2MjkzNjYyNTguNjA.&_ga=2.51748460.457236480.1629358299-406689108.1610112862)). 

Not pretty but works... I also tried to disable the CodeAnalysis.dll for every package through unity inspector but the changes does not presist when you start a new project or re-download dependencies. Best option would be to exclude certain files from NuGet Packages but had no luck for that either.

#400

**Comment by LangInteger** [comment]
> > I think I might be facing this too. I'm using the AWS SDK which depends on `Microsoft.CodeAnalysis` but I get `FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`
> > If I try and install the dependency directly it conflicts with an existing one. Any ideas?
> 
> I'm having same issue, solved by copy-pasting required code analyzer dll's from [Unity-Roslyn](https://github.com/mwahnish/Unity-Roslyn) (which i found [from a unity docs reference](https://docs.unity3d.com/2020.3/Documentation/Manual/roslyn-analyzers.html?_gl=1*17ho3xs*_ga*NDA2Njg5MTA4LjE2MTAxMTI4NjI.*_ga_1S78EFL1W5*MTYyOTM2NjI1OC45My4wLjE2MjkzNjYyNTguNjA.&_ga=2.51748460.457236480.1629358299-406689108.1610112862)).
> 
> Not pretty but works... I also tried to disable the CodeAnalysis.dll for every package through unity inspector but the changes does not presist when you start a new project or re-download dependencies. Best option would be to exclude certain files from NuGet Packages but had no luck for that either.
> 
> #400

![image](https://user-images.githubusercontent.com/17768055/202962841-dedf875f-2fcd-4a0c-877f-f2761bb99cd5.png)

In addition to @nRamstedt 's, I have to download all these Dlls from [Unity-Roslyn](https://github.com/mwahnish/Unity-Roslyn) to make my code work.

**Comment by JoC0de** [comment]
Roslyn analyzers are handled correctly since 3.1.0 (marked as analyzers so even unity can understand them)
