### ISSUE TITLE
Move `NuGet` directory into Assets/Plugins

### ISSUE THREAD

**Issue by pixelpax** [GlitchEnzo/NuGetForUnity#411]
## Description
Since installing  NuGetForUnity my editor has been slowing down a ton whenever I have to reload a script (probably from 1-2 seconds to 15 seconds or so). My [understanding ](https://gamejolt.com/p/tales-of-kulplex-devlog-6-attempting-to-decrease-compile-times-she9y7qf)is that Unity will avoid recompiling slow-changing code/external dependencies when they're in the `Plugins` directory. 

Any way I could change NuGetForUnity's path? 

- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2020.3.13f1
- **Operating System:** Windows 10

**Comment by jwittner** [comment]
It's unusual that N4U itself would be recompiling - if you install it with the unitypackage from the Releases page it should be compiled as a dll already. Others have reported seeing some slow down in the processing of packages (a recompile does cause a restore operation in N4U) though.

Can you lay out what packages you've installed with N4U and I can try to reproduce?

**Comment by pixelpax** [comment]
Sure, thanks for your response!

The only package I've installed is NSubstitute and it's dependencies:

```
Castle.Core 4.40
Microsoft.NETCore.Platforms 1.1.0
NETStandard.Librarv 1.61
System.Threading.Tasks.Exten 4.3.0
NSubstitute 4.2.2
```

**Comment by pixelpax** [comment]
For a bit of added information, I tried (as a dumb experiment) moving `NuGet` into `Assets/Plugins` along with the .asmdefs, and this did immediately speed up the recompilation (while totally breaking the references to NuGet packages in my Tests, of course)

**Comment by pixelpax** [comment]
![image](https://user-images.githubusercontent.com/1467013/129433065-a9bba9d9-7a08-4c3d-b62c-42702e4acebc.png)

It does seem like NuGetForUnity.dll is taking up a significant part of assembly reload, but for some reason my assembly is reloading on actions where it shouldn't like moving gameobjects within the editor, so it's impact might be exaggerated here.
