### ISSUE TITLE
Restoring in CI pipeline

### ISSUE THREAD

**Issue by denravonska** [GlitchEnzo/NuGetForUnity#414]
## Description
I'm trying to implement a build pipeline for a project which uses NuGetForUnity and Docker. As an initial step I want to install dependencies, following the command from the readme:

> unity-editor -batchmode -projectPath /src -executeMethod NugetForUnity.NugetHelper.Restore

However, this seems to try to build my project which fails due to missing dependencies. Nothing in the logs shows that NuGetForUnity is invoked. Is there something I'm missing?

- **NuGet Package:** N/A
- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2020.3.17f1
- **Operating System:** Linux in Docker

**Comment by jwittner** [comment]
We've had good luck with a two pass build method. Start up Unity once, lets N4U restore things, shut down. Then run again and do a real build and check for errors there.

We've had lots of trouble getting Unity to work well in Windows containers, would be cool to hear if you're successful on Linux.

**Comment by denravonska** [comment]
Here's what I've found. If I run the command locally in a checkout where the library has been built once it works, even just by doing `unity-editor -batchmode -quit` like you suggested. If I remove the `Library/` folder I get the same problem as in our pipeline where Unity tries to rebuild the library, failing due to compile errors and then aborts. So it never reaches the package restore.

**Comment by denravonska** [comment]
I ended up using regular nuget with a cleanup step. A bit more clunky but it got the job done.

**Comment by jwittner** [comment]
> Here's what I've found. If I run the command locally in a checkout where the library has been built once it works, even just by doing `unity-editor -batchmode -quit` like you suggested. If I remove the `Library/` and `Temp/` folders I get the same problem as in our pipeline where Unity tries to rebuild the library, failing due to compile errors and then aborts. So it never reaches the package restore.

That's interesting. If you're using the package you should have a dll for NugetForUnity and so the restore should happen even if there are build errors. Perhaps that's not true in newer versions of Unity, e.g. the ones with 'safe mode'? This behavior, where it continues to initialize assemblies even if other code fails to compile is a big reason we build the rather than shipping as code (this was before assembly defs existed of course).

**Comment by Strepto** [comment]
Try adding the `-ignoreCompilerError` flag to disable safe mode. 

`unity-editor -batchmode -ignoreCompilerError -projectPath /src -executeMethod NugetForUnity.NugetHelper.Restore`

**Comment by denravonska** [comment]
> Try adding the `-ignoreCompilerError` flag to disable safe mode. See the very last text on this page: https://docs.unity3d.com/2020.2/Documentation/Manual/SafeMode.html . Its not listed on the standard ["CommandLineArguments" docs](https://docs.unity3d.com/Manual/CommandLineArguments.html) anywhere, so its kinda hard to find.
> 
> `unity-editor -batchmode -ignoreCompilerError -projectPath /src -executeMethod NugetForUnity.NugetHelper.Restore`

Oh, there's an undocumented flag? I have it running through manual nuget now but I'll try that next week if I can remember.

**Comment by NoTuxNoBux** [comment]
Just wanted to mention that it's `-ignoreCompilerErrors` **with** a trailing `s` according to the documentation. This makes a difference, the one without `s` doesn't do anything :smile:.

**Comment by JoC0de** [comment]
I finally released the CLI for restoring packages before starting Unity Editor [NuGetForUnity.Cli](https://www.nuget.org/packages/NuGetForUnity.Cli).
