### ISSUE TITLE
Cannot run the downloaded package because the downloaded dependencies version mismatched the requirement

### ISSUE THREAD

**Issue by conghoacntt13t1** [GlitchEnzo/NuGetForUnity#415]
## Description
In some package requires dependencies to run, NuGetForUnity auto download all required dependencies, but in wrong version (seems to be the latest version), causing them unable to be loaded. Please fix that issues

- **NuGet Package:** Microsoft.AspNetCore.SignalR.Client
- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2020.3.3f1
- **Operating System:** Windows 10 x64

**Comment by SamNChiet** [comment]
I'm getting this too. There's a "Show All Versions" checkbox at the top of the UI which doesn't appear to do anything.

As a workaround, I was able to manually edit the version number for the necessary packages in the packages.config file, then delete the folder containing the (incorrect) package and BOOM! It restored to the right version.
![image](https://user-images.githubusercontent.com/34078563/137835792-7f8f9270-7c4c-42b5-8264-01c4910ae414.png)

Maybe there's an easy way to add this as a feature, I haven't looked at the source yet.

**Comment by SamNChiet** [comment]
Ehhhhh alright. it's breaking all over the place again. Wack.
![image](https://user-images.githubusercontent.com/34078563/137836947-87367d25-1630-4d0a-8f81-f0130944aaeb.png)

**Comment by LocalJoost** [comment]
Almost 2.5 years down the road, and this problem still seems to be occurring. Why isn't is possible to download the correct dependencies? It seems to be downloading the latest version of everything, and then (of course) everything breaks.

**Comment by JoC0de** [comment]
@LocalJoost are you sure you are using the last version of NuGetForUnity (3.1.0)? And then you try to install Microsoft.AspNetCore.SignalR.Client? And what do you mean by braking? When you get a incorrect dependency version warning from unity you can just disable version checking using a setting in Unity. When multiple packages reference the same package in multiple versions it is not always possible to find a common version.

**Comment by LocalJoost** [comment]
No, I am installing a different package, just didn't want to open an new issue if there is a similar open issue. I was also wondering why "show all versions" didn't work (it says so in the documentation) while the package manager in Visual Studio seems to be able to do that. I didn't want to diss your work, was just wondering if this still had your attention 😊

**Comment by JoC0de** [comment]
The "Show All Versions" button is to be able to install preview versions of packages.
But I still don't understand what exactly is the problem, the author of the issue never showed what error he is getting.

**Comment by LocalJoost** [comment]
Okay, two separate issues I have here:
- I installed Microsoft.ML in Unity 2021.3.16f1. This pulls in a host of other packages, and in the end results is a version conflict. This may or may not be an issue cause my NuGet for Unity
- When I try to downgrade one of the packages (Google.ProtoBuf) and click "show all versions" nothing seems to happen.
- When I try to be a clever **** and try to change the version number in packages.config using a text editor, then hit restore, I get an error message indicating the desired package version cannot be found, although it clearly exists.

I had installed 3.1.0. The documentation clearly states:

> Enable Show All Versions to list all old versions of a package **(doesn't work with nuget.org).** Disable Show All Versions to only show the latest version of a package.

Emphasis mine.

**Comment by JoC0de** [comment]
Sry I'm always confused with "Show All Versions" and "Show Prerelease".
In the UI you can only install the latest version, there is a separate issue to add this feature. 
As I mentioned some packages have cyclic dependencies in a way that not all packages can't be installed in the correct version. For normal C#-Projects NuGet just ignores the conflict but unity does a additional version validation. You can just disable the version compatibility, check see: https://docs.unity3d.com/ScriptReference/PlayerSettings-assemblyVersionValidation.html (i couldn't find a documentation witch shows how to change the setting in UI but it should be possible), to get the same behavior inside Unity.

**Comment by JoC0de** [comment]
It is now in the mentioned in the README
