### ISSUE TITLE
Error: IOException: Attempted to Seek before the beginning of the stream

### ISSUE THREAD

**Issue by zhimin-wang** [GlitchEnzo/NuGetForUnity#416]
## Describe the bug
In Unity, I used the NuGet to install the Microsoft.Windows.MixedReality.DotNetWinRT, and the error happened. However, I used the NuGet to install other package such as Microsoft.MixedReality.QR and no error happened.

## To reproduce

1. Create Unity Project.
2. Import MRTK.
3. Import NuGet.
4. Search Microsoft.Windows.MixedReality.DotNetWinRT.
5. See error

## Expected behavior

Install the Microsoft.Windows.MixedReality.DotNetWinRT sucessfully.

## Screenshots

![image](https://user-images.githubusercontent.com/24918185/134692891-8e985ddc-6ce7-4a35-9de5-19c3f61a3939.png)

## Your setup (please complete the following information)

- Windows 10
- Unity Version [2020.3.11f1]
- MRTK Version [2.7.2.0]
- NuGet Version [3.0.2]
- Microsoft.Windows.MixedReality.DotNetWinRT Version [0.5.1049]

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

IOException: Attempted to Seek before the beginning of the stream
System.IO.FileStream.Seek (System.Int64 offset, System.IO.SeekOrigin origin) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () (at <893b20abc59547dc8b2fd41a7233777e>:0)
Rethrow as InvalidDataException: Central Directory corrupt.
System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () (at <893b20abc59547dc8b2fd41a7233777e>:0)
System.IO.Compression.ZipArchive.Init (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen) (at <893b20abc59547dc8b2fd41a7233777e>:0)
System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen, System.Text.Encoding entryNameEncoding) (at <893b20abc59547dc8b2fd41a7233777e>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode, System.Text.Encoding entryNameEncoding) (at <21010871e8cb4079b5e9593dc3e69066>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode) (at <21010871e8cb4079b5e9593dc3e69066>:0)
System.IO.Compression.ZipFile.OpenRead (System.String archiveFileName) (at <21010871e8cb4079b5e9593dc3e69066>:0)
NugetForUnity.NuspecFile.FromNupkgFile (System.String nupkgFilepath) (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetPackage.FromNupkgFile (System.String nupkgFilepath) (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetHelper.GetCachedPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetHelper.GetSpecificPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetHelper.InstallIdentifier (NugetForUnity.NugetPackageIdentifier package, System.Boolean refreshAssets) (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetWindow.DrawPackage (NugetForUnity.NugetPackage package, UnityEngine.GUIStyle packageStyle, UnityEngine.GUIStyle contrastStyle) (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetWindow.DrawPackages (System.Collections.Generic.List`1[T] packages) (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetWindow.DrawOnline () (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
NugetForUnity.NugetWindow.OnGUI () (at <ee6cbe4822d046d98553a66d7fbaadcd>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <0b8db76a688c4d18a15dd7dfe092a035>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <0b8db76a688c4d18a15dd7dfe092a035>:0)
UnityEditor.DockArea.OldOnGUI () (at <0b8db76a688c4d18a15dd7dfe092a035>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <0dab12d45c2a4edc933579280843bdeb>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <6ddf8eac3856492ab1b8cf42618915cc>:0)

**Comment by denravonska** [comment]
Mine started doing this as well. It won't install packages or refresh the package lists.

**Comment by JoC0de** [comment]
I testet to install Microsoft.Windows.MixedReality.DotNetWinRT 0.5.1049 it works fine.
The most probably think that could have happen ist that the cached .nupkg file got corrupted. Cache is locate at LocalApplicationData see https://github.com/GlitchEnzo/NuGetForUnity/blob/master/src/NuGetForUnity/Editor/NugetHelper.cs#L49-L51
