### ISSUE TITLE
The files in the "Project" window are too fragmented and cannot be moved outside the root directory (affecting functionality)

### ISSUE THREAD

**Issue by lb-chc** [GlitchEnzo/NuGetForUnity#418]
## Description
[Describe the issue you have.]

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
- 
- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
- Version 0.9.6
- **Unity Version:** [What version of Unity are you using?]
- 2020.3.18f1
- **Operating System:** [What OS are you on?]
- macOS
<img width="182" alt="屏幕快照 2021-10-01 下午3 10 33" src="https://user-images.githubusercontent.com/69136546/135580001-164479bd-8feb-41d6-aeab-350cba4d8ba5.png">
<img width="223" alt="屏幕快照 2021-10-01 下午3 11 11" src="https://user-images.githubusercontent.com/69136546/135580007-56a1a2ae-7173-4029-8b1f-473936cc54bf.png">

**Comment by JoC0de** [comment]
This is by designe Unity requires the NuGet Packages need to be installed into the Assets folder.
