### ISSUE TITLE
Package ILGPU not unpacked

### ISSUE THREAD

**Issue by CryptoCashCashoo** [GlitchEnzo/NuGetForUnity#425]
## Description
The package ILGPU is available in the searcher, and have a support for Net5 (or at least the devs say so). 
Inside the ILGPU nupkg -> lib -> there are two files, one for net4 , and another that might be compatible with net5: "netstandard2.1"

Issue: after downloading the package, it seems that there's no lib, nor code... 

- **NuGet Package:** 
ILGPU version 0.10.1
- **NuGetForUnity Version:** 
3.02
- **Unity Version:** 
2021.1.11f1
- **Operating System:** Linux -> Ubuntu -> 20.04 -> (Focal Fossa)

**Comment by JoC0de** [comment]
Sorry for the delay the package was not actively maintained in the year 2021.
I just testet installing ILGPU in Unity 2021 but there was no issue. Probably there was a issue that is already solved in the latest NuGetForUnity version. If the issue still exists pleas enable verbose logs and post them here.
