### ISSUE TITLE
Is it possible to disable the package auto-restore?

### ISSUE THREAD

**Issue by AVAVT** [GlitchEnzo/NuGetForUnity#427]
## Description

Hello, our project is getting bigger, and NuGet package restore is taking a big chunk of our time.

Splitting codebase into several assemblies helped reducing recompile time significantly, but we're stuck with 1~2min of NuGet package restore every time we make the smallest change to our code.

Is it possible to disable the auto-restore feature and opt to manual-restore only instead?

- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2020.1.17
- **Operating System:** Windows

**Comment by JoC0de** [comment]
Hi are there still problems with performance? There are some changes that should resolved the "always restore if something changed" in version 3.0.5 and in 3.1.0 there are some changes that should have improved the package restore performance.
