### ISSUE TITLE
Package Dependency downloaded is the wrong according to target framework.

### ISSUE THREAD

**Issue by Merichbier** [GlitchEnzo/NuGetForUnity#430]
## Description
We are developing a UWP app and have the project set to target .NET standard 2.0 framwork. When using NugetForUnity to install a package, it downloads the wrong dependencies.

Moreover, we tried to force .NET standard framework by adding the tag `targetFramework="netstandard2.0"` in the package.config file, but NugetForUnity always override it and remove this tags.

Has you can see on Nuget, the dependency of `SQLitePCLRaw.bundle_e_sqlcipher` should be `SQLitePCLRaw.provider.e_sqlcipher` and not `SQLitePCLRaw.provider.dynamic_cdecl`.

![unity-target-framework](https://user-images.githubusercontent.com/9365869/145019625-8755b487-d854-4dbd-a9dc-dc43e4a7fade.PNG)
![sql-net-sqlcipher-nugetforunity-dependencies-tree](https://user-images.githubusercontent.com/9365869/145018374-66481e8c-c4ed-402a-a526-ed4ed7eeace8.PNG)
![nuget-package-dependencies](https://user-images.githubusercontent.com/9365869/145019226-b856450c-48e1-45b7-bebc-290e48060108.PNG)

- **NuGet Package:** 
1.  sqlite-net-sqlcipher - version="1.8.116"

- **NuGetForUnity Version:** 
3.0.3

- **Unity Version:** 
2020.3.22f1

- **Operating System:** 
Windows 10, build 19042.1348

**Comment by JoC0de** [comment]
Sorry for the delay.
At least in the latest version of NuGetForUnity it works correctly:
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/53140583/142d93e7-ade1-498c-ae5f-325f2c990794)
