### ISSUE TITLE
NuGet package is not recognized after downloading

### ISSUE THREAD

**Issue by justin-omnivor** [GlitchEnzo/NuGetForUnity#433]
## Description
After installing a NuGet package Unity is unable to resolve `using` directives that should be resolved by the package.

## Steps to reproduce
1. Create a new Unity project
2. Import the NuGetForUnity unitypackage using Unity's Assets/Import Package/Custom Package...
3. Create a new script and add `using uPLibrary.Networking.M2Mqtt;` to the file

## Results
- Unity produces the following error:
  ```
  The type or namespace name 'uPLibrary' could not be found (are you missing a using directive or an assembly reference?)
  ```
- In `Assets/Packages` I can see a folder, `M2Mqtt.4.3.0.0`, which contains an empty `lib` folder as well as a `.nupkg` file.

## Other Info

- **NuGet Package:** M2Mqtt version 4.3.0.0
- **NuGetForUnity Version:** 3.0.3
- **Unity Version:** 2020.3.19f1
- **Operating System:** Windows 10

**Comment by ayyobro** [comment]
👍 , I am getting the same issue installing the `TeamDev.Redis.Client` package as well.

Hope someone can help us out!!

### Other Info

- NuGet Package: TeamDev.Redis.Client v1.0.4
- NuGetForUnity Version: 3.0.3
- Unity Version: 2020.3.27f1
- Operating System: Windows 10 Pro

**Comment by jwittner** [comment]
@justin-omnivor - your repro steps don't include installing the necessary package via NugetForUnity (N4U(). Did you leave that out or are you expecting N4U to auto install the missing package like how Visual Studio can?

If the latter then this would be a feature request and not something trivially implemented in N4U as we'd have to do code analysis to understand what was missing and resolve type names to packages.

**Comment by rainbowdesign** [comment]
Hey, i have the same question or feature request:

I use nuget to install raylib-cs i have now a folder packages/raylib-cs it contains a nuget file but no cs files and it does not seem to be included into visual studio.

How can i use using raylib-cs now?

**Comment by swifter87** [comment]
Same here, its not working!  I see only the .nupkg file inside the Assets/Packages folder

**Comment by JoC0de** [comment]
I will close the issue as the initial issue (from @justin-omnivor) is just related to a misuse of NuGetForUnity. 
@rainbowdesign and @swifter87 pleas create own issues with more details, I don't understand what's the exact problem you are having.
