### ISSUE TITLE
Add option to disable auto restore in Gui (should not be stored in PlayerPrefs, but needs to be stored somewhere else e.g. editor resource folder

### ISSUE THREAD

**Issue by studentutu** [GlitchEnzo/NuGetForUnity#435]
## Description
We have an issue with CI - it tries to restore packages, even if they are already inside the project, which causes recompilation and even re-import of the assets.

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
Grpc.Core
Grpc.Api
- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]

3.0.3 ( latest) 
- **Unity Version:** [What version of Unity are you using?]
2020.3.16.f1
- **Operating System:** [What OS are you on?]
Linux

**Comment by JoC0de** [comment]
Hi are there still problems with performance? There are some changes that should resolved the "always restore if something changed" in version 3.0.5 and in 3.1.0 there are some changes that should have improved the package restore performance.
