### ISSUE TITLE
Can NuGetForUnity be installed as a package via PackageManager?

### ISSUE THREAD

**Issue by DaveXR** [GlitchEnzo/NuGetForUnity#436]
## Seems like this is a prime candidate for installation via Package Manager

- **NuGet Package:** NuGetForUnity
- **NuGetForUnity Version:** current
- **Unity Version:** 2020 LTS
- **Operating System:** Windows

I can install this to my Unity project by downloading and using Assets/Import Package... just fine. I'd rather use the Package Manager to Install from Git URL. Are there any plans for that?

**Comment by robin-moss** [comment]
The repo does not support that no, only the `unitypackage` option

**Comment by mcmikecreations** [comment]
> The repo does not support that no, only the `unitypackage` option

Is support for this planned for a future release?
