### ISSUE TITLE
Attempting to install HTMLAgilityPack gives: Unable to retrieve package.  - http://www.nuget.org/api/v2/Packages is depeceated.

### ISSUE THREAD

**Issue by Mowtine** [GlitchEnzo/NuGetForUnity#437]
## Description
Attempting to install HTMLAgilityPack gives: Unable to retrieve package.  Manually navigating to:
http://www.nuget.org/api/v2/Packages gives a depreciated error.  Is this something that the package authors need to fix or to do with NuGetForUnity? 

![image](https://user-images.githubusercontent.com/11579805/154396100-7871a3a5-9d25-4864-9e7e-635ddfbcedca.png)

- **NuGet Package:** HTMLAgilityPack 1.11.42
- **NuGetForUnity Version:** 3.0.3
- **Unity Version:** 2020.3.22f1
- **Operating System:** Windows 10

**Comment by mls-sergio** [comment]
I am having the same issue with another package 
![image](https://user-images.githubusercontent.com/84468064/154588850-30b1a4c2-6543-4665-921d-504140797137.png)

**Comment by aasoni** [comment]
This started to happen for us as recently as well in our cloud build batch process. This used to work until a week ago, which is when we started seeing these errors

![image](https://user-images.githubusercontent.com/8077248/154682461-b2b3edc6-bc11-4068-8ecb-f6c09198b826.png)

**Comment by KEALHOVIK** [comment]
Same issue here.

**Comment by Centribo** [comment]
This occurs with me aswell when trying to install C5:
![image](https://user-images.githubusercontent.com/6460973/155220194-24ad446d-c5d0-4aa6-9e43-a9a09ea5f296.png)

**Comment by LeviVisser** [comment]
Same issue here, cannot install anything

**Comment by jwittner** [comment]
This may have been recently fixed by #434. Can someone on this issue test with latest from the repo and if it does fix this I'll make the effort to craft a new release ASAP.

**Comment by LeviVisser** [comment]
> This may have been recently fixed by #434. Can someone on this issue test with latest from the repo and if it does fix this I'll make the effort to craft a new release ASAP.

Running latest from repo with android build target and Unity version 2020.3.17f1 (my own use case) works.

**Comment by jwittner** [comment]
Ok fix should be available at https://github.com/GlitchEnzo/NuGetForUnity/releases/tag/v3.0.4
