### ISSUE TITLE
XML Exception - hexadecimal issue 0x1f is an invalid character. Line 1, position 1

### ISSUE THREAD

**Issue by Willnoble83** [GlitchEnzo/NuGetForUnity#440]
## Description
When trying to install any package (Tested with: Microsoft.Extensions.Logging, Microsoft.BCL.AsyncInterfaces, Serilog) I get the above error message
![image](https://user-images.githubusercontent.com/24992749/155309553-d6b4f2e7-91d9-4508-ab2f-6374558433d0.png)
(error message is pretty much the same for all packages)

I am not sure if I am doing something wrong. Have tried clearing the NuGet.config file in the project and restarting to regenerate it but it hasn't worked. Any assistance with this issue would be greatly appreciated.

- **NuGet Package:** Tested with: Microsoft.Extensions.Logging, Microsoft.BCL.AsyncInterfaces, Serilog
- **NuGetForUnity Version:** 3.0.2
- **Unity Version:** 2020.3.14f1
- **Operating System:** Windows 10 64 Bit

**Comment by gtoto007** [comment]
How Can I test the latest version from repo without dll on Unity?

**Comment by gtoto007** [comment]
I resolved! Your fix is working!

**Comment by jwittner** [comment]
Ok fix should be available at https://github.com/GlitchEnzo/NuGetForUnity/releases/tag/v3.0.4
