### ISSUE TITLE
Casing problem in Nuget 3.04 package: NugetForUnity vs NuGetForUnity

### ISSUE THREAD

**Issue by genereddick** [GlitchEnzo/NuGetForUnity#442]
Installing Nuget 3.04 from the Unity package installer throws an error due to a casing mismatch

Error is along the lines of:
assembly will not be loaded due to errors NugetForUnity does not match the name NuGetForUnity.

It seems to be looking for the dll "NuGetForUnity" but the dll installed is "NugetForUnity"

Renaming the file and restarting Unity fixes the problem

- **NuGet Package:3.04
- **Unity Version: Unity 2021.2.16f1
- **Operating System: Windows 11

**Comment by kunlinyu** [comment]
same to me.

the two command fixes the problem:

$ mv Assets/NuGet/Editor/NugetForUnity.dll Assets/NuGet/Editor/NuGetForUnity.dll
$ mv Assets/NuGet/Editor/NugetForUnity.dll.meta Assets/NuGet/Editor/NuGetForUnity.dll.meta


    **NuGet Package:3.0.4
    **Unity Version: Unity 2022.1.0b11.2843
    **Operating System: Ubuntu 20.04.03

**Comment by feipinxiang** [comment]
same error. Renaming the dll manually doesn't fix the problem.
windows 10, unity2021.3.0f1.

**Comment by iamabigartist** [comment]
Renaming manually doesn't fix the problem on
windows 10, unity2021.2.16f1.

**Comment by jwittner** [comment]
This should be fixed in 3.0.5.
