### ISSUE TITLE
Unity 2021.3.0f1 LTS when import NuGetForUnity.dll has naming issue

### ISSUE THREAD

**Issue by michael811125** [GlitchEnzo/NuGetForUnity#447]
2021.3.0f1 LTS dll name must be same as assembly name, If not is same has error lead to import failed.
rename NugetForUnity.dll => NuGetForUnity.dll

**Comment by Roshinator** [comment]
I had the same issue. Tried reinstalling the latest version and it didn't work.

**Comment by dbqt** [comment]
Same thing here on a fresh project in 2021.3.0f1 with this being the only thing added to the project.
The full error message is:

> Assembly 'Assets/NuGet/Editor/NugetForUnity.dll' will not be loaded due to errors:
Assembly name 'NuGetForUnity' does not match file name 'NugetForUnity'

**Comment by z3nth10n** [comment]
Same here!

**Comment by miggat** [comment]
Exact same message, unable to use it

**Comment by etaxi341** [comment]
Same problem

**Comment by jwittner** [comment]
Released at https://github.com/GlitchEnzo/NuGetForUnity/releases/tag/v3.0.5
