### ISSUE TITLE
Unable to install package Az in PowerSheel

### ISSUE THREAD

**Issue by UmashankarSingh** [GlitchEnzo/NuGetForUnity#448]
hi.,

I am getting the below error message when trying to install Az module in PowerShell:
PS C:\Users\INUMSIN> Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
Install-Package: Package 'Az.Attestation' failed to be installed because: End of Central Directory record could not be found.

PowerShell Version
PowerShell 7.2.2

**Comment by jwittner** [comment]
I don't think this is the right repo for your issue...

**Comment by jwittner** [comment]
Perhaps you wanted https://github.com/Azure/azure-powershell ?
