### ISSUE TITLE
Deleted my packages folder...

### ISSUE THREAD

**Issue by rafaelbenavent** [GlitchEnzo/NuGetForUnity#455]
This asset deleted everything in my Packages folder. I think this should be made pretty clear that it deletes things. Ideally, if the Package folder is in use, the user should be prompted to use another folder.

**Comment by jwittner** [comment]
Unclear on how we'd detect that the folder wasn't just out of date - in most cases the user wants the packages folder to align with the N4U packages file defines it. If we can detect that I think it's a great idea to confirm deletion. Maybe we can track it as a user preference, prompt, but have a check box to not check going forward?

Open to PRs. =)

**Comment by raspberrypuppies** [comment]
I discovered that it even deletes itself if you move it into Assets/Packages

**Comment by JoC0de** [comment]
Inside the `NuGet.config` file you can decide where the packages should be stored.  What exactly is the use case of placing files inside the same location as files that are automatically handled by a package-manager?

**Comment by warent** [comment]
Well I'm relieved I read this before using the package. Deleted immediately. Please consider adding this info to your README

**Comment by JoC0de** [comment]
@warent but what items are you placing inside the `Assets/Packages` folder as long as I know it is not a "default" folder. But yes deleting files that without a notice is not expected. I think I will change the behavior.
