### ISSUE TITLE
Getting 401 Unauthorized error while fetching packages from JFrog Artifactory

### ISSUE THREAD

**Issue by urlloader** [GlitchEnzo/NuGetForUnity#456]
## Description
I uploaded a custom Nuget package to a private **JFrog Artifactory** repo (as they support Nuget API v2). 

Unfortunately, even though I add the JFrog repo/user/pass to my `Assets/NuGet.config` file, as soon as I click "Nuget  -> Manage Nuget Packages" from unity to search and install my custom package to the project, I get a `401` (Unauthorized) error in the console.

Here is the full error message:
```
Unable to retrieve package list from https://USER.jfrog.io/artifactory/api/nuget/REPO/Search()?$filter=IsLatestVersion&$orderby=DownloadCount desc&$skip=0&$top=15&searchTerm=''&targetFramework=''&includePrerelease=false
System.Net.WebException: The remote server returned an error: (401) .
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x00146] in <6d7c4c8dd3624dc596686fb7270ae1e6>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <6d7c4c8dd3624dc596686fb7270ae1e6>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <6d7c4c8dd3624dc596686fb7270ae1e6>:0 
  at NugetForUnity.NugetHelper.RequestUrl (System.String url, System.String userName, System.String password, System.Nullable`1[T] timeOut) [0x000c0] in <52f11524b7d74432afd0486e05bd92cc>:0 
  at NugetForUnity.NugetPackageSource.GetPackagesFromUrl (System.String url, System.String username, System.String password) [0x0006c] in <52f11524b7d74432afd0486e05bd92cc>:0 
  at NugetForUnity.NugetPackageSource.Search (System.String searchTerm, System.Boolean includeAllVersions, System.Boolean includePrerelease, System.Int32 numberToGet, System.Int32 numberToSkip) [0x000ce] in <52f11524b7d74432afd0486e05bd92cc>:0 
UnityEngine.Debug:LogErrorFormat (string,object[])
NugetForUnity.NugetPackageSource:Search (string,bool,bool,int,int)
NugetForUnity.NugetHelper:Search (string,bool,bool,int,int)
NugetForUnity.NugetWindow:UpdateOnlinePackages ()
NugetForUnity.NugetWindow:Refresh (bool)
NugetForUnity.NugetWindow:OnEnable ()
UnityEditor.EditorWindow:GetWindow<NugetForUnity.NugetWindow> ()
NugetForUnity.NugetWindow:DisplayNugetWindow ()
```

And here is the content of my `Assets/NuGet.config` :
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
       <clear />
       <add key="NuGet" value="http://www.nuget.org/api/v2/" />
        <add key="ArtifactoryV2" value="https://USER.jfrog.io/artifactory/api/nuget/REPO/" />
    </packageSources>
    <disabledPackageSources />
    <activePackageSource>
       <add key="All" value="(Aggregate source)" />
    </activePackageSource>
    <config>
       <add key="repositoryPath" value="./Packages" />
       <add key="DefaultPushSource" value="http://www.nuget.org/api/v2/" />
    </config>
	<packageSourceCredentials>
    <ArtifactoryV2>
        <add key="Username" value="USER_EMAIL" />
        <add key="Password" value="PASSWORD" />
    </ArtifactoryV2>
	</packageSourceCredentials>
</configuration>
```

I tried:
1. Adding the plain, unencrypted password manually to `Assets/NuGet.config` (did not work)
2. Using the `nuget sources Add` command to add the encrypted to password `Assets/NuGet.config` (did not work)

Neither approach worked. I am still getting the same `401` error.

However when I drop the URL `https://USER.jfrog.io/artifactory/api/nuget/REPO/Search()?$filter=IsLatestVersion&$orderby=DownloadCount desc&$skip=0&$top=15&searchTerm=''&targetFramework=''&includePrerelease=false` in a web browser, the browser opens a credential window in which I put the same user email and plain, unencrypted password from the `Assets/NuGet.config`, and it works. I get an XML response back with a list of packages. Which means the issue is not from the **JFrog Artifactory** server.

Am I missing something?
Is there a specific way to set credentials for custom repos?

I read from some other closed issues that a credential managers is supposed to pop up, but I never get that. I get a straight up, unceremonious `401`.

Any help is greatly appreciated.

- **NuGet Package:** This is a custom package
- **NuGetForUnity Version:** 3.0.5
- **Unity Version:** Unity 2021.3.1f1
- **Operating System:** Windows 10 21H2 (OS Build 19044.1706)

**Comment by JoC0de** [comment]
there is a example on how to set credentials: https://github.com/GlitchEnzo/NuGetForUnity/blob/master/Assets/Tests/Resources/NuGet.config
as far as I can see it you need to use `userName` and `clearTextPassword` (important the casing needs to match).

**Comment by JoC0de** [comment]
No response so I close it
