### ISSUE TITLE
How to -executeMethod NugetForUnity.NugetHelper.Restore on different path than project path

### ISSUE THREAD

**Issue by darrenge** [GlitchEnzo/NuGetForUnity#460]
There is a thread on the Game-CI about this too: https://github.com/game-ci/unity-builder/issues/276 so I know others are seeing issues too.

I am on Windows 11; Unity 2020.3.25f1; 

I am trying to do a restore of Nuget packages and it doesn't look like things are working. 

$proc = Start-Process -FilePath "$editor" -ArgumentList "-projectPath $($projectPath) -logFile $($logFile.FullName) -batchMode -quit -wait -buildOutput $outDir -logDirectory $logDirectory -buildWindows64Player ./PerspectiveView.exe -executeMethod NugetForUnity.NugetHelper.Restore" -PassThru 

After running this Start-Process, I still get errors that it is missing projects like the nuget was not restore.  If I run Nuget.exe restore from $ProjectPath\Assets it works fine, so I know the Nuget restore works. Also, if I run Nuget.exe after this batchBuild call, the nuget packages are restored proving that the NugetHelper.Restore is not working.

**Comment by darrenge** [comment]
My NugetForUnity version is 3.0.5 and there isn't a new update so it is the latest and greatest.

**Comment by JoC0de** [comment]
The way Unity is working (when opening from command line): 
1. runs the C# Compiler and compile the project Scripts (this fails on your side)
2. runs the `-executeMethod` specified
so you need to add a second call of the unity-editor with `-ignoreCompilerErrors` that performs the nuget restore before performing the build see https://github.com/GlitchEnzo/NuGetForUnity/issues/414#issuecomment-938556496

**Comment by JoC0de** [comment]
I finally released the CLI for restoring packages before starting Unity Editor [NuGetForUnity.Cli](https://www.nuget.org/packages/NuGetForUnity.Cli).
