### ISSUE TITLE
Fatal: Int32 Overflow When Installing "Microsoft.Extensions.Primitives"

### ISSUE THREAD

**Issue by chenyanzz** [GlitchEnzo/NuGetForUnity#461]
## Description
[Describe the issue you have.]

- **NuGet Package:** "Microsoft.Extensions.Primitives >= 2.0.2" as a dependency
- **NuGetForUnity Version:** latest 3.0.5
- **Unity Version:** 2020.26r1c1
- **Operating System:** Win11
- from the error message, I guess it the "CntBrowse" in XML greater than MAX_INT

**Comment by jwittner** [comment]
Closing as resolved with https://github.com/GlitchEnzo/NuGetForUnity/pull/464. Please reopen if you still experience this with latest from master.
