### ISSUE TITLE
System.OverflowException when trying to install package.

### ISSUE THREAD

**Issue by Christanoid** [GlitchEnzo/NuGetForUnity#463]
## Description
Can't install a package due to a System.OverflowException

- **NuGet Package:** Makaretu.Dns.Multicast version 0.27.0
- **NuGetForUnity Version:** 3.0.5
- **Unity Version:** 2022.1.12f1
- **Operating System:** Windows 11

![image](https://user-images.githubusercontent.com/21364591/184540795-231c33d2-7dce-446c-b4b5-724c9b83a500.png)

**Comment by nikola-bozin** [comment]
Hello, im having the same issue. How can i change "int" to "long", and where?

**Comment by jwittner** [comment]
Closing as resolved with #464. Please reopen if you still experience this with latest from master.
