### ISSUE TITLE
Errors after installing Microsoft.ML.Probabilistic.Compiler

### ISSUE THREAD

**Issue by fdorothy** [GlitchEnzo/NuGetForUnity#466]
## Description
I'm seeing several errors after installing Microsoft.ML.Probabilistic.Compiler.

`Library\PackageCache\com.unity.visualscripting@1.7.8\Editor\VisualScripting.Core\Platforms\AotStubWriter.cs(18,37): error CS0433: The type 'CodeStatement' exists in both 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Library\PackageCache\com.unity.visualscripting@1.7.8\Editor\VisualScripting.Core\Platforms\AotPreBuilder.cs(31,37): error CS0433: The type 'CodeStatement' exists in both 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

...
`

- **NuGet Package:** Microsoft.ML.Probabilistic.Compiler Version 0.4.2203.202
- **NuGetForUnity Version:** 3.0.5
- **Unity Version:** Unity 2021.3.6f1
- **Operating System:** Windows 10

**Comment by jamieyello** [comment]
Getting similar errors with Microsoft.ML, haven't fount a solution

**Comment by JoC0de** [comment]
Are you using the UPM version of NuGetForUnity? 
Do you use netstandard or .net framework as a scripting backend?
