### ISSUE TITLE
How to use *Reference element in some nuget libraries

### ISSUE THREAD

**Issue by xiaochao00** [GlitchEnzo/NuGetForUnity#467]
## How to use *Reference element in some nuget libraries?
Such as library: [ikvm](https://www.nuget.org/packages/IKVM/8.2.0)

When I use NuGetForUnity in Unity, I do not know how to add "IkvmReference" element in project. Can you help me?

- **NuGet Package:** ikvm
- **NuGetForUnity Version:** latest
- **Unity Version:** 2021
- **Operating System:** window10

**Comment by JoC0de** [comment]
Unity generates the .csproj files on demand. You can hook into the generation process and edit the file content before it is written to disk using `OnGeneratedCSProject` see [documentation:](https://learn.microsoft.com/en-us/visualstudio/gamedev/unity/extensibility/customize-project-files-created-by-vstu) 
[CsprojModifier](https://github.com/Cysharp/CsprojModifier) also uses this method.
An probably more suitable alternative is using a [Directory.Build.props](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build) and placing it inside your unity project folder so the additional 'Properties' will be available to the build process (at leas when building inside Visual Studio, I never teste if this works when performing a build inside Unity). As IKVM does advanced stuff while intercepting the buld-process i am not sure if it will work within unity.

**Comment by JoC0de** [comment]
When you build a project inside unity it doesn't use the csproj file. So the only way to do sitch advanced stuff and not needing to force unity to somehow do the extra stuff while compilation is to create a external C# project that compiles a library that you than use inside unity. There is a tutorial under https://link.medium.com/ivim1NlJ9xb how you can do this.
