### ISSUE TITLE
Question about contributing

### ISSUE THREAD

**Issue by JoC0de** [GlitchEnzo/NuGetForUnity#473]
I like to help maintaining and contributing to this project.
For me the project is a "must have" for Unity but it leaks some important functionalities that I would like to add.
I could just create some PRs but as there is not that much activity lately I ask here first.
So is there a possibility to become a co-maintainer? Or has someone time to merge PRs?

**Comment by GlitchEnzo** [comment]
You should now have access. Thanks for volunteering!

**Comment by jwittner** [comment]
Yay! Thanks @JoC0de - I'm so glad to see someone picking this project up as my time available for it has reduced dramatically over the last year!.
