### ISSUE TITLE
[Install] button dosen’t work

### ISSUE THREAD

**Issue by third0light** [GlitchEnzo/NuGetForUnity#477]
I want to install Microsoft.CodeAnalysis.CSharp.Scripting, but the [Install] button didn’t work.I pressed the button but nothing happened.

- Microsoft.CodeAnalysis.CSharp.Scripting 4.4.0 [What is the name and version of the NuGet package you are installing?]
- NuGetForUnity Version:3.0.5 [What version of NuGetForUnity are you running?]
- Unity Version:2021.3.6F1C1 [What version of Unity are you using?]
- Operating System:win11 22H2 [What OS are you on?]

**Comment by Atennop1** [comment]
I have this issue too. Fix please

**Comment by JoC0de** [comment]
you are tying to install the "C# Compiler" into Unity.
1.  you picked version 4.4.0 witch is the C# compiler for C# 10 (see: https://github.com/dotnet/roslyn/blob/main/docs/wiki/NuGet-packages.md) Unity only supports C# 9 (see: https://docs.unity3d.com/Manual/CSharpCompiler.html)
2. Unity has its own package that contains "what you try to install" https://docs.unity3d.com/Packages/com.unity.code-analysis@0.1/manual/index.html so I think NuGetForUnity is skipping the installation as "already imported". But to verify you can just enable verbose logging.

If this doesn't help you pleas add the log from console (after you enable Verbose-Logging).

**Comment by davide-aldegheri** [comment]
I have this issue too when trying to install RabbitMQ.Client, after enabling verbose logging it produces these two lines:

Is package 'RabbitMQ.Client' already imported? True
Package RabbitMQ.Client.6.4.0 is already imported in engine, skipping install.

I've tried installing it in another empty project and it works fine. In my original project I don't have the line about Rabbit in the packages.config file, is there any way I can workaround this issue?

**Comment by JoC0de** [comment]
@davide-aldegheri do you use the current master of NuGetForUnity (using upm)? There was a change recently that should affect the installation of RabbitMQ as unity has a version of RabbitMQ in on of its internal packages, and before the change we detected this .dll and therefore it was skipping the installation as "already imported". I didn't released a new version until now but the UPM version or the current build artefact (.unitypackage) should have the fix.

**Comment by davide-aldegheri** [comment]
@JoC0de thank you, that did the trick, I've removed the package installed via .unitypackage and installed using upm, after a restart of the application I was able to correctly install RabbitMQ.

**Comment by JoC0de** [comment]
Closing as no response.
