### ISSUE TITLE
No packages found in hierarchical NuGet local folder

### ISSUE THREAD

**Issue by Facsimiler** [GlitchEnzo/NuGetForUnity#481]
## Description

I have a local folder that stores internally-developed _NuGet_ packages. _NuGetForUnity_ locates this folder (it doesn't issue any errors stating that the directory cannot be found, which is what happens if I deliberately enter an invalid path), but doesn't list any of the packages it contains.

The `NuGet.config` file (as populated through the _Edit/Preferences/NuGet_ form) is as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="http://www.nuget.org/api/v2/" />
    <add key="Internal" value="%HOMEDRIVE%%HOMEPATH%\NuGet" />
  </packageSources>
  <disabledPackageSources />
  <packageSourceCredentials />
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <config>
    <add key="repositoryPath" value="./Packages" />
    <add key="verbose" value="true" />
    <add key="InstallFromCache" value="false" />
    <add key="ReadOnlyPackageFiles" value="false" />
  </config>
</configuration>
```

Note that I've tried changing the order of the repos in `packageSources`, to no avail.

We publish to this folder using both the `nuget add` and `dotnet nuget push` CLI commands, and can access them through `NuGet` in _Visual Studio_ and _Rider_, so there's no issue with the local folder repo organization itself.

-   **NuGet Package:** n/a
-   **NuGetForUnity Version:** 3.0.5
-   **Unity Version:** 2021.3.14f1
-   **Operating System:** Windows 10 Enterprise 22H2.

Any thoughts?

**Comment by Facsimiler** [comment]
According to the _Microsoft_ [documentation on local feeds](https://learn.microsoft.com/en-us/nuget/hosting-packages/local-feeds), _NuGet_ 3.3+ supports hierarchical folder structures. I'm guessing such hierarchical folders are not supported by _NuGetForUnity_, right now.

If I add the `.nuget` packages to the local folder itself, then `NuGetForUnity` finds them OK.

So I guess this becomes a request to support hierarchical folders in _NuGet_ local feeds.

**Comment by JoC0de** [comment]
Hi,
thanks for the good explanation. Yes you are correct currently it only searches for the `.nuget` on top level.
It is a feature that is relatively easy to implement there is already a PR #147 .
I am not happy with the implementation used in the PR. I think I will implement this feature soon. I hope it is not "urgent".

**Comment by Facsimiler** [comment]
Hi @JoC0de!

Thanks for the prompt reply. I guess now I know that there's a workaround, I guess it's no longer "urgent": I can simply copy the files across to the root directory for now. However, supporting the new folder structure would definitely result in fewer surprises for new users. I certainly spent a lot of time trying to figure this out. :-)

I'd be willing to volunteer my time to polish the PR, if that helps...

**Comment by JoC0de** [comment]
@Facsimiler thanks for the "willing" but I don't need help with this feature, it is "simple".

**Comment by Facsimiler** [comment]
No worries. :-)

BTW, I was looking at the code for this in the current implementation, and it looks like you're rolling your own solution. However, there's a [_NuGet_ client API](https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk) available that ought to simplify matters even further, in case you're unaware of it.

**Comment by mpsbauer** [comment]
I'm also looking for this feature. So I'm glad to hear it is on your radar. It is something we will need eventually, but it isn't urgent.
