### ISSUE TITLE
Libs with target "netstandard2.1" is not imported, but since Unity 2021.3 it is supported.

### ISSUE THREAD

**Issue by kekchpek** [GlitchEnzo/NuGetForUnity#485]
## Description
When I try to import package with target framework "netstandard2.1" the `lib` folder keeps being empty. As I understand it happens cause NuGetForUnity somehow filter libs in package and leave only the ones, that are supported by Unity. But "netstandard2.1" becomes being supported, so, probably it should be added to this filter?

-   **NuGet Package:** UnityMVVM.0.3.1
-   **NuGetForUnity Version:** 3.0.4
-   **Unity Version:** 2021.3.16f1
-   **Operating System:** Windows 10

**Comment by JoC0de** [comment]
Hi @kekchpek thanks for the note. 
I already implemented it in #479 I just didn't released it as I did some 'bigger' changes but you can use the preview build (output of the CI build https://github.com/GlitchEnzo/NuGetForUnity/suites/10378313881/artifacts/512068112).
If you use the preview build pleas report any errors (if you find some).

**Comment by kekchpek** [comment]
Thanks!
