### ISSUE TITLE
Unity crash when searching or resolving BitMiracle.LibTiff.NET

### ISSUE THREAD

**Issue by Risord** [GlitchEnzo/NuGetForUnity#497]
## Unity crash when searching or resolving BitMiracle.LibTiff.NET

I had package BitMiracle.LibTiff.NET installed but when I updated 2021.3.16 => 2021.3.18 (or .17) Unity crashes on startup.

Minimal reproduce is:
1. Create new Unity project (3D Core tested)
2. Install NuGetForUnity
3. Open Nuget/Manage Nuget Packages
4. Search "BitMiracle.LibTiff.NET" => Unity will crash (no need to even install)

-   **NuGet Package:** BitMiracle.LibTiff.NET
-   **NuGetForUnity Version:** 3.0.5
-   **Unity Version:** 2021.3.18
-   **Operating System:** Windows 11

**Comment by JoC0de** [comment]
Hi @Risord thanks for the bug report. There is a issue that the icons of some NuGet Packages are GIF format what is not supported by Unity buildin Texture2D. In the newest release 3.1.0 this is error is now ignored / catched.
