### ISSUE TITLE
Unity 2021.3.20 Crash while searching NuGet 

### ISSUE THREAD

**Issue by AmoghaSrikanth** [GlitchEnzo/NuGetForUnity#504]
Hello,
I am trying to search websocketsharp from NuGet but I dont know for some reasons my unity is crashing can you help me with this.
I have attached the recording of the same as well.
-   NuGet Package: 3.1.0
-   NuGetForUnity Version: 3.0.5
-   Unity Version:2021.3.20f1
-   Operating System:Windows 11

https://user-images.githubusercontent.com/113014994/225588680-662b34cb-2f47-43d2-9e11-2b913454c46a.mp4

**Comment by igor84** [comment]
It would help if you could send the Editor.log after the crash. You can probably just click Go to crash logs on that last dialog that opens to find it.

**Comment by AmoghaSrikanth** [comment]
Please find attached the Editor.log
[Editor.log](https://github.com/GlitchEnzo/NuGetForUnity/files/10989992/Editor.log)

**Comment by igor84** [comment]
I see you are using Unity 2021.3.20 so it might be this [Unity bug](https://issuetracker.unity3d.com/issues/downloadhandlertexture-crashes-if-it-downloads-invalid-texture-data) that they claim they fixed in 2021.3.21. Can you try updating Unity to that version?

**Comment by AmoghaSrikanth** [comment]
Yes it did get resolved in the unity version of 2021.3.21.
Thanks
