### ISSUE TITLE
Ability to import packages where the dll AutoReferenced asset property is set to false

### ISSUE THREAD

**Issue by callum-rose-red-engine** [GlitchEnzo/NuGetForUnity#505]
## Description

[Describe the issue you have.]

-   **NuGet Package:** [What is the name and version of the NuGet package you are installing?]
-   **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
-   **Unity Version:** [What version of Unity are you using?]
-   **Operating System:** [What OS are you on?]

**Comment by callum-rose-red-engine** [comment]
I'm not the author, it's just standard Serilog packages in my case. I could make a fork but that would require manually keeping it up to date with main, and seems very heavy handed. I know plugins use a PluginImporter object but I'm not sure how to modify this, the docs are pretty vague about how to use it

**Comment by callum-rose-red-engine** [comment]
As you say I was imagining a flag in the package.config file. This would ensure a package restore would setup the imports correctly without having to commit anything extra to the repo. In my use case I only want to control the references between dlls and unity assembly references / the predefined C-Sharp-Assembly. In my head this would be a checkbox you can toggle when first importing the package

**Comment by JoC0de** [comment]
@callum-rose-red-engine I added a flag to package.config file its called `autoReferenced`. The feature is no 100% clean so I didn't merged it jet but you can test it when you install the version from https://github.com/JoC0de/NuGetForUnity/tree/feature/add-auto-referenced-setting

**Comment by callum-rose-red-engine** [comment]
Yep this seems to work well. Cheers for speedy update!

I'm unsure if this is a thing just on this branch but I get this error if I install the Castle.Core package (Unity 2022.1.24f):
```
Assembly 'Assets/Packages/System.Diagnostics.EventLog.4.7.0/lib/netstandard2.0/System.Diagnostics.EventLog.dll' will not be loaded due to errors:
System.Diagnostics.EventLog references strong named System.Security.Principal.Windows Assembly references: 4.1.1.0 Found in project: 4.1.3.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
```

**Comment by JoC0de** [comment]
@callum-rose-red-engine this is a general issue. As described in den error message it is just a setting you need to change. See my other comment https://github.com/GlitchEnzo/NuGetForUnity/issues/415#issuecomment-1483919770
