### ISSUE TITLE
Unity crashed when i search a keyword "Protobuf"

### ISSUE THREAD

**Issue by ZombieCook** [GlitchEnzo/NuGetForUnity#506]
## Description

When i search at the Menu "Manage Nuget Packages" the keyword "Protobuf" unity crashed. No matter what case was like PROTOBUF or ProtoBuf.

Protobuf - Crash
Protobuf s - Crash
Protobufs - ok
Protobu - ok

So it seems like the token "Protobuf" is the problem, but i don't know why. It occurs on every project no matter it is new or not. 

Here is the crash log.
Also it is reproduced everytime whenever i tried to.

[CrashLog_30.03.23.txt](https://github.com/GlitchEnzo/NuGetForUnity/files/11107884/CrashLog_30.03.23.txt)

-   **NuGetForUnity Version:** [3.1.0]
-   **Unity Version:** [Hub 3.4.1, Editor 2021.3.18f1]
-   **Operating System:** [Windows 10, 64bit]

**Comment by igor84** [comment]
This looks like issue #504. Can you try newer Unity version?

**Comment by ZombieCook** [comment]
> This looks like issue #504. Can you try newer Unity version?

I didn't checked closed issues. It solved on newer unity version.

thank you for clarifying it :)
