### ISSUE TITLE
Issue with UnityPreImportedLibraryResolver in unitypackage

### ISSUE THREAD

**Issue by igor84** [GlitchEnzo/NuGetForUnity#512]
## Description

I noticed a strange issue that only happens when you install NugetForUnity as unitypackage. If you try to install Google.Protobuf package it will pull System.Runtime.CompilerServices.Unsafe, but also System.Buffers, System.Memory and System.Numerics.Vectors. If you install NugetForUnity as a unity package from Git Url than in only pulls System.Runtime.CompilerServices.Unsafe because it correctly concludes the other packages are already installed.

I also tried building the NugetForUnity.dll from NuGetForUnity.CreateDll solution myself and putting that dll into Unity and again it only pulled that one dependency. I guess that means the issue must somehow be in a way you built that dll before you packaged it into unitypackage file that can be downloaded from Releases page.

-   **NuGet Package:** Google.Protobuf
-   **NuGetForUnity Version:** 3.1.0
-   **Unity Version:** 2021.3.12f1
-   **Operating System:** Windows

**Comment by JoC0de** [comment]
It need to be related to the fact that we compile the .dll using Unity 2018 so all code that uses preprocessor directives like `#if` are using the "old" implementation. So this issue need to be related to 
```csharp
#if UNITY_2019_3_OR_NEWER
            const AssembliesType assemblieType = AssembliesType.PlayerWithoutTestAssemblies;
#else
            const AssembliesType assemblieType = AssembliesType.Player;
#endif
```
https://github.com/GlitchEnzo/NuGetForUnity/blob/2a728b401a9f7687dffec4f354e27ddd3d613fa5/src/NuGetForUnity/Editor/UnityPreImportedLibraryResolver.cs#L42
But I see no way this can have more assemblies in the "not 2019" branch. Did you look at the Verbose Log e.g. the `Already imported libs: ...` and the `Selecting {0} as the best target framework for current settings`. Eventually it didn't select the correct TargetFramework or detects wrong ApiCompatibilityLevel. As far as I know Unity should run the .dll code the same way as the Git-Package code so it need to be related to preprocessor directives.

**Comment by JoC0de** [comment]
Are you getting the issue in the Nordeus/NuGetForUnity fork? So it is related to https://github.com/Nordeus/NuGetForUnity/blob/83a38cee8e4b4d2752cf1bb17c1b3f86f6bfd94b/Assets/NuGet/Editor/UnityPreImportedLibraryResolver.cs#L31

**Comment by igor84** [comment]
No, I tested this only with your version. The DLL reported 142 "Already imported libs" and the git URL version reported 192. Later I also tried DLL built from our (Nordeus) fork and it also reported 192 Already imported libs but we built our DLL with Unity 2021 so it seems your first post is onto something. I'll see if I can try to execute the #else branch in newer Unity tomorrow from git URL and see what happens.

**Comment by igor84** [comment]
I looked at the decompiled code from the DLL and I realized the difference is coming from the fact that you made a Release 3.1.0 unitypackage two months ago when code in UnityPreImportedLibraryResolver was still using AppDomain.CurrentDomain.GetAssemblies() and when I install the plugin from git url I actually get the latest code version which uses CompilationPipeline.GetAssemblies(assemblieType). So that is where my confusion came from and everything is actually fine :) .

**Comment by JoC0de** [comment]
@igor84 oh sorry, that I missed it. I shortly thought about it but I was pretty sure that the change was already in version 3.1.0.
