### ISSUE TITLE
Header Section is Black in Editor Window using Light Skin

### ISSUE THREAD

**Issue by CDTR-MattConroy** [GlitchEnzo/NuGetForUnity#517]
## Description

The header section in the Manage Nuget Packages Editor Window has a black background (presumably also with black text), therefore nothing can be seen or read apart from buttons.

-   **NuGetForUnity Version: 3.1.0
-   **Unity Version: 2022.2.13f1
-   **Operating System: Windows 11 Home 22H2

![image](https://user-images.githubusercontent.com/120377840/233296765-7a91a92d-c427-4bcb-8557-75d8a2affaca.png)

**Comment by JoC0de** [comment]
I cant't reproduce it.
With Dark-Mode:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/53140583/233793385-d30d722b-baac-43f9-a345-076579a25480.png">
with Light-Mode:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/53140583/233793392-404aa817-44bb-4db6-b328-824fdfcee50f.png">
I also testet in version 2022.2.1f1 but I don't have 2022.2.13f1. Do you have some special settings? Do you have the same issue when using Dark-Mode?

**Comment by CDTR-MattConroy** [comment]
This is what I see after switching to Dark Mode:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/120377840/233928695-26d23427-ff2c-472e-93f2-b2ef8ba1e555.png">

It's still the same after switching back to light mode. 
It looks like from your screenshot that the background for the header shouldn't be black even in Dark Mode? Seems something is telling that background to be black regardless of the theme. Maybe an un-initialised texture somewhere?

**Comment by CDTR-MattConroy** [comment]
I have it installed via UPM. I've debugged the script and the background of the GUIStyle is being set correctly. I've retested in Unity 2022.2.1f1 and Unity 2022.2.16f1 (the latest) and I get the same result. 

I thought it might be due to scaledBackgrounds not being set (as I'm working on a laptop that uses Windows scaling, but that didn't seem to have any effect.

**Comment by JoC0de** [comment]
The [GUIStyle](https://docs.unity3d.com/ScriptReference/GUIStyle.html) has separate settings for `active` `focused` and `hover` eventually Unity uses one of them instead of the `normal` style we change. Can you try setting them?

**Comment by CDTR-MattConroy** [comment]
I tried setting those as well and no joy. It looks like EditorGUILayout.BeginVertical isn't respecting the style somehow?

**Comment by JoC0de** [comment]
Can you try changing the 
https://github.com/GlitchEnzo/NuGetForUnity/blob/1360823f15ed590204b960472df505357c1bb929/src/NuGetForUnity/Editor/NugetWindow.cs#L526
to `MakeTex(16, 16, ...`. Eventually it is because your GPU needs a two-complement as texture size.

**Comment by CDTR-MattConroy** [comment]
I changed all the MakeTex to 16, I tried 8 and 4 as well to no avail.
I tested chaning the ProLicense checks to ProSkin checks and now it's at least visible, though I don't think it matches your screenshots from earlier.

Light Skin:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/120377840/234511687-199e8df0-2dbc-45da-b916-ac2e83597e04.png">

Dark Skin:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/120377840/234511768-e48c87e0-50f9-4ac8-a375-8e75b0f11839.png">
