### ISSUE TITLE
NuGetForUnity Unity Package reports Incorrect Version

### ISSUE THREAD

**Issue by CDTR-MattConroy** [GlitchEnzo/NuGetForUnity#519]
## Description

In Unity Package Manager, the version reported is 3.0.5.
NuGet For Unity's Window reports the version as 3.1.0.

-   **NuGetForUnity Version: 3.1.0, depending on which window you believe
-   **Unity Version: 2022.2.16
-   **Operating System: Windows 11 22H2

![image](https://user-images.githubusercontent.com/120377840/234513968-f0f49be1-2e3a-4dfa-ab79-43e250d8674a.png)

**Comment by JoC0de** [comment]
Thanks for reporting the issue. So you installed NuGetForUnity using Git URL? Have you specified a tag at the end of the URL? It is relay strange as I changed the version number in the commit: https://github.com/GlitchEnzo/NuGetForUnity/commit/df746e943177c2b8f45de3c4bd8567a1c726e8f7 witch is also the on commit that is tagged with v3.1.0.

**Comment by CDTR-MattConroy** [comment]
Yes, I've installed NuGetForUnity with the following Git URL `https://github.com/GlitchEnzo/NuGetForUnity.git?path=/src/NuGetForUnity`.

The version displayed in Unity Package Manager is the version that's set in the package manifest, looks like currently it's still set to 3.0.5: https://github.com/GlitchEnzo/NuGetForUnity/blob/master/src/NuGetForUnity/package.json

**Comment by JoC0de** [comment]
@CDTR-MattConroy thanks. I fixed it.

**Comment by CDTR-MattConroy** [comment]
@JoC0de any word on when this will be released? UPM still reports 3.0.5 from 20 Feb 2023 as the latest

**Comment by JoC0de** [comment]
@CDTR-MattConroy I think the only way to synchronize both versions would be to release a new version. There are some changes so a new release makes sense, but there are still open PRs that I am working on. Especially merging https://github.com/GlitchEnzo/NuGetForUnity/pull/525 would be nice.

**Comment by JoC0de** [comment]
I thought about it and I can also provide a hotfix and reset the tag to the fixed version but I don't think that this is a nice solution.

**Comment by JoC0de** [comment]
@CDTR-MattConroy I released a new version (3.1.3) now it should be in sync.
