### ISSUE TITLE
Feature Request: Move the NuGet and packages .dll into a folder (i.e. packages) make it dynamically findable?

### ISSUE THREAD

**Issue by Avalin** [GlitchEnzo/NuGetForUnity#527]
Would be nice if it didn't clutter in the Assets folder itself :)

**Comment by JoC0de** [comment]
Hi @Avalin thanks for the suggestion. Unfortunately it is a hard requirement from unity that the .dll's are placed somewhere inside the assets folder, else unity will just ignore them. You can configure the exact folder where they are placed.
