### ISSUE TITLE
Installing unlisted packages

### ISSUE THREAD

**Issue by KingTempest07** [GlitchEnzo/NuGetForUnity#535]
## Description

I recently made a package for Nuget and I'm trying to test it on Unity. Because of that, I have it set to be unlisted so that nobody is going to waste their time on it if it doesn't work. Looking through the readme and issues, I couldn't find any way of installing unlisted packages (or at least nothing appeared to be related in any way).

So essentially, is there a built-in way to do this, or maybe even some way of installing via console?

-   **NuGet Package:** TempestStatSystem v1.0.1-pre-alpha
-   **NuGetForUnity Version:** v3.1.3
-   **Unity Version:** 2021.3.5f1
-   **Operating System:** Windows 10

**Comment by JoC0de** [comment]
Hi,
NuGetForUnity just uses the NuGet v2 API to find and download packages. So it basically called https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm=%27newtonsoft%27 it seems that there is no support for unlisted packages in API v2
See https://github.com/NuGet/Home/issues/5896. I am working on supporting API v3 but it will take a bit. But for simple testing you package you can use a local package source. Just place the NuGet package, the .nupkg, in a folder and add it as a local package source.

**Comment by KingTempest07** [comment]
Sorry for not responding. I couldn't get the local packages to work, but temporarily listing and unlisting again seems to work fine for now, although it is a little annoying sometimes.
