### ISSUE TITLE
Incompatible installation

### ISSUE THREAD

**Issue by thandh-3171** [GlitchEnzo/NuGetForUnity#536]
## incompatible installation

[Describe the issue you have. If applicable provide logs produced by enabeling verbose logging in the NuGetForUnity settings.]

-   **NuGet Package:** Redis 2.6.122
-   **NuGetForUnity Version:** 3.1.3
-   **Unity Version:** 2021.3.7f1
-   **Operating System:** Window
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/111112390/c45cca6f-1faa-4857-b69a-902574e525d7)

Then I try and install Unsafe 6.0.0. I got this error.
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/111112390/fc2a598b-bac2-419a-9ae5-f318f06ea7eb)

From here. I can't get to the point where I can downgrade to that version. (Unsafe 4.0.4.1).

**Comment by JoC0de** [comment]
Hi.
In the readme we have section on how to fix the version conflict error: See https://github.com/GlitchEnzo/NuGetForUnity#version-conflicts

**Comment by JoC0de** [comment]
Sorry for the delay. I now investigate the issue. You are using Api Compatibility Level .Net Framework.
So NuGetForUnity prevers dependencies targeting .Net Framework e.g. net47. Unity pre-includes `System.Threading.Tasks.Extensions` when targeting .Net Framework. In the dependency tree the package `System.Runtime.CompilerServices.Unsafe` is only listed as a dependency of [System.Threading.Tasks.Extensions](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/) [Pipelines.Sockets.Unofficial](https://www.nuget.org/packages/Pipelines.Sockets.Unofficial) somehow doesn't list it as a dependency. So `System.Runtime.CompilerServices.Unsafe` need to be installed manually either by editing the `package.config` or using the UI.

**Comment by thandh-3171** [comment]
Thanks for the explanation.
