### ISSUE TITLE
Feature request: ability to pin a version

### ISSUE THREAD

**Issue by RobertBaruch** [GlitchEnzo/NuGetForUnity#555]
## Description

[Describe the issue you have. If applicable provide logs produced by enabeling verbose logging in the NuGetForUnity settings.]

-   **NuGet Package:** Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0
-   **NuGetForUnity Version:** 3.1.3
-   **Unity Version:** 2022.3.4f1
-   **Operating System:** Windows 11

Currently the docs say:

> Enable Show All Versions to list all old versions of a package (currently only works with local nuget feeds). Disable Show All Versions to only show the latest version of a package.

However, if I'm trying to work with someone else, setting up a local nuget feed for everyone involved in the project is error-prone. I'd like the ability to install and pin a version of a package rather than always use the latest.

**Comment by JoC0de** [comment]
Hi @RobertBaruch,
thanks for the issue, sorry for the delay.
I don't really understand what you like to have. If you install a package in a Unity project we store the installed package, including the version number into a file `package.config`. You should just commit this file, including the `NuGet.config` file to your GIT. Then everyone automatically gets the same packages with the same version installed when he open the Project / when the  `package.config` file get changed (e.g. on a git merge). 
I hope this clears thinks. Eventually we can update the documentation to explain this in a easier way.

**Comment by RobertBaruch** [comment]
Maybe I asked for the wrong feature. What I really want is the ability for the Show All Versions button to list all old versions of a package *even if not local*. Then you can select the version you want to install and not have to set up a local nuget feed.

**Comment by JoC0de** [comment]
Ok this feature was implemented in #554 last week 😃. But it will only work with nuget feeds that support API version 3.

**Comment by JoC0de** [comment]
Just released version 4.0.0 witch contains the new feature.
