### ISSUE TITLE
BouncyCastle.1.8.5 fails to install properly.

### ISSUE THREAD

**Issue by ScionOfDesign** [GlitchEnzo/NuGetForUnity#583]
## Description

When trying to install `BouncyCastle.1.8.5` (or 1.8.9) or anything that depends on it, the package is not downloaded to the cache in the `.nuget/packages` folder and the actual `BouncyCastle.Crypto.dll` is not found, even though a BouncyCastle folder appears in the packages folder.

-   **NuGet Package:** BouncyCastle.1.8.5
-   **NuGetForUnity Versions: The latest on master**
  - 6936f0fb4e3a2adb46ab371a1c088b7cade34577
  - 749259df69620a4cd914ad893d21f342e0bc65aa
-   **Unity Version:** 2022.3.9f1
-   **Operating System:** Windows 11

**Comment by JoC0de** [comment]
If your project has assembly compatibility level set to the default `.net standard 2` it will not work to install this as it is a .net Framework package. You need to download [Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle/1.9.0#supportedframeworks-body-tab) that supports .net standard and.net Framework

**Comment by ScionOfDesign** [comment]
Thank you, but we were using .net framework and not.net standard.

**Comment by JoC0de** [comment]
Ok actually the [BouncyCastle](https://www.nuget.org/packages/BouncyCastle/1.8.5) package is deprecated and has a non standard package layout that we are not supporting:
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/53140583/901bba13-dd10-4d6c-b590-a30a0d479b5a)
You can install [BouncyCastle.Cryptography](https://www.nuget.org/packages/BouncyCastle.Cryptography) or [Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle/1.9.0#supportedframeworks-body-tab) that both support .net framework and .net standard.

**Comment by ScionOfDesign** [comment]
The issue is that we are using a slightly older version of MySQL.Data, version 8.0.25, which depends upon `BouncyCastle 1.8.5`.

We can try and upgrade, but I can definitely see it causing potential issues with projects that depend upon older packages.

**Comment by ScionOfDesign** [comment]
Also, perhaps an optional warning about deprecated packages would be nice to have.

**Comment by JoC0de** [comment]
The problem is not the depreciation. The folder structure is wrong. We can support this structure, I am not sure if it is standard conform and other packages also use this.

**Comment by ScionOfDesign** [comment]
Well, the weird thing is that we didn't have an issue with it until just very recently. We have been using this MySql package for months, but only noticed that we we're unable to load the project on a fresh machine with no cache today. If we delete the bouncycastle cache

**Comment by JoC0de** [comment]
It can be that older version supportet this folder structure. So I think we should re enable this.

**Comment by ScionOfDesign** [comment]
Thank you very much!
