### ISSUE TITLE
Package fails to download from GitHub Enterprise Server.

### ISSUE THREAD

**Issue by jbvirt** [GlitchEnzo/NuGetForUnity#598]
## Description

We are trying to use NuGet for unity with our GitHub Enterprise server. We can add out GHE server as a source and preview the packages, but trying to download fails.

![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/110490781/38ef5a2a-86a8-4788-b76d-63c31d4503d1)

Error:
```
Could not find ****.****.Persistence 1.0.0.2 or greater.
UnityEngine.Debug:LogErrorFormat (string,object[])
NugetForUnity.NugetPackageInstaller:InstallIdentifier (NugetForUnity.Models.INugetPackageIdentifier,bool,bool) (at ./Library/PackageCache/com.github-glitchenzo.nugetforunity@5a1e296804/Editor/NugetPackageInstaller.cs:39)
NugetForUnity.Ui.NugetWindow:DrawPackage (NugetForUnity.Models.INugetPackage,UnityEngine.GUIStyle,UnityEngine.GUIStyle,bool) (at ./Library/PackageCache/com.github-glitchenzo.nugetforunity@5a1e296804/Editor/Ui/NugetWindow.cs:1095)
NugetForUnity.Ui.NugetWindow:DrawPackages (System.Collections.Generic.IEnumerable`1<NugetForUnity.Models.INugetPackage>,bool) (at ./Library/PackageCache/com.github-glitchenzo.nugetforunity@5a1e296804/Editor/Ui/NugetWindow.cs:677)
NugetForUnity.Ui.NugetWindow:DrawOnline () (at ./Library/PackageCache/com.github-glitchenzo.nugetforunity@5a1e296804/Editor/Ui/NugetWindow.cs:642)
NugetForUnity.Ui.NugetWindow:OnGUI () (at ./Library/PackageCache/com.github-glitchenzo.nugetforunity@5a1e296804/Editor/Ui/NugetWindow.cs:293)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

-   **NuGet Package:** A custom one hosted on GitHub Enterprise Server 3.8.2
-   **NuGetForUnity Version:** The latest git hash: 5a1e29680437c762255e08402dcfe6d4ed10e084
-   **Unity Version:** 2022.3.9f1
-   **Operating System:** Windows

**Comment by JoC0de** [comment]
Ok seems like GitHub Packages also don't support the `packageid:<NuGetPackageId>` search query.
Azure seems to have the same issue see #589 
We need to implement a workaround using different APIs.
