### ISSUE TITLE
Problem setting up Azure Blob Storage in Unity on fresh installation

### ISSUE THREAD

**Issue by LuMiN0uSaRc** [GlitchEnzo/NuGetForUnity#601]
## Description

Currently I am having an issue using Azure Blob Storage in Unity using NuGet. Also, this is done on a **fresh set up of an Unity project.**

Errors: 
Assembly 'Assets/Packages/Azure.Storage.Blobs.12.18.0/lib/netstandard2.1/Azure.Storage.Blobs.dll' will not be loaded due to errors:
Azure.Storage.Blobs references strong named System.Diagnostics.DiagnosticSource Assembly references: 6.0.0.0 Found in project: 6.0.0.1.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Assembly 'Assets/Packages/Azure.Storage.Common.12.17.0/lib/netstandard2.0/Azure.Storage.Common.dll' will not be loaded due to errors:
Azure.Storage.Common references strong named System.Diagnostics.DiagnosticSource Assembly references: 6.0.0.0 Found in project: 6.0.0.1.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Assembly 'Assets/Packages/Azure.Core.1.35.0/lib/net472/Azure.Core.dll' will not be loaded due to errors:
Reference has errors 'System.Text.Json'.

Assembly 'Assets/Packages/System.Text.Json.4.7.2/lib/net461/System.Text.Json.dll' will not be loaded due to errors:
System.Text.Json references strong named System.Text.Encodings.Web Assembly references: 4.0.5.0 Found in project: 4.0.5.1.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
System.Text.Json references strong named System.Runtime.CompilerServices.Unsafe Assembly references: 4.0.6.0 Found in project: 6.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Assembly 'Assets/Packages/System.Memory.Data.1.0.2/lib/net461/System.Memory.Data.dll' will not be loaded due to errors:
System.Memory.Data references strong named System.Text.Json Assembly references: 4.0.0.0 Found in project: 4.0.1.2.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

-   **NuGet Package:**  Azure Blob Storage, 12.18.0 (latest)
-   **NuGetForUnity Version:** 4.0.1 (latest)
-   **Unity Version:** 2021.3.29f1
-   **Operating System:** Windows

**Comment by JoC0de** [comment]
Hi @LuMiN0uSaRc 
the README has a extra section regarding this error: https://github.com/GlitchEnzo/NuGetForUnity#version-conflicts
you just need to change a setting like mentioned in the Error.

**Comment by LuMiN0uSaRc** [comment]
Hi @JoC0de , thanks for the reply.
I tried changing the settings but the error persisted. 

I managed to resolve the issue by giving up on this, and installed the individual packages manually.

Thank you!
