### ISSUE TITLE
Support to target specific framework in packages.config

### ISSUE THREAD

**Issue by ArnavS59** [GlitchEnzo/NuGetForUnity#603]
## Description

Apparently, I have been trying to install nuget packages via the plugin for a specific netstandard framework eg netstandard2.0 , however the tag `targetFramework` [here ](https://learn.microsoft.com/en-us/nuget/reference/packages-config#:~:text=are%20not%20allowed.-,targetFramework,-No)  doesn't seem to be working in the packages.config. 
It seems to override or simply selects the framework which is set in the player settings-> API compatibility level. 

The plugin doesn't seem to parse the `targetFramework` tag.  
 ` <package id="LiteDB" version="5.0.16" manuallyInstalled="true"  targetFramework="netstandard2.0" />`

 It is important to have the possibility to downloads certain NuGet packages in certain target frameworks. 

My questions is there a way to specifically install a nuget package in a specific target framework without changing the framework under  player settings-> API compatibility level.  

-   **NuGetForUnity Version:** [4.0.1]
-   **Unity Version:** [2022.3.7f1 ]
-   **Operating System:** [Windows]

**Comment by JoC0de** [comment]
Hi @ArnavS59 thanks for the feature request.
To understand you correctly, you try to install a NuGet package that doesn't officially support the `API compatibility level` of you Unity project? Or do you like to force NuGetForUnity to select / prioritize a different targetFramework?

**Comment by ArnavS59** [comment]
Hi @JoC0de , I would like to select/specify/prioritize a different targetFramework for the NuGetForUnity without altering the `API Compatability level` setting.

**Comment by ArnavS59** [comment]
@JoC0de Hi do you have any update or pointers regarding the opened issue?

**Comment by TORISOUP** [comment]
It may have something to do with this issue.
I too feel that the ability to specify TargetFramework is needed.
https://github.com/GlitchEnzo/NuGetForUnity/issues/621
