### ISSUE TITLE
Contributing doc has no instructions for creating a new release

### ISSUE THREAD

**Issue by igor84** [GlitchEnzo/NuGetForUnity#614]
## Description

Should we include some instructions for creating a new release in the Contributing.md? Like what are all the needed steps so that packages are updated on nuget.org and new release is created on github?

Also @JoC0de can you release a new version now? Note that the last released version 4.0.2 doesn't seem to have a unitypackage file attached.

**Comment by igor84** [comment]
If I understood our github actions well all it takes to release packages on the nuget.org is to push a tag whose name starts with `v`. After that a Release can also be created on the gotihub. @JoC0de is that right?

Also I see you are not very active these days. Hope all is well but I wanted to ask you if it is ok if me and @popara96 take initiative and merge some pull requests you didn't review for some time and make a new release?

**Comment by JoC0de** [comment]
@igor84 Somehow I didn't had much time / was busy at work so I had not much desire in coding in my free time. I hope this will change again but I am not certain. For me its ok if you merge a PR without my review e.g. If I am to busy.

I added the missing `unitypackage` to the release.
The steps to create a new release are currently the following (probably we can automate even more):

1. Ensure that the new version is noted in `src/NuGetForUnity/package.json` and `src/NuGetForUnity/Editor/Ui/NugetPreferences.cs`
2. Create the Release on the GitHub Releases page -> use auto-generated Release-Notes
3. Creating the release also creates a new tag `v....` so the GitHub Action is triggered to create the binaries -> it automatically uploads the NuGet packages. It also generates the `unitypackage` but it needs to be manually downloaded -> uploaded to the Release page.

**Comment by igor84** [comment]
Thank you. I might do some work at the beginning of next week but then I will be on vacation for the next two weeks.

**Comment by JoC0de** [comment]
i added the documentation on how to release a new version in PR #681
