### ISSUE TITLE
SixLabors.ImageSharp fails to install properly.

### ISSUE THREAD

**Issue by jbvirt** [GlitchEnzo/NuGetForUnity#629]
## Description
Trying to install the SixLabors.ImageSharp NuGet Package installs everything _but_ the source .DLL's. See the image below.
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/110490781/b2c49bc9-aa33-4fad-804c-ec0c783c75c0)

-   **NuGet Package:** [SixLabors.ImageSharp v3.1.3](https://www.nuget.org/packages/SixLabors.ImageSharp/)
-   **NuGetForUnity Version:** 4.0.2 latest commit 25dcde8a309d6f273c82699af7967ef46048e5a1 
-   **Unity Version:** 2022.3.16f1
-   **Operating System:** Windows

**Comment by JoC0de** [comment]
Hi @jbvirt 
The package only supports .net 6 but unity only supports netstandard 2.1.
Probably you can try to add the dlls manually and see if unity supports it.

**Comment by jbvirt** [comment]
Good catch, thanks!
Version 3.1.3 is **not** supported in Unity because it needs the `System.Runtime.Intrinsics` namespace.
I was upgrading because of a recent CVE, but it seems that version 2.1.7 was also patched 10 hours ago.
