### ISSUE TITLE
安装FreeSql.Provider.Dameng

### ISSUE THREAD

**Issue by 9a6c** [GlitchEnzo/NuGetForUnity#633]
## Description

[Describe the issue you have. If applicable provide logs produced by enabeling verbose logging in the NuGetForUnity settings.]
我安装FreeSql.Provider.Dameng，它有.NETFramework 4.5版本， 但是安装的是.NETStandard 2.0
I installed FreeSql.Provider.Dameng, which has. NETFramework 4.5, but installed. NETStandard 2.0

![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/51264840/90945872-2780-4e80-81a2-11e8b948b5bc)
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/51264840/4fdd5b16-21f0-46fe-a169-feeda16f6781)

-   **NuGet Package:** [FreeSql.Provider.Dameng]
-   **NuGetForUnity Version:** [4.0.2]
-   **Unity Version:** [unity2021.3.6f1]
-   **Operating System:** [windows]

**Comment by JoC0de** [comment]
Hi @9a6c 
It depends on your unity settings if you project supports netstandard OD netframework. The settin is called API compatibility level. NuGeForUnity respects the setting and downloads the according package.

**Comment by 9a6c** [comment]
thanks
