### ISSUE TITLE
Selecting version did not work for a prerelease package

### ISSUE THREAD

**Issue by NITechLabs** [GlitchEnzo/NuGetForUnity#634]
## Issue with installing latest version, selects oldest automatically. Update does not work.

-   **NuGet Package:** Azure.AI.OpenAI version 1.0.0-beta.15
-   **NuGetForUnity Version:** 4.0.2
-   **Unity Version:** 2022.3.20f1
-   **Operating System:** Windows 11

After selecting Prerelease and searching for Azure.AI.OpenAI I want to select beta.15. But after selecting and pressing Install it installs beta.2. Update then shows beta.9 as option but that does not install as it (no longer?) does not exist!
Beta.2 does not have the required functionality.
How can I make sure NuGetForUnity will install the latest version?

**Comment by JoC0de** [comment]
Hi @NITechLabs 
Thanks for creating the issue.
I think this was fixed in #610, that is not included in 4.0.2.
We probably should release a new version that contains the fix. Untill we release a new version you can install the master version using the git-url install method.

**Comment by NITechLabs** [comment]
When I try the git-url install in Unity (2022.3.20) by copying the git url on the code page, Unity reports an error:

[Package Manager Window] Error adding package: https://github.com/GlitchEnzo/NuGetForUnity.git.
Unable to add package [https://github.com/GlitchEnzo/NuGetForUnity.git]:
  [https://github.com/GlitchEnzo/NuGetForUnity.git] does not point to a valid package. No package manifest was found.

Do you perhaps know how to fix this?

I fixed the OpenAI library install by adding it in Visual Studio, then copying that dll to the Plugins folder of my Unity project. Wroks but not very pretty :-)

**Comment by JoC0de** [comment]
I released 4.1.0
