### ISSUE TITLE
install r3 package error in tuanjie editor(china version)

### ISSUE THREAD

**Issue by maplelinyuan** [GlitchEnzo/NuGetForUnity#635]
## Description

[click install R3, console error:]
`Unable to install package R3 1.1.11
System.TypeInitializationException: The type initializer for 'NugetForUnity.TargetFrameworkResolver' threw an exception. ---> System.TypeInitializationException: The type initializer for 'NugetForUnity.Models.UnityVersion' threw an exception. ---> System.ArgumentException: Invalid unity version`

-   **NuGet Package:** [NuGetForUnity(https://github.com/GlitchEnzo/NuGetForUnity.git?path=/src/NuGetForUnity)]
-   **NuGetForUnity Version:** [4.0.2]
-   **Unity Version:** [Tuanjie 1.1.0]
-   **Operating System:** [MacOS monterey 12.5]

**Comment by JoC0de** [comment]
Hi @maplelinyuan 
We try to parse the unity version number to find out if it e.g. supports netstandard 2.1. As you use Tuanjie witch doesn't use t

**Comment by xiaoshanlin000** [comment]
团结引擎 版本是 2022.3.2t10 你可以修改源码 再导入
![20240519181050](https://github.com/GlitchEnzo/NuGetForUnity/assets/5867735/01d8fc32-7227-48bb-87ea-85bcc526a3b8)
