### ISSUE TITLE
UniTask didn't works correctly

### ISSUE THREAD

**Issue by nekolyst** [GlitchEnzo/NuGetForUnity#638]
If UniTask is installed using .unitypackage from https://github.com/Cysharp/UniTask, it works fine.
However, if installed from NuGetForUnity, there has issue, as shown in the screenshot, where certain syntax cannot be found and compilation errors are displayed.
![Imgur](https://imgur.com/1PkwC5b.jpg)

-   **NuGet Package:** UniTask v2.5.4
-   **NuGetForUnity Version:** v4.1.0
-   **Unity Version:** 2022.3.20f1
-   **Operating System:** Windows 11

**Comment by Akeit0** [comment]
From nuget.org, only UniTask.NetCore is supposed to be distributed.
