### ISSUE TITLE
How to download NAudio

### ISSUE THREAD

**Issue by toolgood** [GlitchEnzo/NuGetForUnity#649]
## Description

![图片](https://github.com/GlitchEnzo/NuGetForUnity/assets/17310407/09b30e52-684b-485e-a76a-6b74ce5059bd)

-   **NuGetForUnity Version:**  4.1.1
-   **Unity Version:** 2022.3

**Comment by JoC0de** [comment]
Hi,
you can see on NuGet https://www.nuget.org/packages/naudio and inside the NuGet package https://nuget.info/packages/NAudio/2.2.1:
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/53140583/50675d93-bfb8-435e-b746-de5996fddf1d)
that it only supports `.Net Framework` and `.Net 6`. You probably have configured your unity project with the Assembly Compatibility Level `.Net Standard` (enabled by default) so you need to switch the Assembly Compatibility Level to `.Net Framework`.
