### ISSUE TITLE
`Manage NuGet Packages` entry crashes Unity (Linux)

### ISSUE THREAD

**Issue by luca-schlecker** [GlitchEnzo/NuGetForUnity#653]
Clicking `Manage NuGet Packages` instantly crashes Unity.
If there are **no sources activated** in the preferences, the panel opens without a problem.

I did some digging and I think I was able to roughly locate the issues:

### Local Source
The moment `stream` is being disposed of in line 204, Unity crashes.
I also verified this by calling `stream.Dispose()` using the debugger.
I tried to leave out the `using`-block and it didn't crash when the only activated source was a local one.
https://github.com/GlitchEnzo/NuGetForUnity/blob/c7a7bbf74e102495c2afeb03e4b25ffb802611b7/src/NuGetForUnity/Editor/NuspecFile.cs#L197-L205

### Remote V3 Api Source
After `httpClient.SendAsync(...)` is called, Unity crashes. The debugger never reached Line 763.
https://github.com/GlitchEnzo/NuGetForUnity/blob/c7a7bbf74e102495c2afeb03e4b25ffb802611b7/src/NuGetForUnity/Editor/PackageSource/NugetApiClientV3.cs#L757-L767

<br/><br/>

Whilst debugging I also encountered a problem with this line:
https://github.com/GlitchEnzo/NuGetForUnity/blob/c7a7bbf74e102495c2afeb03e4b25ffb802611b7/src/NuGetForUnity/Editor/Ui/NugetWindow.cs#L464-L466

Marking the method `async` and substituting that part with:
```cs
availablePackages = await ConfigurationManager.SearchAsync(onlineSearchTerm, showOnlinePrerelease, numberToGet, numberToSkip);
```
seemed to fix it though and I was able to continue debugging.

<br/><br/>

-   **NuGetForUnity Version:** I tested with both `v4.1.0` and `v4.1.1`
-   **Unity Version:** I tested with both `2022.3.11f1` and `2023.2.20f1`
-   **Operating System:** Fedora 40

**Comment by luca-schlecker** [comment]
I was able to track it down even further by using a freshly created `HttpClient` instead of the one from the enclosing class.
:tada: Unity **won't** crash when removing `AutomaticDecompression` :tada::
https://github.com/GlitchEnzo/NuGetForUnity/blob/a0bb5566082ff88e5e6ebfb850dafe7fc63b0895/src/NuGetForUnity/Editor/PackageSource/NugetApiClientV3.cs#L85

<br/>

Installing packages is not possible though (incoming data is not decompressed), only browsing.
This is a step in the right direction though.

This, combined with the local repository crashing due to the zip entry, leads me to believe that the problem has to do with Mono and decompression.

**Comment by luca-schlecker** [comment]
Another thing I've just discovered:
This bug only occurs when installing Unity-Hub using the official yum repository ([as described here](https://docs.unity3d.com/hub/manual/InstallHub.html#red-hat-enterprise-linux-rhel-or-centos))

I tried installing Unity-Hub using Flatpak and it suddenly started working.

**Comment by JoC0de** [comment]
Hi @luca-schlecker,
Thanks for investigating the issue.
Seems strange that it is working when using a different Unity Hub. Could be that the installer includes a different version of the mono runtime.
Is now everything working or do we need to change something in the code of NuGeForUnity? As you mentioned runtime, you can change the Assembly Compatibility level of Editor code so e.g. NuGeForUnity uses .Net standard runtime.

**Comment by luca-schlecker** [comment]
Everything seems to be working properly using the Flatpak version.
Quite a strange behavior. I had a quick look, seems like the Flathub package is based on the `.deb` variant. But I won't be able to take a deeper look into it.
I don't think this issue is on NuGetForUnity's end but rather on Unity's and I'll thus close this issue.

**Comment by luca-schlecker** [comment]
I just found out that the issue has to do with the zlib-ng library (used in Fedora 40).
It's only a matter of time until the fix lands.
https://github.com/zlib-ng/zlib-ng/issues/1708
