### ISSUE TITLE
Checking of checkboxes anywhere in the Inspector deselects the currently selected gameobject

### ISSUE THREAD

**Issue by Geminior** [GlitchEnzo/NuGetForUnity#660]
The plugin makes interaction with checkboxes unusable.

It is trivial to reproduce:
1. Find/Create a prefab with a Monobehaviour that exposes a boolean
2. Click the checkbox in the Inspector
3. Observe that the selection is cleared (Inspector goes blank)

This is on Unity version 2022.3.23. I have not tried other versions.

**Comment by igor84** [comment]
Hi @Geminior. Can you provide information on why you think this is related with NugetForUnity?

**Comment by Geminior** [comment]
I realize it sounds unrelated, however, it simply starts occurring once NugetForUnity is added to the project, and once removed it returns to normal.
I have updated the original report with the Unity version number, which may be relevant.

**Comment by igor84** [comment]
I tried reproducing this in Unity 2022.3.23f1 but everything seems to work. I installed NugetforUnity through Unity package manager and I even installed a few packages. @Geminior can you reproduce this in a new empty project?

**Comment by Geminior** [comment]
Hmm I will try, I suppose it could be some incompatibility with some other
package.

**Comment by igor84** [comment]
@Geminior thank you for the repro project. I managed to isolate that the call to AssetDatabase.StopAssetEditing in NugetAssetPostprocessor.cs is causing Unity to deselect the editing object on edit. I made a fix in pull request #661.

**Comment by Geminior** [comment]
Sweet, thanks for the swift update, glad you were able to locate the issue :)

**Comment by igor84** [comment]
Fix is merged into master.
