### ISSUE TITLE
Make package restore get the EXACT version

### ISSUE THREAD

**Issue by GlitchEnzo** [GlitchEnzo/NuGetForUnity#75]
Currently it gets a package version that is GREATER THAN OR EQUAL to the specific version,

This can cause issues with the cached packages.

**Comment by GlitchEnzo** [comment]
This is indeed NuGet behaviour in VS:

http://stackoverflow.com/questions/11630414/nugets-restore-package-insists-on-specific-package-versions

**Comment by jwittner** [comment]
I believe this is fixed now.
