### ISSUE TITLE
Packages with multiple unity targets are not supported

### ISSUE THREAD

**Issue by jwittner** [GlitchEnzo/NuGetForUnity#83]
Current methodology for selecting what lib folders to keep doesn't allow shipping multiple Unity targets in one package.

Suggested PR to resolve incoming.

**Comment by GlitchEnzo** [comment]
The "net35-unity full v3.5" style targets are interesting. Is there documentation somewhere describing these?

**Comment by jwittner** [comment]
They are added to Visual Studio when you install the [Visual Studio for Unity Tools](https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-studio-tools-for-unity). There's not much on what those targets mean, but they overlap the capabilities of the Unity Editor under a few different circumstances, e.g. in the editor or not.
