### ISSUE TITLE
Cannot Install Package

### ISSUE THREAD

**Issue by felixwcf** [GlitchEnzo/NuGetForUnity#86]
I get error when clicking Install button, want tot download Mathnet.Numerics.
Getting this error:

System.ArgumentException: Path is empty
  at System.IO.Directory.CreateDirectory (System.String path) [0x0001c] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:78 
  at Ionic.Zip.ZipEntry.InternalExtract (System.String baseDir, System.IO.Stream outstream, System.String password) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetHelper:Install(NugetPackage, Boolean)
NugetForUnity.NugetWindow:DrawPackage(NugetPackage)
NugetForUnity.NugetWindow:DrawOnline()
NugetForUnity.NugetWindow:OnGUI()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I'm using Unity 2017.1.1.f1 Personal Edition in MacOS 10.12.6.

**Comment by GlitchEnzo** [comment]
Were you using the 0.0.10 binary or the 0.0.11 source code?

I was able to successfully install it using the latest 0.0.11 source on Windows 10.

**Comment by felixwcf** [comment]
NugetForUNity ver: v0.0.11.

**Comment by GlitchEnzo** [comment]
Unfortunately I don't have a Mac, and so I've never run NuGetForUnity on one.  It appears there are some issues, but it'll be hard for me to track down what exactly they are myself.

**Comment by Ziugy** [comment]
@felixwcf could you enable verbose logging in the NuGet preferences tab and post the screen cap to help us determine the pathing issue?

**Comment by daemon4d** [comment]
I used https://www.nuget.org/packages/DotNetZip/ instead of Ionic.Zip and got rid of this error.

**Comment by raunaqrox** [comment]
I too was getting similar error, this is from verbose logging.
<img width="1006" alt="screen shot 2017-11-15 at 4 14 36 am" src="https://user-images.githubusercontent.com/2609361/32809115-af343672-c9bb-11e7-9c05-b06b26ac5565.png">

**Comment by jwittner** [comment]
I wonder if changing zip libraries would fix this and #114.

**Comment by jwittner** [comment]
We moved to dotnetzip a while back.
