### ISSUE TITLE
VSTS authenticated feeds are not supported.

### ISSUE THREAD

**Issue by jwittner** [GlitchEnzo/NuGetForUnity#89]
Right now there's no authentication process for getting credentials through the client into the api requests.

Can we run the CredentialProvider ourselves?
Can we use user name and PAT to auth?

**Comment by ForrestTrepte** [comment]
It looks like I can authenticate with my VSTS feed as follows:
1) Add credentials to the HttpWebRequest e.g. getRequest.Credentials = new NetworkCredential("forrest@contoso.com", "_VSTS Token Goes Here_")
2) Add the package source under NuGetForUnity Preferences with the V2 base URL e.g. https://myproject.pkgs.visualstudio.com/_packaging/myproject/nuget/v2/.

I will work on adding a user name and password field to the NuGetForUnity preferences UI for this. Will make a pull request when I get this working.

**Comment by ForrestTrepte** [comment]
I may have spoken too soon. Although this successfully downloads the list of packages from VSTS, it fails when attempting to install one of those packages. It fails with "The remote server returned an error: (400) Authentication information is not given in the correct format. Check the value of Authorization header.." Frustratingly, the same code that fails in Unity succeeds when run in a C# console application. Perhaps a difference in between Mono and .NET HttpWebRequest?

**Comment by ForrestTrepte** [comment]
This was fixed by #96.
