### ISSUE TITLE
Support "Assembly Definition Files" in Unity 2017.3+

### ISSUE THREAD

**Issue by GlitchEnzo** [GlitchEnzo/NuGetForUnity#92]
Currently, NuGetForUnity assumes all of the "loose" scripts will get compiled into one single assembly (usually `Assembly-CSharp.dll`).  Thus, all NuGet package references are assumed to be shared by the entire project and are installed into a `Packages` folder at the root of the project.

If someone is using the new [Assembly Definition Files](https://drive.google.com/file/d/0Bykxs2qcd6PSUTJhYkJySS1hazA/view) feature of [Unity 2017.3](https://blogs.unity3d.com/2017/09/30/unity-2017-3-beta-is-out/) or later, they might want their separate assemblies to have separate NuGet package dependencies.

Personally, I'm uncertain if this is even possible as this moment. I have yet to test the Assembly Definition File feature and I don't know how it handles pre-compiled assemblies inside of a folder containing a .assembly.json file.

**Comment by xmedeko** [comment]
The assembly definition file for Unity 2018 is `*.asmdef`, see https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

I think, that if you want to use packages just for one assembly, that it has to be copied (linked?) to the assembly folder (or some of it's subfolders). At least that's what's wotking with DLLs placed into the `MyAssembly\Plugins`.

**Comment by jwittner** [comment]
Closing as people can achieve and ship these in whatever shapes they desire.
