### ISSUE TITLE
What if compile errors prevent NuGetForUnity from executing, but you need it in order to download fixes?

### ISSUE THREAD

**Issue by ForrestTrepte** [GlitchEnzo/NuGetForUnity#93]
If there is a compile error in any editor script, then the NuGetForUnity UI won't appear when you open your project. It seems like this would be a problem if you need to use NuGetForUnity to pull down a new version of your package in order to fix the compile error.

Questions:
1. Have others found this to be a problem?
1. How would one get unstuck in this case? Modify, comment out, or delete scripts until you're building again so you can pull down the update? Manually get the updated package in a clean version of NuGetForUnity and then copy it across?

Proposed solution: Build the NuGetForUnity scripts as a DLL. This would allow Unity to load the DLL even while other scripts in your project don't compile.

Does that sound like a good idea? If we use a Visual Studio solution to build this DLL would that work? I have created Visual Studio solutions targeting Unity DLLs, but I don't know if there are Mac users who wouldn't be able to use that approach.

**Comment by GlitchEnzo** [comment]
NuGetForUnity is already built and released as a precompiled DLL for exactly the reasons you have stated.  Check out the [Releases](https://github.com/GlitchEnzo/NuGetForUnity/releases) section which are .unitypackage files with the prebuilt DLL inside. 

The DLL is built from the [CreateDLL.sln](https://github.com/GlitchEnzo/NuGetForUnity/releases) which you can see is included in the source.  It has the single [CreateDLL.csproj](https://github.com/GlitchEnzo/NuGetForUnity/blob/master/CreateDLL/CreateDLL.csproj) file that has the Unity .cs scripts added via a link.

This precompiled DLL should be compatible with Mono on Mac, although I have never had the opportunity to test it myself.

**Comment by ForrestTrepte** [comment]
Perfect! Thanks for explaining.
