### ISSUE TITLE
Create .nuspec file - unexpected behavior

### ISSUE THREAD

**Issue by Ziugy** [GlitchEnzo/NuGetForUnity#99]
Creating the .nuspec file through the right click context menu in the Project window doesn't work as expected.

* Creation of .nuspec file should auto-focus in renaming the file.
* Right-clicking on a folder directly under `Assets` puts the .nuspec file in `Assets`. Expected behavior should be similar to creating other assets, like `Materials`.
    * This behavior also happens if the right-click was done from the folder's content panel.
* Running this twice causes an exception.

**Comment by GlitchEnzo** [comment]
> - Right-clicking on a folder directly under Assets puts the .nuspec file in Assets.
> - Running this twice causes an exception.

I'm not seeing either of those behaviors myself.  However, I _am_ seeing an issue where right-clicking on a _file_ fails to create a new .nuspec file at all.

> Creation of .nuspec file should auto-focus in renaming the file.

That's a good idea. I'll see what I can do.

**Comment by GlitchEnzo** [comment]
I've fixed the file creation issue and I've made it so the new .nuspec is automatically selected after being created. It isn't automatically put into rename "mode" though. The user still has to press F2 (on Windows) or Return (on Mac).
#117

**Comment by jwittner** [comment]
Closing as GlitchEnzo added some of the desired functionality.
